// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdminActivities = `-- name: CountAdminActivities :one
SELECT COUNT(*) FROM activities
`

// CountAdminActivities
//
//	SELECT COUNT(*) FROM activities
func (q *Queries) CountAdminActivities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminActivities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublicActivities = `-- name: CountPublicActivities :one
SELECT COUNT(*)
FROM activities AS a
WHERE a.status = 'published'
  AND (
    $1::TEXT = ''
    OR a.title_id ILIKE '%' || $1::TEXT || '%'
    OR a.title_en ILIKE '%' || $1::TEXT || '%'
    OR a.caption_id ILIKE '%' || $1::TEXT || '%'
    OR a.caption_en ILIKE '%' || $1::TEXT || '%'
    OR EXISTS (
        SELECT 1
        FROM activity_tags AS t
        WHERE t.activity_id = a.id
          AND t.value ILIKE '%' || $1::TEXT || '%'
    )
  )
  AND (
    $2::activity_category IS NULL
    OR a.category = $2::activity_category
  )
`

type CountPublicActivitiesParams struct {
	Search   string            `db:"search" json:"search"`
	Category *ActivityCategory `db:"category" json:"category"`
}

// CountPublicActivities
//
//	SELECT COUNT(*)
//	FROM activities AS a
//	WHERE a.status = 'published'
//	  AND (
//	    $1::TEXT = ''
//	    OR a.title_id ILIKE '%' || $1::TEXT || '%'
//	    OR a.title_en ILIKE '%' || $1::TEXT || '%'
//	    OR a.caption_id ILIKE '%' || $1::TEXT || '%'
//	    OR a.caption_en ILIKE '%' || $1::TEXT || '%'
//	    OR EXISTS (
//	        SELECT 1
//	        FROM activity_tags AS t
//	        WHERE t.activity_id = a.id
//	          AND t.value ILIKE '%' || $1::TEXT || '%'
//	    )
//	  )
//	  AND (
//	    $2::activity_category IS NULL
//	    OR a.category = $2::activity_category
//	  )
func (q *Queries) CountPublicActivities(ctx context.Context, arg CountPublicActivitiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublicActivities, arg.Search, arg.Category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities (
    slug,
    title_id,
    title_en,
    caption_id,
    caption_en,
    body_id,
    body_en,
    category,
    activity_date,
    status,
    pinned,
    progress,
    related_project,
    published_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    CASE
        WHEN $10::activity_status = 'published' THEN NOW()
        ELSE NULL
    END
)
RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
`

type CreateActivityParams struct {
	Slug           *string           `db:"slug" json:"slug"`
	TitleID        string            `db:"title_id" json:"title_id"`
	TitleEn        string            `db:"title_en" json:"title_en"`
	CaptionID      string            `db:"caption_id" json:"caption_id"`
	CaptionEn      string            `db:"caption_en" json:"caption_en"`
	BodyID         string            `db:"body_id" json:"body_id"`
	BodyEn         string            `db:"body_en" json:"body_en"`
	Category       ActivityCategory  `db:"category" json:"category"`
	ActivityDate   pgtype.Date       `db:"activity_date" json:"activity_date"`
	Status         ActivityStatus    `db:"status" json:"status"`
	Pinned         bool              `db:"pinned" json:"pinned"`
	Progress       *ActivityProgress `db:"progress" json:"progress"`
	RelatedProject *string           `db:"related_project" json:"related_project"`
}

// CreateActivity
//
//	INSERT INTO activities (
//	    slug,
//	    title_id,
//	    title_en,
//	    caption_id,
//	    caption_en,
//	    body_id,
//	    body_en,
//	    category,
//	    activity_date,
//	    status,
//	    pinned,
//	    progress,
//	    related_project,
//	    published_at
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11,
//	    $12,
//	    $13,
//	    CASE
//	        WHEN $10::activity_status = 'published' THEN NOW()
//	        ELSE NULL
//	    END
//	)
//	RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.Slug,
		arg.TitleID,
		arg.TitleEn,
		arg.CaptionID,
		arg.CaptionEn,
		arg.BodyID,
		arg.BodyEn,
		arg.Category,
		arg.ActivityDate,
		arg.Status,
		arg.Pinned,
		arg.Progress,
		arg.RelatedProject,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleID,
		&i.TitleEn,
		&i.CaptionID,
		&i.CaptionEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Category,
		&i.ActivityDate,
		&i.Status,
		&i.Pinned,
		&i.Progress,
		&i.RelatedProject,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteActivity = `-- name: DeleteActivity :execrows
DELETE FROM activities WHERE id = $1
`

// DeleteActivity
//
//	DELETE FROM activities WHERE id = $1
func (q *Queries) DeleteActivity(ctx context.Context, activityID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteActivity, activityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteActivityAssets = `-- name: DeleteActivityAssets :exec
DELETE FROM activity_assets WHERE activity_id = $1
`

// DeleteActivityAssets
//
//	DELETE FROM activity_assets WHERE activity_id = $1
func (q *Queries) DeleteActivityAssets(ctx context.Context, activityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivityAssets, activityID)
	return err
}

const deleteActivitySlugRedirect = `-- name: DeleteActivitySlugRedirect :exec
DELETE FROM activity_slug_redirects WHERE slug = $1
`

// DeleteActivitySlugRedirect
//
//	DELETE FROM activity_slug_redirects WHERE slug = $1
func (q *Queries) DeleteActivitySlugRedirect(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deleteActivitySlugRedirect, slug)
	return err
}

const deleteActivityTags = `-- name: DeleteActivityTags :exec
DELETE FROM activity_tags WHERE activity_id = $1
`

// DeleteActivityTags
//
//	DELETE FROM activity_tags WHERE activity_id = $1
func (q *Queries) DeleteActivityTags(ctx context.Context, activityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivityTags, activityID)
	return err
}

const getActivityByID = `-- name: GetActivityByID :one
SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at FROM activities WHERE id = $1
`

// GetActivityByID
//
//	SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at FROM activities WHERE id = $1
func (q *Queries) GetActivityByID(ctx context.Context, activityID pgtype.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, getActivityByID, activityID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleID,
		&i.TitleEn,
		&i.CaptionID,
		&i.CaptionEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Category,
		&i.ActivityDate,
		&i.Status,
		&i.Pinned,
		&i.Progress,
		&i.RelatedProject,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivityIDByRedirectSlug = `-- name: GetActivityIDByRedirectSlug :one
SELECT activity_id
FROM activity_slug_redirects
WHERE slug = $1
`

// GetActivityIDByRedirectSlug
//
//	SELECT activity_id
//	FROM activity_slug_redirects
//	WHERE slug = $1
func (q *Queries) GetActivityIDByRedirectSlug(ctx context.Context, slug string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getActivityIDByRedirectSlug, slug)
	var activity_id pgtype.UUID
	err := row.Scan(&activity_id)
	return activity_id, err
}

const getMediaAssetForActivityLink = `-- name: GetMediaAssetForActivityLink :one
SELECT id, kind, status
FROM media_assets
WHERE id = $1
`

type GetMediaAssetForActivityLinkRow struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Kind   MediaKind   `db:"kind" json:"kind"`
	Status AssetStatus `db:"status" json:"status"`
}

// GetMediaAssetForActivityLink
//
//	SELECT id, kind, status
//	FROM media_assets
//	WHERE id = $1
func (q *Queries) GetMediaAssetForActivityLink(ctx context.Context, assetID pgtype.UUID) (GetMediaAssetForActivityLinkRow, error) {
	row := q.db.QueryRow(ctx, getMediaAssetForActivityLink, assetID)
	var i GetMediaAssetForActivityLinkRow
	err := row.Scan(&i.ID, &i.Kind, &i.Status)
	return i, err
}

const getPublishedActivityByID = `-- name: GetPublishedActivityByID :one
SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
FROM activities
WHERE id = $1
  AND status = 'published'
`

// GetPublishedActivityByID
//
//	SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
//	FROM activities
//	WHERE id = $1
//	  AND status = 'published'
func (q *Queries) GetPublishedActivityByID(ctx context.Context, activityID pgtype.UUID) (Activity, error) {
	row := q.db.QueryRow(ctx, getPublishedActivityByID, activityID)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleID,
		&i.TitleEn,
		&i.CaptionID,
		&i.CaptionEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Category,
		&i.ActivityDate,
		&i.Status,
		&i.Pinned,
		&i.Progress,
		&i.RelatedProject,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedActivityBySlug = `-- name: GetPublishedActivityBySlug :one
SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
FROM activities
WHERE slug = $1
  AND status = 'published'
`

// GetPublishedActivityBySlug
//
//	SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
//	FROM activities
//	WHERE slug = $1
//	  AND status = 'published'
func (q *Queries) GetPublishedActivityBySlug(ctx context.Context, slug *string) (Activity, error) {
	row := q.db.QueryRow(ctx, getPublishedActivityBySlug, slug)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleID,
		&i.TitleEn,
		&i.CaptionID,
		&i.CaptionEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Category,
		&i.ActivityDate,
		&i.Status,
		&i.Pinned,
		&i.Progress,
		&i.RelatedProject,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertActivityAsset = `-- name: InsertActivityAsset :exec
INSERT INTO activity_assets (
    activity_id,
    asset_id,
    role,
    position,
    alt_text,
    caption_id,
    caption_en,
    label_id,
    label_en,
    crop,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type InsertActivityAssetParams struct {
	ActivityID pgtype.UUID       `db:"activity_id" json:"activity_id"`
	AssetID    pgtype.UUID       `db:"asset_id" json:"asset_id"`
	Role       ActivityAssetRole `db:"role" json:"role"`
	Position   int32             `db:"position" json:"position"`
	AltText    string            `db:"alt_text" json:"alt_text"`
	CaptionID  string            `db:"caption_id" json:"caption_id"`
	CaptionEn  string            `db:"caption_en" json:"caption_en"`
	LabelID    string            `db:"label_id" json:"label_id"`
	LabelEn    string            `db:"label_en" json:"label_en"`
	Crop       []byte            `db:"crop" json:"crop"`
	Metadata   []byte            `db:"metadata" json:"metadata"`
}

// InsertActivityAsset
//
//	INSERT INTO activity_assets (
//	    activity_id,
//	    asset_id,
//	    role,
//	    position,
//	    alt_text,
//	    caption_id,
//	    caption_en,
//	    label_id,
//	    label_en,
//	    crop,
//	    metadata
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8,
//	    $9,
//	    $10,
//	    $11
//	)
func (q *Queries) InsertActivityAsset(ctx context.Context, arg InsertActivityAssetParams) error {
	_, err := q.db.Exec(ctx, insertActivityAsset,
		arg.ActivityID,
		arg.AssetID,
		arg.Role,
		arg.Position,
		arg.AltText,
		arg.CaptionID,
		arg.CaptionEn,
		arg.LabelID,
		arg.LabelEn,
		arg.Crop,
		arg.Metadata,
	)
	return err
}

const insertActivitySlugRedirect = `-- name: InsertActivitySlugRedirect :exec
INSERT INTO activity_slug_redirects (slug, activity_id)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET activity_id = EXCLUDED.activity_id
`

type InsertActivitySlugRedirectParams struct {
	Slug       string      `db:"slug" json:"slug"`
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
}

// InsertActivitySlugRedirect
//
//	INSERT INTO activity_slug_redirects (slug, activity_id)
//	VALUES ($1, $2)
//	ON CONFLICT (slug) DO UPDATE SET activity_id = EXCLUDED.activity_id
func (q *Queries) InsertActivitySlugRedirect(ctx context.Context, arg InsertActivitySlugRedirectParams) error {
	_, err := q.db.Exec(ctx, insertActivitySlugRedirect, arg.Slug, arg.ActivityID)
	return err
}

const insertActivityTag = `-- name: InsertActivityTag :exec
INSERT INTO activity_tags (activity_id, position, value)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertActivityTagParams struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	Position   int32       `db:"position" json:"position"`
	Value      string      `db:"value" json:"value"`
}

// InsertActivityTag
//
//	INSERT INTO activity_tags (activity_id, position, value)
//	VALUES (
//	    $1,
//	    $2,
//	    $3
//	)
func (q *Queries) InsertActivityTag(ctx context.Context, arg InsertActivityTagParams) error {
	_, err := q.db.Exec(ctx, insertActivityTag, arg.ActivityID, arg.Position, arg.Value)
	return err
}

const listActivityAssets = `-- name: ListActivityAssets :many
SELECT
    link.activity_id,
    link.asset_id,
    link.role,
    link.position,
    link.alt_text,
    link.caption_id,
    link.caption_en,
    link.label_id,
    link.label_en,
    link.crop,
    link.metadata AS link_metadata,
    asset.kind,
    asset.status,
    asset.original_filename,
    asset.mime_type,
    asset.byte_size,
    asset.width,
    asset.height,
    asset.duration_ms,
    asset.page_count
FROM activity_assets AS link
JOIN media_assets AS asset ON asset.id = link.asset_id
WHERE link.activity_id = $1
ORDER BY link.role, link.position
`

type ListActivityAssetsRow struct {
	ActivityID       pgtype.UUID       `db:"activity_id" json:"activity_id"`
	AssetID          pgtype.UUID       `db:"asset_id" json:"asset_id"`
	Role             ActivityAssetRole `db:"role" json:"role"`
	Position         int32             `db:"position" json:"position"`
	AltText          string            `db:"alt_text" json:"alt_text"`
	CaptionID        string            `db:"caption_id" json:"caption_id"`
	CaptionEn        string            `db:"caption_en" json:"caption_en"`
	LabelID          string            `db:"label_id" json:"label_id"`
	LabelEn          string            `db:"label_en" json:"label_en"`
	Crop             []byte            `db:"crop" json:"crop"`
	LinkMetadata     []byte            `db:"link_metadata" json:"link_metadata"`
	Kind             MediaKind         `db:"kind" json:"kind"`
	Status           AssetStatus       `db:"status" json:"status"`
	OriginalFilename string            `db:"original_filename" json:"original_filename"`
	MimeType         string            `db:"mime_type" json:"mime_type"`
	ByteSize         int64             `db:"byte_size" json:"byte_size"`
	Width            *int32            `db:"width" json:"width"`
	Height           *int32            `db:"height" json:"height"`
	DurationMs       *int64            `db:"duration_ms" json:"duration_ms"`
	PageCount        *int32            `db:"page_count" json:"page_count"`
}

// ListActivityAssets
//
//	SELECT
//	    link.activity_id,
//	    link.asset_id,
//	    link.role,
//	    link.position,
//	    link.alt_text,
//	    link.caption_id,
//	    link.caption_en,
//	    link.label_id,
//	    link.label_en,
//	    link.crop,
//	    link.metadata AS link_metadata,
//	    asset.kind,
//	    asset.status,
//	    asset.original_filename,
//	    asset.mime_type,
//	    asset.byte_size,
//	    asset.width,
//	    asset.height,
//	    asset.duration_ms,
//	    asset.page_count
//	FROM activity_assets AS link
//	JOIN media_assets AS asset ON asset.id = link.asset_id
//	WHERE link.activity_id = $1
//	ORDER BY link.role, link.position
func (q *Queries) ListActivityAssets(ctx context.Context, activityID pgtype.UUID) ([]ListActivityAssetsRow, error) {
	rows, err := q.db.Query(ctx, listActivityAssets, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityAssetsRow{}
	for rows.Next() {
		var i ListActivityAssetsRow
		if err := rows.Scan(
			&i.ActivityID,
			&i.AssetID,
			&i.Role,
			&i.Position,
			&i.AltText,
			&i.CaptionID,
			&i.CaptionEn,
			&i.LabelID,
			&i.LabelEn,
			&i.Crop,
			&i.LinkMetadata,
			&i.Kind,
			&i.Status,
			&i.OriginalFilename,
			&i.MimeType,
			&i.ByteSize,
			&i.Width,
			&i.Height,
			&i.DurationMs,
			&i.PageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityTags = `-- name: ListActivityTags :many
SELECT activity_id, position, value
FROM activity_tags
WHERE activity_id = $1
ORDER BY position
`

// ListActivityTags
//
//	SELECT activity_id, position, value
//	FROM activity_tags
//	WHERE activity_id = $1
//	ORDER BY position
func (q *Queries) ListActivityTags(ctx context.Context, activityID pgtype.UUID) ([]ActivityTag, error) {
	rows, err := q.db.Query(ctx, listActivityTags, activityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityTag{}
	for rows.Next() {
		var i ActivityTag
		if err := rows.Scan(&i.ActivityID, &i.Position, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminActivities = `-- name: ListAdminActivities :many
SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
FROM activities
ORDER BY updated_at DESC, created_at DESC
LIMIT $2
OFFSET $1
`

type ListAdminActivitiesParams struct {
	PageOffset int32 `db:"page_offset" json:"page_offset"`
	PageLimit  int32 `db:"page_limit" json:"page_limit"`
}

// ListAdminActivities
//
//	SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
//	FROM activities
//	ORDER BY updated_at DESC, created_at DESC
//	LIMIT $2
//	OFFSET $1
func (q *Queries) ListAdminActivities(ctx context.Context, arg ListAdminActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listAdminActivities, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TitleID,
			&i.TitleEn,
			&i.CaptionID,
			&i.CaptionEn,
			&i.BodyID,
			&i.BodyEn,
			&i.Category,
			&i.ActivityDate,
			&i.Status,
			&i.Pinned,
			&i.Progress,
			&i.RelatedProject,
			&i.PublishedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicActivities = `-- name: ListPublicActivities :many
SELECT a.id, a.slug, a.title_id, a.title_en, a.caption_id, a.caption_en, a.body_id, a.body_en, a.category, a.activity_date, a.status, a.pinned, a.progress, a.related_project, a.published_at, a.version, a.created_at, a.updated_at
FROM activities AS a
WHERE a.status = 'published'
  AND (
    $1::TEXT = ''
    OR a.title_id ILIKE '%' || $1::TEXT || '%'
    OR a.title_en ILIKE '%' || $1::TEXT || '%'
    OR a.caption_id ILIKE '%' || $1::TEXT || '%'
    OR a.caption_en ILIKE '%' || $1::TEXT || '%'
    OR EXISTS (
        SELECT 1
        FROM activity_tags AS t
        WHERE t.activity_id = a.id
          AND t.value ILIKE '%' || $1::TEXT || '%'
    )
  )
  AND (
    $2::activity_category IS NULL
    OR a.category = $2::activity_category
  )
ORDER BY a.pinned DESC, a.activity_date DESC, a.created_at DESC
LIMIT $4
OFFSET $3
`

type ListPublicActivitiesParams struct {
	Search     string            `db:"search" json:"search"`
	Category   *ActivityCategory `db:"category" json:"category"`
	PageOffset int32             `db:"page_offset" json:"page_offset"`
	PageLimit  int32             `db:"page_limit" json:"page_limit"`
}

// ListPublicActivities
//
//	SELECT a.id, a.slug, a.title_id, a.title_en, a.caption_id, a.caption_en, a.body_id, a.body_en, a.category, a.activity_date, a.status, a.pinned, a.progress, a.related_project, a.published_at, a.version, a.created_at, a.updated_at
//	FROM activities AS a
//	WHERE a.status = 'published'
//	  AND (
//	    $1::TEXT = ''
//	    OR a.title_id ILIKE '%' || $1::TEXT || '%'
//	    OR a.title_en ILIKE '%' || $1::TEXT || '%'
//	    OR a.caption_id ILIKE '%' || $1::TEXT || '%'
//	    OR a.caption_en ILIKE '%' || $1::TEXT || '%'
//	    OR EXISTS (
//	        SELECT 1
//	        FROM activity_tags AS t
//	        WHERE t.activity_id = a.id
//	          AND t.value ILIKE '%' || $1::TEXT || '%'
//	    )
//	  )
//	  AND (
//	    $2::activity_category IS NULL
//	    OR a.category = $2::activity_category
//	  )
//	ORDER BY a.pinned DESC, a.activity_date DESC, a.created_at DESC
//	LIMIT $4
//	OFFSET $3
func (q *Queries) ListPublicActivities(ctx context.Context, arg ListPublicActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listPublicActivities,
		arg.Search,
		arg.Category,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Activity{}
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.TitleID,
			&i.TitleEn,
			&i.CaptionID,
			&i.CaptionEn,
			&i.BodyID,
			&i.BodyEn,
			&i.Category,
			&i.ActivityDate,
			&i.Status,
			&i.Pinned,
			&i.Progress,
			&i.RelatedProject,
			&i.PublishedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlugsWithPrefix = `-- name: ListSlugsWithPrefix :many
SELECT a.slug AS slug
FROM activities AS a
WHERE a.slug LIKE $1
UNION
SELECT r.slug AS slug
FROM activity_slug_redirects AS r
WHERE r.slug LIKE $1
`

// ListSlugsWithPrefix
//
//	SELECT a.slug AS slug
//	FROM activities AS a
//	WHERE a.slug LIKE $1
//	UNION
//	SELECT r.slug AS slug
//	FROM activity_slug_redirects AS r
//	WHERE r.slug LIKE $1
func (q *Queries) ListSlugsWithPrefix(ctx context.Context, pattern *string) ([]*string, error) {
	rows, err := q.db.Query(ctx, listSlugsWithPrefix, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var slug *string
		if err := rows.Scan(&slug); err != nil {
			return nil, err
		}
		items = append(items, slug)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateActivity = `-- name: UpdateActivity :one
UPDATE activities
SET slug = $1,
    title_id = $2,
    title_en = $3,
    caption_id = $4,
    caption_en = $5,
    body_id = $6,
    body_en = $7,
    category = $8,
    activity_date = $9,
    status = $10,
    pinned = $11,
    progress = $12,
    related_project = $13,
    published_at = CASE
        WHEN $10::activity_status = 'published'
            THEN COALESCE(published_at, NOW())
        ELSE NULL
    END,
    version = version + 1,
    updated_at = NOW()
WHERE id = $14
  AND version = $15
RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
`

type UpdateActivityParams struct {
	Slug            *string           `db:"slug" json:"slug"`
	TitleID         string            `db:"title_id" json:"title_id"`
	TitleEn         string            `db:"title_en" json:"title_en"`
	CaptionID       string            `db:"caption_id" json:"caption_id"`
	CaptionEn       string            `db:"caption_en" json:"caption_en"`
	BodyID          string            `db:"body_id" json:"body_id"`
	BodyEn          string            `db:"body_en" json:"body_en"`
	Category        ActivityCategory  `db:"category" json:"category"`
	ActivityDate    pgtype.Date       `db:"activity_date" json:"activity_date"`
	Status          ActivityStatus    `db:"status" json:"status"`
	Pinned          bool              `db:"pinned" json:"pinned"`
	Progress        *ActivityProgress `db:"progress" json:"progress"`
	RelatedProject  *string           `db:"related_project" json:"related_project"`
	ActivityID      pgtype.UUID       `db:"activity_id" json:"activity_id"`
	ExpectedVersion int64             `db:"expected_version" json:"expected_version"`
}

// UpdateActivity
//
//	UPDATE activities
//	SET slug = $1,
//	    title_id = $2,
//	    title_en = $3,
//	    caption_id = $4,
//	    caption_en = $5,
//	    body_id = $6,
//	    body_en = $7,
//	    category = $8,
//	    activity_date = $9,
//	    status = $10,
//	    pinned = $11,
//	    progress = $12,
//	    related_project = $13,
//	    published_at = CASE
//	        WHEN $10::activity_status = 'published'
//	            THEN COALESCE(published_at, NOW())
//	        ELSE NULL
//	    END,
//	    version = version + 1,
//	    updated_at = NOW()
//	WHERE id = $14
//	  AND version = $15
//	RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
func (q *Queries) UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error) {
	row := q.db.QueryRow(ctx, updateActivity,
		arg.Slug,
		arg.TitleID,
		arg.TitleEn,
		arg.CaptionID,
		arg.CaptionEn,
		arg.BodyID,
		arg.BodyEn,
		arg.Category,
		arg.ActivityDate,
		arg.Status,
		arg.Pinned,
		arg.Progress,
		arg.RelatedProject,
		arg.ActivityID,
		arg.ExpectedVersion,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.TitleID,
		&i.TitleEn,
		&i.CaptionID,
		&i.CaptionEn,
		&i.BodyID,
		&i.BodyEn,
		&i.Category,
		&i.ActivityDate,
		&i.Status,
		&i.Pinned,
		&i.Progress,
		&i.RelatedProject,
		&i.PublishedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
