// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeMediaAssetUpload = `-- name: CompleteMediaAssetUpload :one
UPDATE media_assets
SET status = 'queued',
    byte_size = $1,
    mime_type = $2,
    metadata = metadata || $3::JSONB,
    error_code = NULL,
    error_message = NULL,
    updated_at = NOW()
WHERE id = $4
  AND status = 'uploading'
RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
`

type CompleteMediaAssetUploadParams struct {
	ByteSize int64       `db:"byte_size" json:"byte_size"`
	MimeType string      `db:"mime_type" json:"mime_type"`
	Metadata []byte      `db:"metadata" json:"metadata"`
	AssetID  pgtype.UUID `db:"asset_id" json:"asset_id"`
}

// CompleteMediaAssetUpload
//
//	UPDATE media_assets
//	SET status = 'queued',
//	    byte_size = $1,
//	    mime_type = $2,
//	    metadata = metadata || $3::JSONB,
//	    error_code = NULL,
//	    error_message = NULL,
//	    updated_at = NOW()
//	WHERE id = $4
//	  AND status = 'uploading'
//	RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
func (q *Queries) CompleteMediaAssetUpload(ctx context.Context, arg CompleteMediaAssetUploadParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, completeMediaAssetUpload,
		arg.ByteSize,
		arg.MimeType,
		arg.Metadata,
		arg.AssetID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.PageCount,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalPurgedAt,
	)
	return i, err
}

const countActivityAssetLinks = `-- name: CountActivityAssetLinks :one
SELECT COUNT(*) FROM activity_assets WHERE asset_id = $1
`

// CountActivityAssetLinks
//
//	SELECT COUNT(*) FROM activity_assets WHERE asset_id = $1
func (q *Queries) CountActivityAssetLinks(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityAssetLinks, assetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (
    id,
    kind,
    status,
    original_filename,
    original_object_key,
    mime_type,
    byte_size,
    metadata
) VALUES (
    $1,
    $2,
    'uploading',
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
`

type CreateMediaAssetParams struct {
	AssetID           pgtype.UUID `db:"asset_id" json:"asset_id"`
	Kind              MediaKind   `db:"kind" json:"kind"`
	OriginalFilename  string      `db:"original_filename" json:"original_filename"`
	OriginalObjectKey string      `db:"original_object_key" json:"original_object_key"`
	MimeType          string      `db:"mime_type" json:"mime_type"`
	ByteSize          int64       `db:"byte_size" json:"byte_size"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
}

// CreateMediaAsset
//
//	INSERT INTO media_assets (
//	    id,
//	    kind,
//	    status,
//	    original_filename,
//	    original_object_key,
//	    mime_type,
//	    byte_size,
//	    metadata
//	) VALUES (
//	    $1,
//	    $2,
//	    'uploading',
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7
//	)
//	RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, createMediaAsset,
		arg.AssetID,
		arg.Kind,
		arg.OriginalFilename,
		arg.OriginalObjectKey,
		arg.MimeType,
		arg.ByteSize,
		arg.Metadata,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.PageCount,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalPurgedAt,
	)
	return i, err
}

const createProcessingJob = `-- name: CreateProcessingJob :exec
INSERT INTO processing_jobs (
    asset_id,
    job_type,
    idempotency_key
) VALUES (
    $1,
    $2,
    $3
)
ON CONFLICT (idempotency_key) DO NOTHING
`

type CreateProcessingJobParams struct {
	AssetID        pgtype.UUID       `db:"asset_id" json:"asset_id"`
	JobType        ProcessingJobType `db:"job_type" json:"job_type"`
	IdempotencyKey string            `db:"idempotency_key" json:"idempotency_key"`
}

// CreateProcessingJob
//
//	INSERT INTO processing_jobs (
//	    asset_id,
//	    job_type,
//	    idempotency_key
//	) VALUES (
//	    $1,
//	    $2,
//	    $3
//	)
//	ON CONFLICT (idempotency_key) DO NOTHING
func (q *Queries) CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) error {
	_, err := q.db.Exec(ctx, createProcessingJob, arg.AssetID, arg.JobType, arg.IdempotencyKey)
	return err
}

const deleteUnlinkedMediaAsset = `-- name: DeleteUnlinkedMediaAsset :execrows
DELETE FROM media_assets AS asset
WHERE asset.id = $1
  AND NOT EXISTS (
      SELECT 1
      FROM activity_assets AS link
      WHERE link.asset_id = asset.id
  )
`

// DeleteUnlinkedMediaAsset
//
//	DELETE FROM media_assets AS asset
//	WHERE asset.id = $1
//	  AND NOT EXISTS (
//	      SELECT 1
//	      FROM activity_assets AS link
//	      WHERE link.asset_id = asset.id
//	  )
func (q *Queries) DeleteUnlinkedMediaAsset(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnlinkedMediaAsset, assetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssetVariantObject = `-- name: GetAssetVariantObject :one
SELECT object_key
FROM asset_variants
WHERE asset_id = $1
  AND variant_key = $2
`

type GetAssetVariantObjectParams struct {
	AssetID    pgtype.UUID `db:"asset_id" json:"asset_id"`
	VariantKey string      `db:"variant_key" json:"variant_key"`
}

// GetAssetVariantObject
//
//	SELECT object_key
//	FROM asset_variants
//	WHERE asset_id = $1
//	  AND variant_key = $2
func (q *Queries) GetAssetVariantObject(ctx context.Context, arg GetAssetVariantObjectParams) (string, error) {
	row := q.db.QueryRow(ctx, getAssetVariantObject, arg.AssetID, arg.VariantKey)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const getAuthorizedAssetObject = `-- name: GetAuthorizedAssetObject :one
SELECT
    asset.original_object_key,
    asset.delivery_object_key,
    asset.kind,
    asset.status,
    EXISTS (
        SELECT 1
        FROM activity_assets AS link
        JOIN activities AS activity ON activity.id = link.activity_id
        WHERE link.asset_id = asset.id
          AND activity.status = 'published'
    ) AS publicly_linked
FROM media_assets AS asset
WHERE asset.id = $1
`

type GetAuthorizedAssetObjectRow struct {
	OriginalObjectKey string      `db:"original_object_key" json:"original_object_key"`
	DeliveryObjectKey *string     `db:"delivery_object_key" json:"delivery_object_key"`
	Kind              MediaKind   `db:"kind" json:"kind"`
	Status            AssetStatus `db:"status" json:"status"`
	PubliclyLinked    bool        `db:"publicly_linked" json:"publicly_linked"`
}

// GetAuthorizedAssetObject
//
//	SELECT
//	    asset.original_object_key,
//	    asset.delivery_object_key,
//	    asset.kind,
//	    asset.status,
//	    EXISTS (
//	        SELECT 1
//	        FROM activity_assets AS link
//	        JOIN activities AS activity ON activity.id = link.activity_id
//	        WHERE link.asset_id = asset.id
//	          AND activity.status = 'published'
//	    ) AS publicly_linked
//	FROM media_assets AS asset
//	WHERE asset.id = $1
func (q *Queries) GetAuthorizedAssetObject(ctx context.Context, assetID pgtype.UUID) (GetAuthorizedAssetObjectRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedAssetObject, assetID)
	var i GetAuthorizedAssetObjectRow
	err := row.Scan(
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.Kind,
		&i.Status,
		&i.PubliclyLinked,
	)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at FROM media_assets WHERE id = $1
`

// GetMediaAsset
//
//	SELECT id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at FROM media_assets WHERE id = $1
func (q *Queries) GetMediaAsset(ctx context.Context, assetID pgtype.UUID) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, getMediaAsset, assetID)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.PageCount,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalPurgedAt,
	)
	return i, err
}

const listAssetObjectKeys = `-- name: ListAssetObjectKeys :many
SELECT object_key
FROM asset_variants
WHERE asset_id = $1
UNION
SELECT delivery_object_key
FROM media_assets
WHERE id = $1
  AND delivery_object_key IS NOT NULL
`

// ListAssetObjectKeys
//
//	SELECT object_key
//	FROM asset_variants
//	WHERE asset_id = $1
//	UNION
//	SELECT delivery_object_key
//	FROM media_assets
//	WHERE id = $1
//	  AND delivery_object_key IS NOT NULL
func (q *Queries) ListAssetObjectKeys(ctx context.Context, assetID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAssetObjectKeys, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var object_key string
		if err := rows.Scan(&object_key); err != nil {
			return nil, err
		}
		items = append(items, object_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurgeableAssetOriginals = `-- name: ListPurgeableAssetOriginals :many
SELECT
    id,
    kind,
    original_object_key
FROM media_assets
WHERE status = 'ready'
  -- Document originals stay: they are what the download button serves.
  AND kind <> 'document'
  AND original_purged_at IS NULL
  AND ready_at IS NOT NULL
  AND ready_at < $1
  -- Never sweep an asset that is still delivered from its own upload.
  AND delivery_object_key IS NOT NULL
  AND delivery_object_key <> original_object_key
ORDER BY ready_at
LIMIT $2
`

type ListPurgeableAssetOriginalsParams struct {
	PurgeBefore pgtype.Timestamptz `db:"purge_before" json:"purge_before"`
	RowLimit    int32              `db:"row_limit" json:"row_limit"`
}

type ListPurgeableAssetOriginalsRow struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	Kind              MediaKind   `db:"kind" json:"kind"`
	OriginalObjectKey string      `db:"original_object_key" json:"original_object_key"`
}

// ListPurgeableAssetOriginals
//
//	SELECT
//	    id,
//	    kind,
//	    original_object_key
//	FROM media_assets
//	WHERE status = 'ready'
//	  -- Document originals stay: they are what the download button serves.
//	  AND kind <> 'document'
//	  AND original_purged_at IS NULL
//	  AND ready_at IS NOT NULL
//	  AND ready_at < $1
//	  -- Never sweep an asset that is still delivered from its own upload.
//	  AND delivery_object_key IS NOT NULL
//	  AND delivery_object_key <> original_object_key
//	ORDER BY ready_at
//	LIMIT $2
func (q *Queries) ListPurgeableAssetOriginals(ctx context.Context, arg ListPurgeableAssetOriginalsParams) ([]ListPurgeableAssetOriginalsRow, error) {
	rows, err := q.db.Query(ctx, listPurgeableAssetOriginals, arg.PurgeBefore, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurgeableAssetOriginalsRow{}
	for rows.Next() {
		var i ListPurgeableAssetOriginalsRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.OriginalObjectKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssetOriginalPurged = `-- name: MarkAssetOriginalPurged :execrows
UPDATE media_assets
SET original_purged_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND original_purged_at IS NULL
`

// MarkAssetOriginalPurged
//
//	UPDATE media_assets
//	SET original_purged_at = NOW(),
//	    updated_at = NOW()
//	WHERE id = $1
//	  AND original_purged_at IS NULL
func (q *Queries) MarkAssetOriginalPurged(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAssetOriginalPurged, assetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
