// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO auth_sessions (
    id,
    admin_user_id,
    current_refresh_token_hash,
    current_access_jti,
    idle_expires_at,
    absolute_expires_at,
    user_agent,
    ip_address
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
`

type CreateAuthSessionParams struct {
	SessionID         pgtype.UUID        `db:"session_id" json:"session_id"`
	AdminUserID       pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	RefreshTokenHash  []byte             `db:"refresh_token_hash" json:"refresh_token_hash"`
	AccessJti         pgtype.UUID        `db:"access_jti" json:"access_jti"`
	IdleExpiresAt     pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	UserAgent         string             `db:"user_agent" json:"user_agent"`
	IpAddress         *netip.Addr        `db:"ip_address" json:"ip_address"`
}

// CreateAuthSession
//
//	INSERT INTO auth_sessions (
//	    id,
//	    admin_user_id,
//	    current_refresh_token_hash,
//	    current_access_jti,
//	    idle_expires_at,
//	    absolute_expires_at,
//	    user_agent,
//	    ip_address
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8
//	)
//	RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.SessionID,
		arg.AdminUserID,
		arg.RefreshTokenHash,
		arg.AccessJti,
		arg.IdleExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CurrentRefreshTokenHash,
		&i.CurrentAccessJti,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastRotatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSessionByConsumedRefreshHash = `-- name: FindSessionByConsumedRefreshHash :one
SELECT session_id
FROM auth_consumed_refresh_tokens
WHERE token_hash = $1
`

// FindSessionByConsumedRefreshHash
//
//	SELECT session_id
//	FROM auth_consumed_refresh_tokens
//	WHERE token_hash = $1
func (q *Queries) FindSessionByConsumedRefreshHash(ctx context.Context, tokenHash []byte) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findSessionByConsumedRefreshHash, tokenHash)
	var session_id pgtype.UUID
	err := row.Scan(&session_id)
	return session_id, err
}

const getActiveAdminUserByEmail = `-- name: GetActiveAdminUserByEmail :one
SELECT id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
FROM admin_users
WHERE email = LOWER(BTRIM($1))
  AND disabled_at IS NULL
`

// GetActiveAdminUserByEmail
//
//	SELECT id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
//	FROM admin_users
//	WHERE email = LOWER(BTRIM($1))
//	  AND disabled_at IS NULL
func (q *Queries) GetActiveAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getActiveAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionPrincipal = `-- name: GetActiveSessionPrincipal :one
SELECT
    s.id AS session_id,
    s.current_access_jti,
    s.idle_expires_at,
    s.absolute_expires_at,
    u.id AS admin_user_id,
    u.email,
    u.display_name
FROM auth_sessions AS s
JOIN admin_users AS u ON u.id = s.admin_user_id
WHERE s.id = $1
  AND s.current_access_jti = $2
  AND s.revoked_at IS NULL
  AND s.idle_expires_at > NOW()
  AND s.absolute_expires_at > NOW()
  AND u.disabled_at IS NULL
`

type GetActiveSessionPrincipalParams struct {
	SessionID pgtype.UUID `db:"session_id" json:"session_id"`
	AccessJti pgtype.UUID `db:"access_jti" json:"access_jti"`
}

type GetActiveSessionPrincipalRow struct {
	SessionID         pgtype.UUID        `db:"session_id" json:"session_id"`
	CurrentAccessJti  pgtype.UUID        `db:"current_access_jti" json:"current_access_jti"`
	IdleExpiresAt     pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	AdminUserID       pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	Email             string             `db:"email" json:"email"`
	DisplayName       string             `db:"display_name" json:"display_name"`
}

// GetActiveSessionPrincipal
//
//	SELECT
//	    s.id AS session_id,
//	    s.current_access_jti,
//	    s.idle_expires_at,
//	    s.absolute_expires_at,
//	    u.id AS admin_user_id,
//	    u.email,
//	    u.display_name
//	FROM auth_sessions AS s
//	JOIN admin_users AS u ON u.id = s.admin_user_id
//	WHERE s.id = $1
//	  AND s.current_access_jti = $2
//	  AND s.revoked_at IS NULL
//	  AND s.idle_expires_at > NOW()
//	  AND s.absolute_expires_at > NOW()
//	  AND u.disabled_at IS NULL
func (q *Queries) GetActiveSessionPrincipal(ctx context.Context, arg GetActiveSessionPrincipalParams) (GetActiveSessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionPrincipal, arg.SessionID, arg.AccessJti)
	var i GetActiveSessionPrincipalRow
	err := row.Scan(
		&i.SessionID,
		&i.CurrentAccessJti,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.AdminUserID,
		&i.Email,
		&i.DisplayName,
	)
	return i, err
}

const lockAuthSessionByRefreshHash = `-- name: LockAuthSessionByRefreshHash :one
SELECT
    s.id, s.admin_user_id, s.current_refresh_token_hash, s.current_access_jti, s.idle_expires_at, s.absolute_expires_at, s.last_rotated_at, s.user_agent, s.ip_address, s.revoked_at, s.revoke_reason, s.created_at, s.updated_at,
    u.email,
    u.display_name,
    u.disabled_at
FROM auth_sessions AS s
JOIN admin_users AS u ON u.id = s.admin_user_id
WHERE s.current_refresh_token_hash = $1
FOR UPDATE OF s
`

type LockAuthSessionByRefreshHashRow struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	AdminUserID             pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	CurrentRefreshTokenHash []byte             `db:"current_refresh_token_hash" json:"current_refresh_token_hash"`
	CurrentAccessJti        pgtype.UUID        `db:"current_access_jti" json:"current_access_jti"`
	IdleExpiresAt           pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt       pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	LastRotatedAt           pgtype.Timestamptz `db:"last_rotated_at" json:"last_rotated_at"`
	UserAgent               string             `db:"user_agent" json:"user_agent"`
	IpAddress               *netip.Addr        `db:"ip_address" json:"ip_address"`
	RevokedAt               pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason            *string            `db:"revoke_reason" json:"revoke_reason"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Email                   string             `db:"email" json:"email"`
	DisplayName             string             `db:"display_name" json:"display_name"`
	DisabledAt              pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
}

// LockAuthSessionByRefreshHash
//
//	SELECT
//	    s.id, s.admin_user_id, s.current_refresh_token_hash, s.current_access_jti, s.idle_expires_at, s.absolute_expires_at, s.last_rotated_at, s.user_agent, s.ip_address, s.revoked_at, s.revoke_reason, s.created_at, s.updated_at,
//	    u.email,
//	    u.display_name,
//	    u.disabled_at
//	FROM auth_sessions AS s
//	JOIN admin_users AS u ON u.id = s.admin_user_id
//	WHERE s.current_refresh_token_hash = $1
//	FOR UPDATE OF s
func (q *Queries) LockAuthSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (LockAuthSessionByRefreshHashRow, error) {
	row := q.db.QueryRow(ctx, lockAuthSessionByRefreshHash, refreshTokenHash)
	var i LockAuthSessionByRefreshHashRow
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CurrentRefreshTokenHash,
		&i.CurrentAccessJti,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastRotatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.DisplayName,
		&i.DisabledAt,
	)
	return i, err
}

const markAdminLogin = `-- name: MarkAdminLogin :exec
UPDATE admin_users
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

// MarkAdminLogin
//
//	UPDATE admin_users
//	SET last_login_at = NOW(),
//	    updated_at = NOW()
//	WHERE id = $1
func (q *Queries) MarkAdminLogin(ctx context.Context, adminUserID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAdminLogin, adminUserID)
	return err
}

const recordConsumedRefreshToken = `-- name: RecordConsumedRefreshToken :exec
INSERT INTO auth_consumed_refresh_tokens (
    token_hash,
    session_id
) VALUES (
    $1,
    $2
)
`

type RecordConsumedRefreshTokenParams struct {
	TokenHash []byte      `db:"token_hash" json:"token_hash"`
	SessionID pgtype.UUID `db:"session_id" json:"session_id"`
}

// RecordConsumedRefreshToken
//
//	INSERT INTO auth_consumed_refresh_tokens (
//	    token_hash,
//	    session_id
//	) VALUES (
//	    $1,
//	    $2
//	)
func (q *Queries) RecordConsumedRefreshToken(ctx context.Context, arg RecordConsumedRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, recordConsumedRefreshToken, arg.TokenHash, arg.SessionID)
	return err
}

const revokeAuthSession = `-- name: RevokeAuthSession :execrows
UPDATE auth_sessions
SET revoked_at = COALESCE(revoked_at, NOW()),
    revoke_reason = COALESCE(revoke_reason, $1),
    updated_at = NOW()
WHERE id = $2
  AND revoked_at IS NULL
`

type RevokeAuthSessionParams struct {
	Reason    *string     `db:"reason" json:"reason"`
	SessionID pgtype.UUID `db:"session_id" json:"session_id"`
}

// RevokeAuthSession
//
//	UPDATE auth_sessions
//	SET revoked_at = COALESCE(revoked_at, NOW()),
//	    revoke_reason = COALESCE(revoke_reason, $1),
//	    updated_at = NOW()
//	WHERE id = $2
//	  AND revoked_at IS NULL
func (q *Queries) RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAuthSession, arg.Reason, arg.SessionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateAuthSession = `-- name: RotateAuthSession :one
UPDATE auth_sessions
SET current_refresh_token_hash = $1,
    current_access_jti = $2,
    idle_expires_at = $3,
    last_rotated_at = NOW(),
    user_agent = $4,
    ip_address = $5,
    updated_at = NOW()
WHERE id = $6
  AND revoked_at IS NULL
RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
`

type RotateAuthSessionParams struct {
	RefreshTokenHash []byte             `db:"refresh_token_hash" json:"refresh_token_hash"`
	AccessJti        pgtype.UUID        `db:"access_jti" json:"access_jti"`
	IdleExpiresAt    pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	UserAgent        string             `db:"user_agent" json:"user_agent"`
	IpAddress        *netip.Addr        `db:"ip_address" json:"ip_address"`
	SessionID        pgtype.UUID        `db:"session_id" json:"session_id"`
}

// RotateAuthSession
//
//	UPDATE auth_sessions
//	SET current_refresh_token_hash = $1,
//	    current_access_jti = $2,
//	    idle_expires_at = $3,
//	    last_rotated_at = NOW(),
//	    user_agent = $4,
//	    ip_address = $5,
//	    updated_at = NOW()
//	WHERE id = $6
//	  AND revoked_at IS NULL
//	RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRow(ctx, rotateAuthSession,
		arg.RefreshTokenHash,
		arg.AccessJti,
		arg.IdleExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.SessionID,
	)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CurrentRefreshTokenHash,
		&i.CurrentAccessJti,
		&i.IdleExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.LastRotatedAt,
		&i.UserAgent,
		&i.IpAddress,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAdminUser = `-- name: UpsertAdminUser :one
INSERT INTO admin_users (
    email,
    display_name,
    password_hash
) VALUES (
    LOWER(BTRIM($1)),
    BTRIM($2),
    $3
)
ON CONFLICT (email) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    password_hash = EXCLUDED.password_hash,
    disabled_at = NULL,
    updated_at = NOW()
RETURNING id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
`

type UpsertAdminUserParams struct {
	Email        string `db:"email" json:"email"`
	DisplayName  string `db:"display_name" json:"display_name"`
	PasswordHash string `db:"password_hash" json:"password_hash"`
}

// UpsertAdminUser
//
//	INSERT INTO admin_users (
//	    email,
//	    display_name,
//	    password_hash
//	) VALUES (
//	    LOWER(BTRIM($1)),
//	    BTRIM($2),
//	    $3
//	)
//	ON CONFLICT (email) DO UPDATE SET
//	    display_name = EXCLUDED.display_name,
//	    password_hash = EXCLUDED.password_hash,
//	    disabled_at = NULL,
//	    updated_at = NOW()
//	RETURNING id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
func (q *Queries) UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, upsertAdminUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
