// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: engagement.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addActivityLike = `-- name: AddActivityLike :exec
INSERT INTO activity_likes (activity_id, visitor_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddActivityLikeParams struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	VisitorID  pgtype.UUID `db:"visitor_id" json:"visitor_id"`
}

// AddActivityLike
//
//	INSERT INTO activity_likes (activity_id, visitor_id)
//	VALUES ($1, $2)
//	ON CONFLICT DO NOTHING
func (q *Queries) AddActivityLike(ctx context.Context, arg AddActivityLikeParams) error {
	_, err := q.db.Exec(ctx, addActivityLike, arg.ActivityID, arg.VisitorID)
	return err
}

const countActivityLikes = `-- name: CountActivityLikes :one
SELECT COUNT(*) FROM activity_likes WHERE activity_id = $1
`

// CountActivityLikes
//
//	SELECT COUNT(*) FROM activity_likes WHERE activity_id = $1
func (q *Queries) CountActivityLikes(ctx context.Context, activityID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLikes, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminComments = `-- name: CountAdminComments :one
SELECT COUNT(*)
FROM activity_comments AS comment
WHERE (
    $1::UUID IS NULL
    OR comment.activity_id = $1
)
  AND (
    $2::comment_status IS NULL
    OR comment.status = $2::comment_status
  )
`

type CountAdminCommentsParams struct {
	ActivityID    pgtype.UUID    `db:"activity_id" json:"activity_id"`
	CommentStatus *CommentStatus `db:"comment_status" json:"comment_status"`
}

// CountAdminComments
//
//	SELECT COUNT(*)
//	FROM activity_comments AS comment
//	WHERE (
//	    $1::UUID IS NULL
//	    OR comment.activity_id = $1
//	)
//	  AND (
//	    $2::comment_status IS NULL
//	    OR comment.status = $2::comment_status
//	  )
func (q *Queries) CountAdminComments(ctx context.Context, arg CountAdminCommentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminComments, arg.ActivityID, arg.CommentStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVisibleActivityComments = `-- name: CountVisibleActivityComments :one
SELECT COUNT(*)
FROM activity_comments
WHERE activity_id = $1
  AND status = 'visible'
`

// CountVisibleActivityComments
//
//	SELECT COUNT(*)
//	FROM activity_comments
//	WHERE activity_id = $1
//	  AND status = 'visible'
func (q *Queries) CountVisibleActivityComments(ctx context.Context, activityID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countVisibleActivityComments, activityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityComment = `-- name: CreateActivityComment :one
INSERT INTO activity_comments (
    activity_id,
    author_name,
    body
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, activity_id, author_name, body, status, created_at, updated_at
`

type CreateActivityCommentParams struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	AuthorName string      `db:"author_name" json:"author_name"`
	Body       string      `db:"body" json:"body"`
}

// CreateActivityComment
//
//	INSERT INTO activity_comments (
//	    activity_id,
//	    author_name,
//	    body
//	) VALUES (
//	    $1,
//	    $2,
//	    $3
//	)
//	RETURNING id, activity_id, author_name, body, status, created_at, updated_at
func (q *Queries) CreateActivityComment(ctx context.Context, arg CreateActivityCommentParams) (ActivityComment, error) {
	row := q.db.QueryRow(ctx, createActivityComment, arg.ActivityID, arg.AuthorName, arg.Body)
	var i ActivityComment
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.AuthorName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :execrows
DELETE FROM activity_comments WHERE id = $1
`

// DeleteComment
//
//	DELETE FROM activity_comments WHERE id = $1
func (q *Queries) DeleteComment(ctx context.Context, commentID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteComment, commentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublishedActivityIDBySlug = `-- name: GetPublishedActivityIDBySlug :one
SELECT id
FROM activities
WHERE slug = $1
  AND status = 'published'
`

// GetPublishedActivityIDBySlug
//
//	SELECT id
//	FROM activities
//	WHERE slug = $1
//	  AND status = 'published'
func (q *Queries) GetPublishedActivityIDBySlug(ctx context.Context, slug *string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPublishedActivityIDBySlug, slug)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const hasActivityLike = `-- name: HasActivityLike :one
SELECT EXISTS (
    SELECT 1
    FROM activity_likes
    WHERE activity_id = $1
      AND visitor_id = $2
)
`

type HasActivityLikeParams struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	VisitorID  pgtype.UUID `db:"visitor_id" json:"visitor_id"`
}

// HasActivityLike
//
//	SELECT EXISTS (
//	    SELECT 1
//	    FROM activity_likes
//	    WHERE activity_id = $1
//	      AND visitor_id = $2
//	)
func (q *Queries) HasActivityLike(ctx context.Context, arg HasActivityLikeParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActivityLike, arg.ActivityID, arg.VisitorID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAdminComments = `-- name: ListAdminComments :many
SELECT comment.id, comment.activity_id, comment.author_name, comment.body, comment.status, comment.created_at, comment.updated_at, activity.slug AS activity_slug
FROM activity_comments AS comment
JOIN activities AS activity ON activity.id = comment.activity_id
WHERE (
    $1::UUID IS NULL
    OR comment.activity_id = $1
)
  AND (
    $2::comment_status IS NULL
    OR comment.status = $2::comment_status
  )
ORDER BY comment.created_at DESC, comment.id DESC
LIMIT $4
OFFSET $3
`

type ListAdminCommentsParams struct {
	ActivityID    pgtype.UUID    `db:"activity_id" json:"activity_id"`
	CommentStatus *CommentStatus `db:"comment_status" json:"comment_status"`
	PageOffset    int32          `db:"page_offset" json:"page_offset"`
	PageLimit     int32          `db:"page_limit" json:"page_limit"`
}

type ListAdminCommentsRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	ActivityID   pgtype.UUID        `db:"activity_id" json:"activity_id"`
	AuthorName   string             `db:"author_name" json:"author_name"`
	Body         string             `db:"body" json:"body"`
	Status       CommentStatus      `db:"status" json:"status"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ActivitySlug *string            `db:"activity_slug" json:"activity_slug"`
}

// ListAdminComments
//
//	SELECT comment.id, comment.activity_id, comment.author_name, comment.body, comment.status, comment.created_at, comment.updated_at, activity.slug AS activity_slug
//	FROM activity_comments AS comment
//	JOIN activities AS activity ON activity.id = comment.activity_id
//	WHERE (
//	    $1::UUID IS NULL
//	    OR comment.activity_id = $1
//	)
//	  AND (
//	    $2::comment_status IS NULL
//	    OR comment.status = $2::comment_status
//	  )
//	ORDER BY comment.created_at DESC, comment.id DESC
//	LIMIT $4
//	OFFSET $3
func (q *Queries) ListAdminComments(ctx context.Context, arg ListAdminCommentsParams) ([]ListAdminCommentsRow, error) {
	rows, err := q.db.Query(ctx, listAdminComments,
		arg.ActivityID,
		arg.CommentStatus,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminCommentsRow{}
	for rows.Next() {
		var i ListAdminCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.AuthorName,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivitySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleActivityComments = `-- name: ListVisibleActivityComments :many
SELECT id, activity_id, author_name, body, status, created_at, updated_at
FROM activity_comments
WHERE activity_id = $1
  AND status = 'visible'
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2
`

type ListVisibleActivityCommentsParams struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	PageOffset int32       `db:"page_offset" json:"page_offset"`
	PageLimit  int32       `db:"page_limit" json:"page_limit"`
}

// ListVisibleActivityComments
//
//	SELECT id, activity_id, author_name, body, status, created_at, updated_at
//	FROM activity_comments
//	WHERE activity_id = $1
//	  AND status = 'visible'
//	ORDER BY created_at DESC, id DESC
//	LIMIT $3
//	OFFSET $2
func (q *Queries) ListVisibleActivityComments(ctx context.Context, arg ListVisibleActivityCommentsParams) ([]ActivityComment, error) {
	rows, err := q.db.Query(ctx, listVisibleActivityComments, arg.ActivityID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityComment{}
	for rows.Next() {
		var i ActivityComment
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.AuthorName,
			&i.Body,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeActivityLike = `-- name: RemoveActivityLike :exec
DELETE FROM activity_likes
WHERE activity_id = $1
  AND visitor_id = $2
`

type RemoveActivityLikeParams struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	VisitorID  pgtype.UUID `db:"visitor_id" json:"visitor_id"`
}

// RemoveActivityLike
//
//	DELETE FROM activity_likes
//	WHERE activity_id = $1
//	  AND visitor_id = $2
func (q *Queries) RemoveActivityLike(ctx context.Context, arg RemoveActivityLikeParams) error {
	_, err := q.db.Exec(ctx, removeActivityLike, arg.ActivityID, arg.VisitorID)
	return err
}

const updateCommentStatus = `-- name: UpdateCommentStatus :one
UPDATE activity_comments
SET status = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, activity_id, author_name, body, status, created_at, updated_at
`

type UpdateCommentStatusParams struct {
	CommentStatus CommentStatus `db:"comment_status" json:"comment_status"`
	CommentID     pgtype.UUID   `db:"comment_id" json:"comment_id"`
}

// UpdateCommentStatus
//
//	UPDATE activity_comments
//	SET status = $1,
//	    updated_at = NOW()
//	WHERE id = $2
//	RETURNING id, activity_id, author_name, body, status, created_at, updated_at
func (q *Queries) UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) (ActivityComment, error) {
	row := q.db.QueryRow(ctx, updateCommentStatus, arg.CommentStatus, arg.CommentID)
	var i ActivityComment
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.AuthorName,
		&i.Body,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
