// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityAssetRole string

const (
	ActivityAssetRoleCover      ActivityAssetRole = "cover"
	ActivityAssetRoleGallery    ActivityAssetRole = "gallery"
	ActivityAssetRoleAttachment ActivityAssetRole = "attachment"
)

func (e *ActivityAssetRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityAssetRole(s)
	case string:
		*e = ActivityAssetRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityAssetRole: %T", src)
	}
	return nil
}

type NullActivityAssetRole struct {
	ActivityAssetRole ActivityAssetRole `json:"activity_asset_role"`
	Valid             bool              `json:"valid"` // Valid is true if ActivityAssetRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityAssetRole) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityAssetRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityAssetRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityAssetRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityAssetRole), nil
}

type ActivityCategory string

const (
	ActivityCategoryProject     ActivityCategory = "project"
	ActivityCategoryLearning    ActivityCategory = "learning"
	ActivityCategoryDaily       ActivityCategory = "daily"
	ActivityCategoryAchievement ActivityCategory = "achievement"
)

func (e *ActivityCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityCategory(s)
	case string:
		*e = ActivityCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityCategory: %T", src)
	}
	return nil
}

type NullActivityCategory struct {
	ActivityCategory ActivityCategory `json:"activity_category"`
	Valid            bool             `json:"valid"` // Valid is true if ActivityCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityCategory), nil
}

type ActivityProgress string

const (
	ActivityProgressLearning  ActivityProgress = "learning"
	ActivityProgressShipped   ActivityProgress = "shipped"
	ActivityProgressExploring ActivityProgress = "exploring"
)

func (e *ActivityProgress) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityProgress(s)
	case string:
		*e = ActivityProgress(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityProgress: %T", src)
	}
	return nil
}

type NullActivityProgress struct {
	ActivityProgress ActivityProgress `json:"activity_progress"`
	Valid            bool             `json:"valid"` // Valid is true if ActivityProgress is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityProgress) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityProgress, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityProgress.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityProgress) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityProgress), nil
}

type ActivityStatus string

const (
	ActivityStatusPublished ActivityStatus = "published"
	ActivityStatusDraft     ActivityStatus = "draft"
	ActivityStatusHidden    ActivityStatus = "hidden"
)

func (e *ActivityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityStatus(s)
	case string:
		*e = ActivityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityStatus: %T", src)
	}
	return nil
}

type NullActivityStatus struct {
	ActivityStatus ActivityStatus `json:"activity_status"`
	Valid          bool           `json:"valid"` // Valid is true if ActivityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityStatus), nil
}

type AssetStatus string

const (
	AssetStatusQueued     AssetStatus = "queued"
	AssetStatusUploading  AssetStatus = "uploading"
	AssetStatusProcessing AssetStatus = "processing"
	AssetStatusReady      AssetStatus = "ready"
	AssetStatusFailed     AssetStatus = "failed"
)

func (e *AssetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetStatus(s)
	case string:
		*e = AssetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetStatus: %T", src)
	}
	return nil
}

type NullAssetStatus struct {
	AssetStatus AssetStatus `json:"asset_status"`
	Valid       bool        `json:"valid"` // Valid is true if AssetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetStatus), nil
}

type CommentStatus string

const (
	CommentStatusVisible CommentStatus = "visible"
	CommentStatusHidden  CommentStatus = "hidden"
)

func (e *CommentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CommentStatus(s)
	case string:
		*e = CommentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CommentStatus: %T", src)
	}
	return nil
}

type NullCommentStatus struct {
	CommentStatus CommentStatus `json:"comment_status"`
	Valid         bool          `json:"valid"` // Valid is true if CommentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCommentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CommentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CommentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCommentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CommentStatus), nil
}

type MediaKind string

const (
	MediaKindImage    MediaKind = "image"
	MediaKindVideo    MediaKind = "video"
	MediaKindDocument MediaKind = "document"
)

func (e *MediaKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaKind(s)
	case string:
		*e = MediaKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaKind: %T", src)
	}
	return nil
}

type NullMediaKind struct {
	MediaKind MediaKind `json:"media_kind"`
	Valid     bool      `json:"valid"` // Valid is true if MediaKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaKind) Scan(value interface{}) error {
	if value == nil {
		ns.MediaKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaKind), nil
}

type ProcessingJobStatus string

const (
	ProcessingJobStatusQueued     ProcessingJobStatus = "queued"
	ProcessingJobStatusProcessing ProcessingJobStatus = "processing"
	ProcessingJobStatusCompleted  ProcessingJobStatus = "completed"
	ProcessingJobStatusFailed     ProcessingJobStatus = "failed"
)

func (e *ProcessingJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingJobStatus(s)
	case string:
		*e = ProcessingJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingJobStatus: %T", src)
	}
	return nil
}

type NullProcessingJobStatus struct {
	ProcessingJobStatus ProcessingJobStatus `json:"processing_job_status"`
	Valid               bool                `json:"valid"` // Valid is true if ProcessingJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingJobStatus), nil
}

type ProcessingJobType string

const (
	ProcessingJobTypeImage    ProcessingJobType = "image"
	ProcessingJobTypeVideo    ProcessingJobType = "video"
	ProcessingJobTypeDocument ProcessingJobType = "document"
)

func (e *ProcessingJobType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProcessingJobType(s)
	case string:
		*e = ProcessingJobType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProcessingJobType: %T", src)
	}
	return nil
}

type NullProcessingJobType struct {
	ProcessingJobType ProcessingJobType `json:"processing_job_type"`
	Valid             bool              `json:"valid"` // Valid is true if ProcessingJobType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProcessingJobType) Scan(value interface{}) error {
	if value == nil {
		ns.ProcessingJobType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProcessingJobType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProcessingJobType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProcessingJobType), nil
}

type Activity struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Slug           *string            `db:"slug" json:"slug"`
	TitleID        string             `db:"title_id" json:"title_id"`
	TitleEn        string             `db:"title_en" json:"title_en"`
	CaptionID      string             `db:"caption_id" json:"caption_id"`
	CaptionEn      string             `db:"caption_en" json:"caption_en"`
	BodyID         string             `db:"body_id" json:"body_id"`
	BodyEn         string             `db:"body_en" json:"body_en"`
	Category       ActivityCategory   `db:"category" json:"category"`
	ActivityDate   pgtype.Date        `db:"activity_date" json:"activity_date"`
	Status         ActivityStatus     `db:"status" json:"status"`
	Pinned         bool               `db:"pinned" json:"pinned"`
	Progress       *ActivityProgress  `db:"progress" json:"progress"`
	RelatedProject *string            `db:"related_project" json:"related_project"`
	PublishedAt    pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Version        int64              `db:"version" json:"version"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ActivityAsset struct {
	ActivityID pgtype.UUID        `db:"activity_id" json:"activity_id"`
	AssetID    pgtype.UUID        `db:"asset_id" json:"asset_id"`
	Role       ActivityAssetRole  `db:"role" json:"role"`
	Position   int32              `db:"position" json:"position"`
	AltText    string             `db:"alt_text" json:"alt_text"`
	CaptionID  string             `db:"caption_id" json:"caption_id"`
	CaptionEn  string             `db:"caption_en" json:"caption_en"`
	LabelID    string             `db:"label_id" json:"label_id"`
	LabelEn    string             `db:"label_en" json:"label_en"`
	Crop       []byte             `db:"crop" json:"crop"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ActivityComment struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	ActivityID pgtype.UUID        `db:"activity_id" json:"activity_id"`
	AuthorName string             `db:"author_name" json:"author_name"`
	Body       string             `db:"body" json:"body"`
	Status     CommentStatus      `db:"status" json:"status"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ActivityLike struct {
	ActivityID pgtype.UUID        `db:"activity_id" json:"activity_id"`
	VisitorID  pgtype.UUID        `db:"visitor_id" json:"visitor_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ActivitySlugRedirect struct {
	Slug       string             `db:"slug" json:"slug"`
	ActivityID pgtype.UUID        `db:"activity_id" json:"activity_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type ActivityTag struct {
	ActivityID pgtype.UUID `db:"activity_id" json:"activity_id"`
	Position   int32       `db:"position" json:"position"`
	Value      string      `db:"value" json:"value"`
}

type AdminUser struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Email        string             `db:"email" json:"email"`
	DisplayName  string             `db:"display_name" json:"display_name"`
	PasswordHash string             `db:"password_hash" json:"password_hash"`
	DisabledAt   pgtype.Timestamptz `db:"disabled_at" json:"disabled_at"`
	LastLoginAt  pgtype.Timestamptz `db:"last_login_at" json:"last_login_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type AssetVariant struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	AssetID    pgtype.UUID        `db:"asset_id" json:"asset_id"`
	VariantKey string             `db:"variant_key" json:"variant_key"`
	ObjectKey  string             `db:"object_key" json:"object_key"`
	MimeType   string             `db:"mime_type" json:"mime_type"`
	ByteSize   int64              `db:"byte_size" json:"byte_size"`
	Width      *int32             `db:"width" json:"width"`
	Height     *int32             `db:"height" json:"height"`
	Metadata   []byte             `db:"metadata" json:"metadata"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type AuthConsumedRefreshToken struct {
	TokenHash  []byte             `db:"token_hash" json:"token_hash"`
	SessionID  pgtype.UUID        `db:"session_id" json:"session_id"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at" json:"consumed_at"`
}

type AuthSession struct {
	ID                      pgtype.UUID        `db:"id" json:"id"`
	AdminUserID             pgtype.UUID        `db:"admin_user_id" json:"admin_user_id"`
	CurrentRefreshTokenHash []byte             `db:"current_refresh_token_hash" json:"current_refresh_token_hash"`
	CurrentAccessJti        pgtype.UUID        `db:"current_access_jti" json:"current_access_jti"`
	IdleExpiresAt           pgtype.Timestamptz `db:"idle_expires_at" json:"idle_expires_at"`
	AbsoluteExpiresAt       pgtype.Timestamptz `db:"absolute_expires_at" json:"absolute_expires_at"`
	LastRotatedAt           pgtype.Timestamptz `db:"last_rotated_at" json:"last_rotated_at"`
	UserAgent               string             `db:"user_agent" json:"user_agent"`
	IpAddress               *netip.Addr        `db:"ip_address" json:"ip_address"`
	RevokedAt               pgtype.Timestamptz `db:"revoked_at" json:"revoked_at"`
	RevokeReason            *string            `db:"revoke_reason" json:"revoke_reason"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type MediaAsset struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Kind              MediaKind          `db:"kind" json:"kind"`
	Status            AssetStatus        `db:"status" json:"status"`
	OriginalFilename  string             `db:"original_filename" json:"original_filename"`
	OriginalObjectKey string             `db:"original_object_key" json:"original_object_key"`
	DeliveryObjectKey *string            `db:"delivery_object_key" json:"delivery_object_key"`
	MimeType          string             `db:"mime_type" json:"mime_type"`
	ByteSize          int64              `db:"byte_size" json:"byte_size"`
	ChecksumSha256    *string            `db:"checksum_sha256" json:"checksum_sha256"`
	Width             *int32             `db:"width" json:"width"`
	Height            *int32             `db:"height" json:"height"`
	DurationMs        *int64             `db:"duration_ms" json:"duration_ms"`
	PageCount         *int32             `db:"page_count" json:"page_count"`
	Metadata          []byte             `db:"metadata" json:"metadata"`
	ErrorCode         *string            `db:"error_code" json:"error_code"`
	ErrorMessage      *string            `db:"error_message" json:"error_message"`
	ReadyAt           pgtype.Timestamptz `db:"ready_at" json:"ready_at"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	OriginalPurgedAt  pgtype.Timestamptz `db:"original_purged_at" json:"original_purged_at"`
}

type ProcessingJob struct {
	ID             pgtype.UUID         `db:"id" json:"id"`
	AssetID        pgtype.UUID         `db:"asset_id" json:"asset_id"`
	JobType        ProcessingJobType   `db:"job_type" json:"job_type"`
	Status         ProcessingJobStatus `db:"status" json:"status"`
	IdempotencyKey string              `db:"idempotency_key" json:"idempotency_key"`
	Attempts       int16               `db:"attempts" json:"attempts"`
	MaxAttempts    int16               `db:"max_attempts" json:"max_attempts"`
	RunAfter       pgtype.Timestamptz  `db:"run_after" json:"run_after"`
	LockedAt       pgtype.Timestamptz  `db:"locked_at" json:"locked_at"`
	LockedBy       *string             `db:"locked_by" json:"locked_by"`
	HeartbeatAt    pgtype.Timestamptz  `db:"heartbeat_at" json:"heartbeat_at"`
	LastError      *string             `db:"last_error" json:"last_error"`
	CompletedAt    pgtype.Timestamptz  `db:"completed_at" json:"completed_at"`
	CreatedAt      pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz  `db:"updated_at" json:"updated_at"`
}
