// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processing.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDocumentProcessingJob = `-- name: ClaimDocumentProcessingJob :one
WITH next_job AS (
    SELECT id
    FROM processing_jobs
    WHERE status = 'queued'
      AND job_type = 'document'
      AND run_after <= NOW()
    ORDER BY run_after, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE processing_jobs AS job
SET status = 'processing',
    attempts = attempts + 1,
    locked_at = NOW(),
    locked_by = $1,
    heartbeat_at = NOW(),
    updated_at = NOW()
FROM next_job
WHERE job.id = next_job.id
RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
`

// ClaimDocumentProcessingJob
//
//	WITH next_job AS (
//	    SELECT id
//	    FROM processing_jobs
//	    WHERE status = 'queued'
//	      AND job_type = 'document'
//	      AND run_after <= NOW()
//	    ORDER BY run_after, created_at
//	    FOR UPDATE SKIP LOCKED
//	    LIMIT 1
//	)
//	UPDATE processing_jobs AS job
//	SET status = 'processing',
//	    attempts = attempts + 1,
//	    locked_at = NOW(),
//	    locked_by = $1,
//	    heartbeat_at = NOW(),
//	    updated_at = NOW()
//	FROM next_job
//	WHERE job.id = next_job.id
//	RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
func (q *Queries) ClaimDocumentProcessingJob(ctx context.Context, workerID *string) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, claimDocumentProcessingJob, workerID)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.JobType,
		&i.Status,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimImageProcessingJob = `-- name: ClaimImageProcessingJob :one
WITH next_job AS (
    SELECT id
    FROM processing_jobs
    WHERE status = 'queued'
      AND job_type = 'image'
      AND run_after <= NOW()
    ORDER BY run_after, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE processing_jobs AS job
SET status = 'processing',
    attempts = attempts + 1,
    locked_at = NOW(),
    locked_by = $1,
    heartbeat_at = NOW(),
    updated_at = NOW()
FROM next_job
WHERE job.id = next_job.id
RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
`

// ClaimImageProcessingJob
//
//	WITH next_job AS (
//	    SELECT id
//	    FROM processing_jobs
//	    WHERE status = 'queued'
//	      AND job_type = 'image'
//	      AND run_after <= NOW()
//	    ORDER BY run_after, created_at
//	    FOR UPDATE SKIP LOCKED
//	    LIMIT 1
//	)
//	UPDATE processing_jobs AS job
//	SET status = 'processing',
//	    attempts = attempts + 1,
//	    locked_at = NOW(),
//	    locked_by = $1,
//	    heartbeat_at = NOW(),
//	    updated_at = NOW()
//	FROM next_job
//	WHERE job.id = next_job.id
//	RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
func (q *Queries) ClaimImageProcessingJob(ctx context.Context, workerID *string) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, claimImageProcessingJob, workerID)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.JobType,
		&i.Status,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimVideoProcessingJob = `-- name: ClaimVideoProcessingJob :one
WITH next_job AS (
    SELECT id
    FROM processing_jobs
    WHERE status = 'queued'
      AND job_type = 'video'
      AND run_after <= NOW()
    ORDER BY run_after, created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE processing_jobs AS job
SET status = 'processing',
    attempts = attempts + 1,
    locked_at = NOW(),
    locked_by = $1,
    heartbeat_at = NOW(),
    updated_at = NOW()
FROM next_job
WHERE job.id = next_job.id
RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
`

// ClaimVideoProcessingJob
//
//	WITH next_job AS (
//	    SELECT id
//	    FROM processing_jobs
//	    WHERE status = 'queued'
//	      AND job_type = 'video'
//	      AND run_after <= NOW()
//	    ORDER BY run_after, created_at
//	    FOR UPDATE SKIP LOCKED
//	    LIMIT 1
//	)
//	UPDATE processing_jobs AS job
//	SET status = 'processing',
//	    attempts = attempts + 1,
//	    locked_at = NOW(),
//	    locked_by = $1,
//	    heartbeat_at = NOW(),
//	    updated_at = NOW()
//	FROM next_job
//	WHERE job.id = next_job.id
//	RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
func (q *Queries) ClaimVideoProcessingJob(ctx context.Context, workerID *string) (ProcessingJob, error) {
	row := q.db.QueryRow(ctx, claimVideoProcessingJob, workerID)
	var i ProcessingJob
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.JobType,
		&i.Status,
		&i.IdempotencyKey,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedAt,
		&i.LockedBy,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeProcessingJob = `-- name: CompleteProcessingJob :execrows
UPDATE processing_jobs
SET status = 'completed',
    completed_at = NOW(),
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    last_error = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
`

type CompleteProcessingJobParams struct {
	JobID    pgtype.UUID `db:"job_id" json:"job_id"`
	WorkerID *string     `db:"worker_id" json:"worker_id"`
}

// CompleteProcessingJob
//
//	UPDATE processing_jobs
//	SET status = 'completed',
//	    completed_at = NOW(),
//	    locked_at = NULL,
//	    locked_by = NULL,
//	    heartbeat_at = NULL,
//	    last_error = NULL,
//	    updated_at = NOW()
//	WHERE id = $1
//	  AND status = 'processing'
//	  AND locked_by = $2
func (q *Queries) CompleteProcessingJob(ctx context.Context, arg CompleteProcessingJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeProcessingJob, arg.JobID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failProcessingJob = `-- name: FailProcessingJob :execrows
UPDATE processing_jobs
SET status = 'failed',
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    last_error = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = 'processing'
  AND locked_by = $3
`

type FailProcessingJobParams struct {
	LastError *string     `db:"last_error" json:"last_error"`
	JobID     pgtype.UUID `db:"job_id" json:"job_id"`
	WorkerID  *string     `db:"worker_id" json:"worker_id"`
}

// FailProcessingJob
//
//	UPDATE processing_jobs
//	SET status = 'failed',
//	    locked_at = NULL,
//	    locked_by = NULL,
//	    heartbeat_at = NULL,
//	    last_error = $1,
//	    updated_at = NOW()
//	WHERE id = $2
//	  AND status = 'processing'
//	  AND locked_by = $3
func (q *Queries) FailProcessingJob(ctx context.Context, arg FailProcessingJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failProcessingJob, arg.LastError, arg.JobID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failStaleProcessingJobs = `-- name: FailStaleProcessingJobs :exec
WITH exhausted AS (
    UPDATE processing_jobs
    SET status = 'failed',
        locked_at = NULL,
        locked_by = NULL,
        heartbeat_at = NULL,
        last_error = 'worker heartbeat expired after final attempt',
        updated_at = NOW()
    WHERE status = 'processing'
      AND heartbeat_at < $1
      AND attempts >= max_attempts
    RETURNING asset_id
)
UPDATE media_assets AS asset
SET status = 'failed',
    error_code = 'worker_timeout',
    error_message = 'Media processing timed out after the final attempt.',
    updated_at = NOW()
FROM exhausted
WHERE asset.id = exhausted.asset_id
`

// FailStaleProcessingJobs
//
//	WITH exhausted AS (
//	    UPDATE processing_jobs
//	    SET status = 'failed',
//	        locked_at = NULL,
//	        locked_by = NULL,
//	        heartbeat_at = NULL,
//	        last_error = 'worker heartbeat expired after final attempt',
//	        updated_at = NOW()
//	    WHERE status = 'processing'
//	      AND heartbeat_at < $1
//	      AND attempts >= max_attempts
//	    RETURNING asset_id
//	)
//	UPDATE media_assets AS asset
//	SET status = 'failed',
//	    error_code = 'worker_timeout',
//	    error_message = 'Media processing timed out after the final attempt.',
//	    updated_at = NOW()
//	FROM exhausted
//	WHERE asset.id = exhausted.asset_id
func (q *Queries) FailStaleProcessingJobs(ctx context.Context, staleBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, failStaleProcessingJobs, staleBefore)
	return err
}

const heartbeatProcessingJob = `-- name: HeartbeatProcessingJob :execrows
UPDATE processing_jobs
SET heartbeat_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND status = 'processing'
  AND locked_by = $2
`

type HeartbeatProcessingJobParams struct {
	JobID    pgtype.UUID `db:"job_id" json:"job_id"`
	WorkerID *string     `db:"worker_id" json:"worker_id"`
}

// HeartbeatProcessingJob
//
//	UPDATE processing_jobs
//	SET heartbeat_at = NOW(),
//	    updated_at = NOW()
//	WHERE id = $1
//	  AND status = 'processing'
//	  AND locked_by = $2
func (q *Queries) HeartbeatProcessingJob(ctx context.Context, arg HeartbeatProcessingJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatProcessingJob, arg.JobID, arg.WorkerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDocumentAssetReady = `-- name: MarkDocumentAssetReady :one
UPDATE media_assets
SET status = 'ready',
    delivery_object_key = $1,
    mime_type = 'application/pdf',
    byte_size = $2,
    page_count = $3,
    metadata = metadata || $4::JSONB,
    error_code = NULL,
    error_message = NULL,
    ready_at = NOW(),
    updated_at = NOW()
WHERE id = $5
  AND status = 'processing'
RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
`

type MarkDocumentAssetReadyParams struct {
	DeliveryObjectKey *string     `db:"delivery_object_key" json:"delivery_object_key"`
	ByteSize          int64       `db:"byte_size" json:"byte_size"`
	PageCount         *int32      `db:"page_count" json:"page_count"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
	AssetID           pgtype.UUID `db:"asset_id" json:"asset_id"`
}

// MarkDocumentAssetReady
//
//	UPDATE media_assets
//	SET status = 'ready',
//	    delivery_object_key = $1,
//	    mime_type = 'application/pdf',
//	    byte_size = $2,
//	    page_count = $3,
//	    metadata = metadata || $4::JSONB,
//	    error_code = NULL,
//	    error_message = NULL,
//	    ready_at = NOW(),
//	    updated_at = NOW()
//	WHERE id = $5
//	  AND status = 'processing'
//	RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
func (q *Queries) MarkDocumentAssetReady(ctx context.Context, arg MarkDocumentAssetReadyParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, markDocumentAssetReady,
		arg.DeliveryObjectKey,
		arg.ByteSize,
		arg.PageCount,
		arg.Metadata,
		arg.AssetID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.PageCount,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalPurgedAt,
	)
	return i, err
}

const markImageAssetReady = `-- name: MarkImageAssetReady :one
UPDATE media_assets
SET status = 'ready',
    delivery_object_key = $1,
    mime_type = $2,
    byte_size = $3,
    width = $4,
    height = $5,
    metadata = metadata || $6::JSONB,
    error_code = NULL,
    error_message = NULL,
    ready_at = NOW(),
    updated_at = NOW()
WHERE id = $7
  AND status = 'processing'
RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
`

type MarkImageAssetReadyParams struct {
	DeliveryObjectKey *string     `db:"delivery_object_key" json:"delivery_object_key"`
	MimeType          string      `db:"mime_type" json:"mime_type"`
	ByteSize          int64       `db:"byte_size" json:"byte_size"`
	Width             *int32      `db:"width" json:"width"`
	Height            *int32      `db:"height" json:"height"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
	AssetID           pgtype.UUID `db:"asset_id" json:"asset_id"`
}

// MarkImageAssetReady
//
//	UPDATE media_assets
//	SET status = 'ready',
//	    delivery_object_key = $1,
//	    mime_type = $2,
//	    byte_size = $3,
//	    width = $4,
//	    height = $5,
//	    metadata = metadata || $6::JSONB,
//	    error_code = NULL,
//	    error_message = NULL,
//	    ready_at = NOW(),
//	    updated_at = NOW()
//	WHERE id = $7
//	  AND status = 'processing'
//	RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
func (q *Queries) MarkImageAssetReady(ctx context.Context, arg MarkImageAssetReadyParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, markImageAssetReady,
		arg.DeliveryObjectKey,
		arg.MimeType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.Metadata,
		arg.AssetID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.PageCount,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalPurgedAt,
	)
	return i, err
}

const markMediaAssetFailed = `-- name: MarkMediaAssetFailed :exec
UPDATE media_assets
SET status = 'failed',
    error_code = $1,
    error_message = $2,
    updated_at = NOW()
WHERE id = $3
`

type MarkMediaAssetFailedParams struct {
	ErrorCode    *string     `db:"error_code" json:"error_code"`
	ErrorMessage *string     `db:"error_message" json:"error_message"`
	AssetID      pgtype.UUID `db:"asset_id" json:"asset_id"`
}

// MarkMediaAssetFailed
//
//	UPDATE media_assets
//	SET status = 'failed',
//	    error_code = $1,
//	    error_message = $2,
//	    updated_at = NOW()
//	WHERE id = $3
func (q *Queries) MarkMediaAssetFailed(ctx context.Context, arg MarkMediaAssetFailedParams) error {
	_, err := q.db.Exec(ctx, markMediaAssetFailed, arg.ErrorCode, arg.ErrorMessage, arg.AssetID)
	return err
}

const markVideoAssetReady = `-- name: MarkVideoAssetReady :one
UPDATE media_assets
SET status = 'ready',
    delivery_object_key = $1,
    mime_type = 'video/mp4',
    byte_size = $2,
    width = $3,
    height = $4,
    duration_ms = $5,
    metadata = metadata || $6::JSONB,
    error_code = NULL,
    error_message = NULL,
    ready_at = NOW(),
    updated_at = NOW()
WHERE id = $7
  AND status = 'processing'
RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
`

type MarkVideoAssetReadyParams struct {
	DeliveryObjectKey *string     `db:"delivery_object_key" json:"delivery_object_key"`
	ByteSize          int64       `db:"byte_size" json:"byte_size"`
	Width             *int32      `db:"width" json:"width"`
	Height            *int32      `db:"height" json:"height"`
	DurationMs        *int64      `db:"duration_ms" json:"duration_ms"`
	Metadata          []byte      `db:"metadata" json:"metadata"`
	AssetID           pgtype.UUID `db:"asset_id" json:"asset_id"`
}

// MarkVideoAssetReady
//
//	UPDATE media_assets
//	SET status = 'ready',
//	    delivery_object_key = $1,
//	    mime_type = 'video/mp4',
//	    byte_size = $2,
//	    width = $3,
//	    height = $4,
//	    duration_ms = $5,
//	    metadata = metadata || $6::JSONB,
//	    error_code = NULL,
//	    error_message = NULL,
//	    ready_at = NOW(),
//	    updated_at = NOW()
//	WHERE id = $7
//	  AND status = 'processing'
//	RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at, original_purged_at
func (q *Queries) MarkVideoAssetReady(ctx context.Context, arg MarkVideoAssetReadyParams) (MediaAsset, error) {
	row := q.db.QueryRow(ctx, markVideoAssetReady,
		arg.DeliveryObjectKey,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.DurationMs,
		arg.Metadata,
		arg.AssetID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.OriginalFilename,
		&i.OriginalObjectKey,
		&i.DeliveryObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.ChecksumSha256,
		&i.Width,
		&i.Height,
		&i.DurationMs,
		&i.PageCount,
		&i.Metadata,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OriginalPurgedAt,
	)
	return i, err
}

const retryProcessingJob = `-- name: RetryProcessingJob :execrows
UPDATE processing_jobs
SET status = 'queued',
    run_after = $1,
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    last_error = $2,
    updated_at = NOW()
WHERE id = $3
  AND status = 'processing'
  AND locked_by = $4
  AND attempts < max_attempts
`

type RetryProcessingJobParams struct {
	RunAfter  pgtype.Timestamptz `db:"run_after" json:"run_after"`
	LastError *string            `db:"last_error" json:"last_error"`
	JobID     pgtype.UUID        `db:"job_id" json:"job_id"`
	WorkerID  *string            `db:"worker_id" json:"worker_id"`
}

// RetryProcessingJob
//
//	UPDATE processing_jobs
//	SET status = 'queued',
//	    run_after = $1,
//	    locked_at = NULL,
//	    locked_by = NULL,
//	    heartbeat_at = NULL,
//	    last_error = $2,
//	    updated_at = NOW()
//	WHERE id = $3
//	  AND status = 'processing'
//	  AND locked_by = $4
//	  AND attempts < max_attempts
func (q *Queries) RetryProcessingJob(ctx context.Context, arg RetryProcessingJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryProcessingJob,
		arg.RunAfter,
		arg.LastError,
		arg.JobID,
		arg.WorkerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryStaleProcessingJobs = `-- name: RetryStaleProcessingJobs :exec
UPDATE processing_jobs
SET status = 'queued',
    run_after = NOW(),
    locked_at = NULL,
    locked_by = NULL,
    heartbeat_at = NULL,
    last_error = 'worker heartbeat expired',
    updated_at = NOW()
WHERE status = 'processing'
  AND heartbeat_at < $1
  AND attempts < max_attempts
`

// RetryStaleProcessingJobs
//
//	UPDATE processing_jobs
//	SET status = 'queued',
//	    run_after = NOW(),
//	    locked_at = NULL,
//	    locked_by = NULL,
//	    heartbeat_at = NULL,
//	    last_error = 'worker heartbeat expired',
//	    updated_at = NOW()
//	WHERE status = 'processing'
//	  AND heartbeat_at < $1
//	  AND attempts < max_attempts
func (q *Queries) RetryStaleProcessingJobs(ctx context.Context, staleBefore pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, retryStaleProcessingJobs, staleBefore)
	return err
}

const startMediaAssetProcessing = `-- name: StartMediaAssetProcessing :execrows
UPDATE media_assets
SET status = 'processing',
    error_code = NULL,
    error_message = NULL,
    updated_at = NOW()
WHERE id = $1
  AND status IN ('queued', 'processing')
`

// StartMediaAssetProcessing
//
//	UPDATE media_assets
//	SET status = 'processing',
//	    error_code = NULL,
//	    error_message = NULL,
//	    updated_at = NOW()
//	WHERE id = $1
//	  AND status IN ('queued', 'processing')
func (q *Queries) StartMediaAssetProcessing(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, startMediaAssetProcessing, assetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertAssetVariant = `-- name: UpsertAssetVariant :one
INSERT INTO asset_variants (
    asset_id,
    variant_key,
    object_key,
    mime_type,
    byte_size,
    width,
    height,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (asset_id, variant_key) DO UPDATE
SET object_key = EXCLUDED.object_key,
    mime_type = EXCLUDED.mime_type,
    byte_size = EXCLUDED.byte_size,
    width = EXCLUDED.width,
    height = EXCLUDED.height,
    metadata = EXCLUDED.metadata
RETURNING id, asset_id, variant_key, object_key, mime_type, byte_size, width, height, metadata, created_at
`

type UpsertAssetVariantParams struct {
	AssetID    pgtype.UUID `db:"asset_id" json:"asset_id"`
	VariantKey string      `db:"variant_key" json:"variant_key"`
	ObjectKey  string      `db:"object_key" json:"object_key"`
	MimeType   string      `db:"mime_type" json:"mime_type"`
	ByteSize   int64       `db:"byte_size" json:"byte_size"`
	Width      *int32      `db:"width" json:"width"`
	Height     *int32      `db:"height" json:"height"`
	Metadata   []byte      `db:"metadata" json:"metadata"`
}

// UpsertAssetVariant
//
//	INSERT INTO asset_variants (
//	    asset_id,
//	    variant_key,
//	    object_key,
//	    mime_type,
//	    byte_size,
//	    width,
//	    height,
//	    metadata
//	) VALUES (
//	    $1,
//	    $2,
//	    $3,
//	    $4,
//	    $5,
//	    $6,
//	    $7,
//	    $8
//	)
//	ON CONFLICT (asset_id, variant_key) DO UPDATE
//	SET object_key = EXCLUDED.object_key,
//	    mime_type = EXCLUDED.mime_type,
//	    byte_size = EXCLUDED.byte_size,
//	    width = EXCLUDED.width,
//	    height = EXCLUDED.height,
//	    metadata = EXCLUDED.metadata
//	RETURNING id, asset_id, variant_key, object_key, mime_type, byte_size, width, height, metadata, created_at
func (q *Queries) UpsertAssetVariant(ctx context.Context, arg UpsertAssetVariantParams) (AssetVariant, error) {
	row := q.db.QueryRow(ctx, upsertAssetVariant,
		arg.AssetID,
		arg.VariantKey,
		arg.ObjectKey,
		arg.MimeType,
		arg.ByteSize,
		arg.Width,
		arg.Height,
		arg.Metadata,
	)
	var i AssetVariant
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.VariantKey,
		&i.ObjectKey,
		&i.MimeType,
		&i.ByteSize,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
