// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	//CompleteMediaAssetUpload
	//
	//  UPDATE media_assets
	//  SET status = 'queued',
	//      byte_size = $1,
	//      mime_type = $2,
	//      metadata = metadata || $3::JSONB,
	//      error_code = NULL,
	//      error_message = NULL,
	//      updated_at = NOW()
	//  WHERE id = $4
	//    AND status = 'uploading'
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	CompleteMediaAssetUpload(ctx context.Context, arg CompleteMediaAssetUploadParams) (MediaAsset, error)
	//CountActivityAssetLinks
	//
	//  SELECT COUNT(*) FROM activity_assets WHERE asset_id = $1
	CountActivityAssetLinks(ctx context.Context, assetID pgtype.UUID) (int64, error)
	//CountAdminActivities
	//
	//  SELECT COUNT(*) FROM activities
	CountAdminActivities(ctx context.Context) (int64, error)
	//CountPublicActivities
	//
	//  SELECT COUNT(*)
	//  FROM activities AS a
	//  WHERE a.status = 'published'
	//    AND (
	//      $1::TEXT = ''
	//      OR a.title_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.title_en ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_en ILIKE '%' || $1::TEXT || '%'
	//      OR EXISTS (
	//          SELECT 1
	//          FROM activity_tags AS t
	//          WHERE t.activity_id = a.id
	//            AND t.value ILIKE '%' || $1::TEXT || '%'
	//      )
	//    )
	//    AND (
	//      $2::activity_category IS NULL
	//      OR a.category = $2::activity_category
	//    )
	CountPublicActivities(ctx context.Context, arg CountPublicActivitiesParams) (int64, error)
	//CreateActivity
	//
	//  INSERT INTO activities (
	//      slug,
	//      title_id,
	//      title_en,
	//      caption_id,
	//      caption_en,
	//      body_id,
	//      body_en,
	//      category,
	//      activity_date,
	//      status,
	//      pinned,
	//      progress,
	//      related_project,
	//      published_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      $13,
	//      CASE
	//          WHEN $10::activity_status = 'published' THEN NOW()
	//          ELSE NULL
	//      END
	//  )
	//  RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	//CreateAuthSession
	//
	//  INSERT INTO auth_sessions (
	//      id,
	//      admin_user_id,
	//      current_refresh_token_hash,
	//      current_access_jti,
	//      idle_expires_at,
	//      absolute_expires_at,
	//      user_agent,
	//      ip_address
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8
	//  )
	//  RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	//CreateMediaAsset
	//
	//  INSERT INTO media_assets (
	//      id,
	//      kind,
	//      status,
	//      original_filename,
	//      original_object_key,
	//      mime_type,
	//      byte_size,
	//      metadata
	//  ) VALUES (
	//      $1,
	//      $2,
	//      'uploading',
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  )
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	//CreateProcessingJob
	//
	//  INSERT INTO processing_jobs (
	//      asset_id,
	//      job_type,
	//      idempotency_key
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3
	//  )
	//  ON CONFLICT (idempotency_key) DO NOTHING
	CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) error
	//DeleteActivity
	//
	//  DELETE FROM activities WHERE id = $1
	DeleteActivity(ctx context.Context, activityID pgtype.UUID) (int64, error)
	//DeleteActivityTags
	//
	//  DELETE FROM activity_tags WHERE activity_id = $1
	DeleteActivityTags(ctx context.Context, activityID pgtype.UUID) error
	//DeleteUnlinkedMediaAsset
	//
	//  DELETE FROM media_assets AS asset
	//  WHERE asset.id = $1
	//    AND NOT EXISTS (
	//        SELECT 1
	//        FROM activity_assets AS link
	//        WHERE link.asset_id = asset.id
	//    )
	DeleteUnlinkedMediaAsset(ctx context.Context, assetID pgtype.UUID) (int64, error)
	//FindSessionByConsumedRefreshHash
	//
	//  SELECT session_id
	//  FROM auth_consumed_refresh_tokens
	//  WHERE token_hash = $1
	FindSessionByConsumedRefreshHash(ctx context.Context, tokenHash []byte) (pgtype.UUID, error)
	//GetActiveAdminUserByEmail
	//
	//  SELECT id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
	//  FROM admin_users
	//  WHERE email = LOWER(BTRIM($1))
	//    AND disabled_at IS NULL
	GetActiveAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	//GetActiveSessionPrincipal
	//
	//  SELECT
	//      s.id AS session_id,
	//      s.current_access_jti,
	//      s.idle_expires_at,
	//      s.absolute_expires_at,
	//      u.id AS admin_user_id,
	//      u.email,
	//      u.display_name
	//  FROM auth_sessions AS s
	//  JOIN admin_users AS u ON u.id = s.admin_user_id
	//  WHERE s.id = $1
	//    AND s.current_access_jti = $2
	//    AND s.revoked_at IS NULL
	//    AND s.idle_expires_at > NOW()
	//    AND s.absolute_expires_at > NOW()
	//    AND u.disabled_at IS NULL
	GetActiveSessionPrincipal(ctx context.Context, arg GetActiveSessionPrincipalParams) (GetActiveSessionPrincipalRow, error)
	//GetActivityByID
	//
	//  SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at FROM activities WHERE id = $1
	GetActivityByID(ctx context.Context, activityID pgtype.UUID) (Activity, error)
	//GetDatabaseTime
	//
	//  SELECT NOW()::TIMESTAMPTZ AS database_time
	GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error)
	//GetMediaAsset
	//
	//  SELECT id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at FROM media_assets WHERE id = $1
	GetMediaAsset(ctx context.Context, assetID pgtype.UUID) (MediaAsset, error)
	//GetPublishedActivityBySlug
	//
	//  SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	//  FROM activities
	//  WHERE slug = $1
	//    AND status = 'published'
	GetPublishedActivityBySlug(ctx context.Context, slug *string) (Activity, error)
	//InsertActivityTag
	//
	//  INSERT INTO activity_tags (activity_id, position, value)
	//  VALUES (
	//      $1,
	//      $2,
	//      $3
	//  )
	InsertActivityTag(ctx context.Context, arg InsertActivityTagParams) error
	//ListActivityTags
	//
	//  SELECT activity_id, position, value
	//  FROM activity_tags
	//  WHERE activity_id = $1
	//  ORDER BY position
	ListActivityTags(ctx context.Context, activityID pgtype.UUID) ([]ActivityTag, error)
	//ListAdminActivities
	//
	//  SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	//  FROM activities
	//  ORDER BY updated_at DESC, created_at DESC
	//  LIMIT $2
	//  OFFSET $1
	ListAdminActivities(ctx context.Context, arg ListAdminActivitiesParams) ([]Activity, error)
	//ListPublicActivities
	//
	//  SELECT a.id, a.slug, a.title_id, a.title_en, a.caption_id, a.caption_en, a.body_id, a.body_en, a.category, a.activity_date, a.status, a.pinned, a.progress, a.related_project, a.published_at, a.version, a.created_at, a.updated_at
	//  FROM activities AS a
	//  WHERE a.status = 'published'
	//    AND (
	//      $1::TEXT = ''
	//      OR a.title_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.title_en ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_en ILIKE '%' || $1::TEXT || '%'
	//      OR EXISTS (
	//          SELECT 1
	//          FROM activity_tags AS t
	//          WHERE t.activity_id = a.id
	//            AND t.value ILIKE '%' || $1::TEXT || '%'
	//      )
	//    )
	//    AND (
	//      $2::activity_category IS NULL
	//      OR a.category = $2::activity_category
	//    )
	//  ORDER BY a.pinned DESC, a.activity_date DESC, a.created_at DESC
	//  LIMIT $4
	//  OFFSET $3
	ListPublicActivities(ctx context.Context, arg ListPublicActivitiesParams) ([]Activity, error)
	//LockAuthSessionByRefreshHash
	//
	//  SELECT
	//      s.id, s.admin_user_id, s.current_refresh_token_hash, s.current_access_jti, s.idle_expires_at, s.absolute_expires_at, s.last_rotated_at, s.user_agent, s.ip_address, s.revoked_at, s.revoke_reason, s.created_at, s.updated_at,
	//      u.email,
	//      u.display_name,
	//      u.disabled_at
	//  FROM auth_sessions AS s
	//  JOIN admin_users AS u ON u.id = s.admin_user_id
	//  WHERE s.current_refresh_token_hash = $1
	//  FOR UPDATE OF s
	LockAuthSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (LockAuthSessionByRefreshHashRow, error)
	//MarkAdminLogin
	//
	//  UPDATE admin_users
	//  SET last_login_at = NOW(),
	//      updated_at = NOW()
	//  WHERE id = $1
	MarkAdminLogin(ctx context.Context, adminUserID pgtype.UUID) error
	//RecordConsumedRefreshToken
	//
	//  INSERT INTO auth_consumed_refresh_tokens (
	//      token_hash,
	//      session_id
	//  ) VALUES (
	//      $1,
	//      $2
	//  )
	RecordConsumedRefreshToken(ctx context.Context, arg RecordConsumedRefreshTokenParams) error
	//RevokeAuthSession
	//
	//  UPDATE auth_sessions
	//  SET revoked_at = COALESCE(revoked_at, NOW()),
	//      revoke_reason = COALESCE(revoke_reason, $1),
	//      updated_at = NOW()
	//  WHERE id = $2
	//    AND revoked_at IS NULL
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	//RotateAuthSession
	//
	//  UPDATE auth_sessions
	//  SET current_refresh_token_hash = $1,
	//      current_access_jti = $2,
	//      idle_expires_at = $3,
	//      last_rotated_at = NOW(),
	//      user_agent = $4,
	//      ip_address = $5,
	//      updated_at = NOW()
	//  WHERE id = $6
	//    AND revoked_at IS NULL
	//  RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
	RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (AuthSession, error)
	//UpdateActivity
	//
	//  UPDATE activities
	//  SET slug = $1,
	//      title_id = $2,
	//      title_en = $3,
	//      caption_id = $4,
	//      caption_en = $5,
	//      body_id = $6,
	//      body_en = $7,
	//      category = $8,
	//      activity_date = $9,
	//      status = $10,
	//      pinned = $11,
	//      progress = $12,
	//      related_project = $13,
	//      published_at = CASE
	//          WHEN $10::activity_status = 'published'
	//              THEN COALESCE(published_at, NOW())
	//          ELSE NULL
	//      END,
	//      version = version + 1,
	//      updated_at = NOW()
	//  WHERE id = $14
	//    AND version = $15
	//  RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	//UpsertAdminUser
	//
	//  INSERT INTO admin_users (
	//      email,
	//      display_name,
	//      password_hash
	//  ) VALUES (
	//      LOWER(BTRIM($1)),
	//      BTRIM($2),
	//      $3
	//  )
	//  ON CONFLICT (email) DO UPDATE SET
	//      display_name = EXCLUDED.display_name,
	//      password_hash = EXCLUDED.password_hash,
	//      disabled_at = NULL,
	//      updated_at = NOW()
	//  RETURNING id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
	UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (AdminUser, error)
}

var _ Querier = (*Queries)(nil)
