// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	//AddActivityLike
	//
	//  INSERT INTO activity_likes (activity_id, visitor_id)
	//  VALUES ($1, $2)
	//  ON CONFLICT DO NOTHING
	AddActivityLike(ctx context.Context, arg AddActivityLikeParams) error
	//ClaimDocumentProcessingJob
	//
	//  WITH next_job AS (
	//      SELECT id
	//      FROM processing_jobs
	//      WHERE status = 'queued'
	//        AND job_type = 'document'
	//        AND run_after <= NOW()
	//      ORDER BY run_after, created_at
	//      FOR UPDATE SKIP LOCKED
	//      LIMIT 1
	//  )
	//  UPDATE processing_jobs AS job
	//  SET status = 'processing',
	//      attempts = attempts + 1,
	//      locked_at = NOW(),
	//      locked_by = $1,
	//      heartbeat_at = NOW(),
	//      updated_at = NOW()
	//  FROM next_job
	//  WHERE job.id = next_job.id
	//  RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
	ClaimDocumentProcessingJob(ctx context.Context, workerID *string) (ProcessingJob, error)
	//ClaimImageProcessingJob
	//
	//  WITH next_job AS (
	//      SELECT id
	//      FROM processing_jobs
	//      WHERE status = 'queued'
	//        AND job_type = 'image'
	//        AND run_after <= NOW()
	//      ORDER BY run_after, created_at
	//      FOR UPDATE SKIP LOCKED
	//      LIMIT 1
	//  )
	//  UPDATE processing_jobs AS job
	//  SET status = 'processing',
	//      attempts = attempts + 1,
	//      locked_at = NOW(),
	//      locked_by = $1,
	//      heartbeat_at = NOW(),
	//      updated_at = NOW()
	//  FROM next_job
	//  WHERE job.id = next_job.id
	//  RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
	ClaimImageProcessingJob(ctx context.Context, workerID *string) (ProcessingJob, error)
	//ClaimVideoProcessingJob
	//
	//  WITH next_job AS (
	//      SELECT id
	//      FROM processing_jobs
	//      WHERE status = 'queued'
	//        AND job_type = 'video'
	//        AND run_after <= NOW()
	//      ORDER BY run_after, created_at
	//      FOR UPDATE SKIP LOCKED
	//      LIMIT 1
	//  )
	//  UPDATE processing_jobs AS job
	//  SET status = 'processing',
	//      attempts = attempts + 1,
	//      locked_at = NOW(),
	//      locked_by = $1,
	//      heartbeat_at = NOW(),
	//      updated_at = NOW()
	//  FROM next_job
	//  WHERE job.id = next_job.id
	//  RETURNING job.id, job.asset_id, job.job_type, job.status, job.idempotency_key, job.attempts, job.max_attempts, job.run_after, job.locked_at, job.locked_by, job.heartbeat_at, job.last_error, job.completed_at, job.created_at, job.updated_at
	ClaimVideoProcessingJob(ctx context.Context, workerID *string) (ProcessingJob, error)
	//CompleteMediaAssetUpload
	//
	//  UPDATE media_assets
	//  SET status = 'queued',
	//      byte_size = $1,
	//      mime_type = $2,
	//      metadata = metadata || $3::JSONB,
	//      error_code = NULL,
	//      error_message = NULL,
	//      updated_at = NOW()
	//  WHERE id = $4
	//    AND status = 'uploading'
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	CompleteMediaAssetUpload(ctx context.Context, arg CompleteMediaAssetUploadParams) (MediaAsset, error)
	//CompleteProcessingJob
	//
	//  UPDATE processing_jobs
	//  SET status = 'completed',
	//      completed_at = NOW(),
	//      locked_at = NULL,
	//      locked_by = NULL,
	//      heartbeat_at = NULL,
	//      last_error = NULL,
	//      updated_at = NOW()
	//  WHERE id = $1
	//    AND status = 'processing'
	//    AND locked_by = $2
	CompleteProcessingJob(ctx context.Context, arg CompleteProcessingJobParams) (int64, error)
	//CountActivityAssetLinks
	//
	//  SELECT COUNT(*) FROM activity_assets WHERE asset_id = $1
	CountActivityAssetLinks(ctx context.Context, assetID pgtype.UUID) (int64, error)
	//CountActivityLikes
	//
	//  SELECT COUNT(*) FROM activity_likes WHERE activity_id = $1
	CountActivityLikes(ctx context.Context, activityID pgtype.UUID) (int64, error)
	//CountAdminActivities
	//
	//  SELECT COUNT(*) FROM activities
	CountAdminActivities(ctx context.Context) (int64, error)
	//CountAdminComments
	//
	//  SELECT COUNT(*)
	//  FROM activity_comments AS comment
	//  WHERE (
	//      $1::UUID IS NULL
	//      OR comment.activity_id = $1
	//  )
	//    AND (
	//      $2::comment_status IS NULL
	//      OR comment.status = $2::comment_status
	//    )
	CountAdminComments(ctx context.Context, arg CountAdminCommentsParams) (int64, error)
	//CountPublicActivities
	//
	//  SELECT COUNT(*)
	//  FROM activities AS a
	//  WHERE a.status = 'published'
	//    AND (
	//      $1::TEXT = ''
	//      OR a.title_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.title_en ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_en ILIKE '%' || $1::TEXT || '%'
	//      OR EXISTS (
	//          SELECT 1
	//          FROM activity_tags AS t
	//          WHERE t.activity_id = a.id
	//            AND t.value ILIKE '%' || $1::TEXT || '%'
	//      )
	//    )
	//    AND (
	//      $2::activity_category IS NULL
	//      OR a.category = $2::activity_category
	//    )
	CountPublicActivities(ctx context.Context, arg CountPublicActivitiesParams) (int64, error)
	//CountVisibleActivityComments
	//
	//  SELECT COUNT(*)
	//  FROM activity_comments
	//  WHERE activity_id = $1
	//    AND status = 'visible'
	CountVisibleActivityComments(ctx context.Context, activityID pgtype.UUID) (int64, error)
	//CreateActivity
	//
	//  INSERT INTO activities (
	//      slug,
	//      title_id,
	//      title_en,
	//      caption_id,
	//      caption_en,
	//      body_id,
	//      body_en,
	//      category,
	//      activity_date,
	//      status,
	//      pinned,
	//      progress,
	//      related_project,
	//      published_at
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8,
	//      $9,
	//      $10,
	//      $11,
	//      $12,
	//      $13,
	//      CASE
	//          WHEN $10::activity_status = 'published' THEN NOW()
	//          ELSE NULL
	//      END
	//  )
	//  RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error)
	//CreateActivityComment
	//
	//  INSERT INTO activity_comments (
	//      activity_id,
	//      author_name,
	//      body
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3
	//  )
	//  RETURNING id, activity_id, author_name, body, status, created_at, updated_at
	CreateActivityComment(ctx context.Context, arg CreateActivityCommentParams) (ActivityComment, error)
	//CreateAuthSession
	//
	//  INSERT INTO auth_sessions (
	//      id,
	//      admin_user_id,
	//      current_refresh_token_hash,
	//      current_access_jti,
	//      idle_expires_at,
	//      absolute_expires_at,
	//      user_agent,
	//      ip_address
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8
	//  )
	//  RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
	CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error)
	//CreateMediaAsset
	//
	//  INSERT INTO media_assets (
	//      id,
	//      kind,
	//      status,
	//      original_filename,
	//      original_object_key,
	//      mime_type,
	//      byte_size,
	//      metadata
	//  ) VALUES (
	//      $1,
	//      $2,
	//      'uploading',
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7
	//  )
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	//CreateProcessingJob
	//
	//  INSERT INTO processing_jobs (
	//      asset_id,
	//      job_type,
	//      idempotency_key
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3
	//  )
	//  ON CONFLICT (idempotency_key) DO NOTHING
	CreateProcessingJob(ctx context.Context, arg CreateProcessingJobParams) error
	//DeleteActivity
	//
	//  DELETE FROM activities WHERE id = $1
	DeleteActivity(ctx context.Context, activityID pgtype.UUID) (int64, error)
	//DeleteActivityTags
	//
	//  DELETE FROM activity_tags WHERE activity_id = $1
	DeleteActivityTags(ctx context.Context, activityID pgtype.UUID) error
	//DeleteComment
	//
	//  DELETE FROM activity_comments WHERE id = $1
	DeleteComment(ctx context.Context, commentID pgtype.UUID) (int64, error)
	//DeleteUnlinkedMediaAsset
	//
	//  DELETE FROM media_assets AS asset
	//  WHERE asset.id = $1
	//    AND NOT EXISTS (
	//        SELECT 1
	//        FROM activity_assets AS link
	//        WHERE link.asset_id = asset.id
	//    )
	DeleteUnlinkedMediaAsset(ctx context.Context, assetID pgtype.UUID) (int64, error)
	//FailProcessingJob
	//
	//  UPDATE processing_jobs
	//  SET status = 'failed',
	//      locked_at = NULL,
	//      locked_by = NULL,
	//      heartbeat_at = NULL,
	//      last_error = $1,
	//      updated_at = NOW()
	//  WHERE id = $2
	//    AND status = 'processing'
	//    AND locked_by = $3
	FailProcessingJob(ctx context.Context, arg FailProcessingJobParams) (int64, error)
	//FailStaleProcessingJobs
	//
	//  WITH exhausted AS (
	//      UPDATE processing_jobs
	//      SET status = 'failed',
	//          locked_at = NULL,
	//          locked_by = NULL,
	//          heartbeat_at = NULL,
	//          last_error = 'worker heartbeat expired after final attempt',
	//          updated_at = NOW()
	//      WHERE status = 'processing'
	//        AND heartbeat_at < $1
	//        AND attempts >= max_attempts
	//      RETURNING asset_id
	//  )
	//  UPDATE media_assets AS asset
	//  SET status = 'failed',
	//      error_code = 'worker_timeout',
	//      error_message = 'Media processing timed out after the final attempt.',
	//      updated_at = NOW()
	//  FROM exhausted
	//  WHERE asset.id = exhausted.asset_id
	FailStaleProcessingJobs(ctx context.Context, staleBefore pgtype.Timestamptz) error
	//FindSessionByConsumedRefreshHash
	//
	//  SELECT session_id
	//  FROM auth_consumed_refresh_tokens
	//  WHERE token_hash = $1
	FindSessionByConsumedRefreshHash(ctx context.Context, tokenHash []byte) (pgtype.UUID, error)
	//GetActiveAdminUserByEmail
	//
	//  SELECT id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
	//  FROM admin_users
	//  WHERE email = LOWER(BTRIM($1))
	//    AND disabled_at IS NULL
	GetActiveAdminUserByEmail(ctx context.Context, email string) (AdminUser, error)
	//GetActiveSessionPrincipal
	//
	//  SELECT
	//      s.id AS session_id,
	//      s.current_access_jti,
	//      s.idle_expires_at,
	//      s.absolute_expires_at,
	//      u.id AS admin_user_id,
	//      u.email,
	//      u.display_name
	//  FROM auth_sessions AS s
	//  JOIN admin_users AS u ON u.id = s.admin_user_id
	//  WHERE s.id = $1
	//    AND s.current_access_jti = $2
	//    AND s.revoked_at IS NULL
	//    AND s.idle_expires_at > NOW()
	//    AND s.absolute_expires_at > NOW()
	//    AND u.disabled_at IS NULL
	GetActiveSessionPrincipal(ctx context.Context, arg GetActiveSessionPrincipalParams) (GetActiveSessionPrincipalRow, error)
	//GetActivityByID
	//
	//  SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at FROM activities WHERE id = $1
	GetActivityByID(ctx context.Context, activityID pgtype.UUID) (Activity, error)
	//GetDatabaseTime
	//
	//  SELECT NOW()::TIMESTAMPTZ AS database_time
	GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error)
	//GetMediaAsset
	//
	//  SELECT id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at FROM media_assets WHERE id = $1
	GetMediaAsset(ctx context.Context, assetID pgtype.UUID) (MediaAsset, error)
	//GetPublishedActivityBySlug
	//
	//  SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	//  FROM activities
	//  WHERE slug = $1
	//    AND status = 'published'
	GetPublishedActivityBySlug(ctx context.Context, slug *string) (Activity, error)
	//GetPublishedActivityIDBySlug
	//
	//  SELECT id
	//  FROM activities
	//  WHERE slug = $1
	//    AND status = 'published'
	GetPublishedActivityIDBySlug(ctx context.Context, slug *string) (pgtype.UUID, error)
	//HasActivityLike
	//
	//  SELECT EXISTS (
	//      SELECT 1
	//      FROM activity_likes
	//      WHERE activity_id = $1
	//        AND visitor_id = $2
	//  )
	HasActivityLike(ctx context.Context, arg HasActivityLikeParams) (bool, error)
	//HeartbeatProcessingJob
	//
	//  UPDATE processing_jobs
	//  SET heartbeat_at = NOW(),
	//      updated_at = NOW()
	//  WHERE id = $1
	//    AND status = 'processing'
	//    AND locked_by = $2
	HeartbeatProcessingJob(ctx context.Context, arg HeartbeatProcessingJobParams) (int64, error)
	//InsertActivityTag
	//
	//  INSERT INTO activity_tags (activity_id, position, value)
	//  VALUES (
	//      $1,
	//      $2,
	//      $3
	//  )
	InsertActivityTag(ctx context.Context, arg InsertActivityTagParams) error
	//ListActivityTags
	//
	//  SELECT activity_id, position, value
	//  FROM activity_tags
	//  WHERE activity_id = $1
	//  ORDER BY position
	ListActivityTags(ctx context.Context, activityID pgtype.UUID) ([]ActivityTag, error)
	//ListAdminActivities
	//
	//  SELECT id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	//  FROM activities
	//  ORDER BY updated_at DESC, created_at DESC
	//  LIMIT $2
	//  OFFSET $1
	ListAdminActivities(ctx context.Context, arg ListAdminActivitiesParams) ([]Activity, error)
	//ListAdminComments
	//
	//  SELECT comment.id, comment.activity_id, comment.author_name, comment.body, comment.status, comment.created_at, comment.updated_at, activity.slug AS activity_slug
	//  FROM activity_comments AS comment
	//  JOIN activities AS activity ON activity.id = comment.activity_id
	//  WHERE (
	//      $1::UUID IS NULL
	//      OR comment.activity_id = $1
	//  )
	//    AND (
	//      $2::comment_status IS NULL
	//      OR comment.status = $2::comment_status
	//    )
	//  ORDER BY comment.created_at DESC, comment.id DESC
	//  LIMIT $4
	//  OFFSET $3
	ListAdminComments(ctx context.Context, arg ListAdminCommentsParams) ([]ListAdminCommentsRow, error)
	//ListPublicActivities
	//
	//  SELECT a.id, a.slug, a.title_id, a.title_en, a.caption_id, a.caption_en, a.body_id, a.body_en, a.category, a.activity_date, a.status, a.pinned, a.progress, a.related_project, a.published_at, a.version, a.created_at, a.updated_at
	//  FROM activities AS a
	//  WHERE a.status = 'published'
	//    AND (
	//      $1::TEXT = ''
	//      OR a.title_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.title_en ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_id ILIKE '%' || $1::TEXT || '%'
	//      OR a.caption_en ILIKE '%' || $1::TEXT || '%'
	//      OR EXISTS (
	//          SELECT 1
	//          FROM activity_tags AS t
	//          WHERE t.activity_id = a.id
	//            AND t.value ILIKE '%' || $1::TEXT || '%'
	//      )
	//    )
	//    AND (
	//      $2::activity_category IS NULL
	//      OR a.category = $2::activity_category
	//    )
	//  ORDER BY a.pinned DESC, a.activity_date DESC, a.created_at DESC
	//  LIMIT $4
	//  OFFSET $3
	ListPublicActivities(ctx context.Context, arg ListPublicActivitiesParams) ([]Activity, error)
	//ListVisibleActivityComments
	//
	//  SELECT id, activity_id, author_name, body, status, created_at, updated_at
	//  FROM activity_comments
	//  WHERE activity_id = $1
	//    AND status = 'visible'
	//  ORDER BY created_at DESC, id DESC
	//  LIMIT $3
	//  OFFSET $2
	ListVisibleActivityComments(ctx context.Context, arg ListVisibleActivityCommentsParams) ([]ActivityComment, error)
	//LockAuthSessionByRefreshHash
	//
	//  SELECT
	//      s.id, s.admin_user_id, s.current_refresh_token_hash, s.current_access_jti, s.idle_expires_at, s.absolute_expires_at, s.last_rotated_at, s.user_agent, s.ip_address, s.revoked_at, s.revoke_reason, s.created_at, s.updated_at,
	//      u.email,
	//      u.display_name,
	//      u.disabled_at
	//  FROM auth_sessions AS s
	//  JOIN admin_users AS u ON u.id = s.admin_user_id
	//  WHERE s.current_refresh_token_hash = $1
	//  FOR UPDATE OF s
	LockAuthSessionByRefreshHash(ctx context.Context, refreshTokenHash []byte) (LockAuthSessionByRefreshHashRow, error)
	//MarkAdminLogin
	//
	//  UPDATE admin_users
	//  SET last_login_at = NOW(),
	//      updated_at = NOW()
	//  WHERE id = $1
	MarkAdminLogin(ctx context.Context, adminUserID pgtype.UUID) error
	//MarkDocumentAssetReady
	//
	//  UPDATE media_assets
	//  SET status = 'ready',
	//      delivery_object_key = $1,
	//      mime_type = 'application/pdf',
	//      byte_size = $2,
	//      page_count = $3,
	//      metadata = metadata || $4::JSONB,
	//      error_code = NULL,
	//      error_message = NULL,
	//      ready_at = NOW(),
	//      updated_at = NOW()
	//  WHERE id = $5
	//    AND status = 'processing'
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	MarkDocumentAssetReady(ctx context.Context, arg MarkDocumentAssetReadyParams) (MediaAsset, error)
	//MarkImageAssetReady
	//
	//  UPDATE media_assets
	//  SET status = 'ready',
	//      delivery_object_key = $1,
	//      mime_type = $2,
	//      byte_size = $3,
	//      width = $4,
	//      height = $5,
	//      metadata = metadata || $6::JSONB,
	//      error_code = NULL,
	//      error_message = NULL,
	//      ready_at = NOW(),
	//      updated_at = NOW()
	//  WHERE id = $7
	//    AND status = 'processing'
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	MarkImageAssetReady(ctx context.Context, arg MarkImageAssetReadyParams) (MediaAsset, error)
	//MarkMediaAssetFailed
	//
	//  UPDATE media_assets
	//  SET status = 'failed',
	//      error_code = $1,
	//      error_message = $2,
	//      updated_at = NOW()
	//  WHERE id = $3
	MarkMediaAssetFailed(ctx context.Context, arg MarkMediaAssetFailedParams) error
	//MarkVideoAssetReady
	//
	//  UPDATE media_assets
	//  SET status = 'ready',
	//      delivery_object_key = $1,
	//      mime_type = 'video/mp4',
	//      byte_size = $2,
	//      width = $3,
	//      height = $4,
	//      duration_ms = $5,
	//      metadata = metadata || $6::JSONB,
	//      error_code = NULL,
	//      error_message = NULL,
	//      ready_at = NOW(),
	//      updated_at = NOW()
	//  WHERE id = $7
	//    AND status = 'processing'
	//  RETURNING id, kind, status, original_filename, original_object_key, delivery_object_key, mime_type, byte_size, checksum_sha256, width, height, duration_ms, page_count, metadata, error_code, error_message, ready_at, created_at, updated_at
	MarkVideoAssetReady(ctx context.Context, arg MarkVideoAssetReadyParams) (MediaAsset, error)
	//RecordConsumedRefreshToken
	//
	//  INSERT INTO auth_consumed_refresh_tokens (
	//      token_hash,
	//      session_id
	//  ) VALUES (
	//      $1,
	//      $2
	//  )
	RecordConsumedRefreshToken(ctx context.Context, arg RecordConsumedRefreshTokenParams) error
	//RemoveActivityLike
	//
	//  DELETE FROM activity_likes
	//  WHERE activity_id = $1
	//    AND visitor_id = $2
	RemoveActivityLike(ctx context.Context, arg RemoveActivityLikeParams) error
	//RetryProcessingJob
	//
	//  UPDATE processing_jobs
	//  SET status = 'queued',
	//      run_after = $1,
	//      locked_at = NULL,
	//      locked_by = NULL,
	//      heartbeat_at = NULL,
	//      last_error = $2,
	//      updated_at = NOW()
	//  WHERE id = $3
	//    AND status = 'processing'
	//    AND locked_by = $4
	//    AND attempts < max_attempts
	RetryProcessingJob(ctx context.Context, arg RetryProcessingJobParams) (int64, error)
	//RetryStaleProcessingJobs
	//
	//  UPDATE processing_jobs
	//  SET status = 'queued',
	//      run_after = NOW(),
	//      locked_at = NULL,
	//      locked_by = NULL,
	//      heartbeat_at = NULL,
	//      last_error = 'worker heartbeat expired',
	//      updated_at = NOW()
	//  WHERE status = 'processing'
	//    AND heartbeat_at < $1
	//    AND attempts < max_attempts
	RetryStaleProcessingJobs(ctx context.Context, staleBefore pgtype.Timestamptz) error
	//RevokeAuthSession
	//
	//  UPDATE auth_sessions
	//  SET revoked_at = COALESCE(revoked_at, NOW()),
	//      revoke_reason = COALESCE(revoke_reason, $1),
	//      updated_at = NOW()
	//  WHERE id = $2
	//    AND revoked_at IS NULL
	RevokeAuthSession(ctx context.Context, arg RevokeAuthSessionParams) (int64, error)
	//RotateAuthSession
	//
	//  UPDATE auth_sessions
	//  SET current_refresh_token_hash = $1,
	//      current_access_jti = $2,
	//      idle_expires_at = $3,
	//      last_rotated_at = NOW(),
	//      user_agent = $4,
	//      ip_address = $5,
	//      updated_at = NOW()
	//  WHERE id = $6
	//    AND revoked_at IS NULL
	//  RETURNING id, admin_user_id, current_refresh_token_hash, current_access_jti, idle_expires_at, absolute_expires_at, last_rotated_at, user_agent, ip_address, revoked_at, revoke_reason, created_at, updated_at
	RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (AuthSession, error)
	//StartMediaAssetProcessing
	//
	//  UPDATE media_assets
	//  SET status = 'processing',
	//      error_code = NULL,
	//      error_message = NULL,
	//      updated_at = NOW()
	//  WHERE id = $1
	//    AND status IN ('queued', 'processing')
	StartMediaAssetProcessing(ctx context.Context, assetID pgtype.UUID) (int64, error)
	//UpdateActivity
	//
	//  UPDATE activities
	//  SET slug = $1,
	//      title_id = $2,
	//      title_en = $3,
	//      caption_id = $4,
	//      caption_en = $5,
	//      body_id = $6,
	//      body_en = $7,
	//      category = $8,
	//      activity_date = $9,
	//      status = $10,
	//      pinned = $11,
	//      progress = $12,
	//      related_project = $13,
	//      published_at = CASE
	//          WHEN $10::activity_status = 'published'
	//              THEN COALESCE(published_at, NOW())
	//          ELSE NULL
	//      END,
	//      version = version + 1,
	//      updated_at = NOW()
	//  WHERE id = $14
	//    AND version = $15
	//  RETURNING id, slug, title_id, title_en, caption_id, caption_en, body_id, body_en, category, activity_date, status, pinned, progress, related_project, published_at, version, created_at, updated_at
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (Activity, error)
	//UpdateCommentStatus
	//
	//  UPDATE activity_comments
	//  SET status = $1,
	//      updated_at = NOW()
	//  WHERE id = $2
	//  RETURNING id, activity_id, author_name, body, status, created_at, updated_at
	UpdateCommentStatus(ctx context.Context, arg UpdateCommentStatusParams) (ActivityComment, error)
	//UpsertAdminUser
	//
	//  INSERT INTO admin_users (
	//      email,
	//      display_name,
	//      password_hash
	//  ) VALUES (
	//      LOWER(BTRIM($1)),
	//      BTRIM($2),
	//      $3
	//  )
	//  ON CONFLICT (email) DO UPDATE SET
	//      display_name = EXCLUDED.display_name,
	//      password_hash = EXCLUDED.password_hash,
	//      disabled_at = NULL,
	//      updated_at = NOW()
	//  RETURNING id, email, display_name, password_hash, disabled_at, last_login_at, created_at, updated_at
	UpsertAdminUser(ctx context.Context, arg UpsertAdminUserParams) (AdminUser, error)
	//UpsertAssetVariant
	//
	//  INSERT INTO asset_variants (
	//      asset_id,
	//      variant_key,
	//      object_key,
	//      mime_type,
	//      byte_size,
	//      width,
	//      height,
	//      metadata
	//  ) VALUES (
	//      $1,
	//      $2,
	//      $3,
	//      $4,
	//      $5,
	//      $6,
	//      $7,
	//      $8
	//  )
	//  ON CONFLICT (asset_id, variant_key) DO UPDATE
	//  SET object_key = EXCLUDED.object_key,
	//      mime_type = EXCLUDED.mime_type,
	//      byte_size = EXCLUDED.byte_size,
	//      width = EXCLUDED.width,
	//      height = EXCLUDED.height,
	//      metadata = EXCLUDED.metadata
	//  RETURNING id, asset_id, variant_key, object_key, mime_type, byte_size, width, height, metadata, created_at
	UpsertAssetVariant(ctx context.Context, arg UpsertAssetVariantParams) (AssetVariant, error)
}

var _ Querier = (*Queries)(nil)
