// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDatabaseTime = `-- name: GetDatabaseTime :one
SELECT NOW()::TIMESTAMPTZ AS database_time
`

// GetDatabaseTime
//
//	SELECT NOW()::TIMESTAMPTZ AS database_time
func (q *Queries) GetDatabaseTime(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getDatabaseTime)
	var database_time pgtype.Timestamptz
	err := row.Scan(&database_time)
	return database_time, err
}
