// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivityAssetRole.
const (
	Attachment ActivityAssetRole = "attachment"
	Cover      ActivityAssetRole = "cover"
	Gallery    ActivityAssetRole = "gallery"
)

// Valid indicates whether the value is a known member of the ActivityAssetRole enum.
func (e ActivityAssetRole) Valid() bool {
	switch e {
	case Attachment:
		return true
	case Cover:
		return true
	case Gallery:
		return true
	default:
		return false
	}
}

// Defines values for ActivityCategory.
const (
	ActivityCategoryAchievement ActivityCategory = "achievement"
	ActivityCategoryDaily       ActivityCategory = "daily"
	ActivityCategoryLearning    ActivityCategory = "learning"
	ActivityCategoryProject     ActivityCategory = "project"
)

// Valid indicates whether the value is a known member of the ActivityCategory enum.
func (e ActivityCategory) Valid() bool {
	switch e {
	case ActivityCategoryAchievement:
		return true
	case ActivityCategoryDaily:
		return true
	case ActivityCategoryLearning:
		return true
	case ActivityCategoryProject:
		return true
	default:
		return false
	}
}

// Defines values for ActivityProgress.
const (
	ActivityProgressExploring ActivityProgress = "exploring"
	ActivityProgressLearning  ActivityProgress = "learning"
	ActivityProgressShipped   ActivityProgress = "shipped"
)

// Valid indicates whether the value is a known member of the ActivityProgress enum.
func (e ActivityProgress) Valid() bool {
	switch e {
	case ActivityProgressExploring:
		return true
	case ActivityProgressLearning:
		return true
	case ActivityProgressShipped:
		return true
	default:
		return false
	}
}

// Defines values for ActivityStatus.
const (
	ActivityStatusDraft     ActivityStatus = "draft"
	ActivityStatusHidden    ActivityStatus = "hidden"
	ActivityStatusPublished ActivityStatus = "published"
)

// Valid indicates whether the value is a known member of the ActivityStatus enum.
func (e ActivityStatus) Valid() bool {
	switch e {
	case ActivityStatusDraft:
		return true
	case ActivityStatusHidden:
		return true
	case ActivityStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for AssetStatus.
const (
	AssetStatusFailed     AssetStatus = "failed"
	AssetStatusProcessing AssetStatus = "processing"
	AssetStatusQueued     AssetStatus = "queued"
	AssetStatusReady      AssetStatus = "ready"
	AssetStatusUploading  AssetStatus = "uploading"
)

// Valid indicates whether the value is a known member of the AssetStatus enum.
func (e AssetStatus) Valid() bool {
	switch e {
	case AssetStatusFailed:
		return true
	case AssetStatusProcessing:
		return true
	case AssetStatusQueued:
		return true
	case AssetStatusReady:
		return true
	case AssetStatusUploading:
		return true
	default:
		return false
	}
}

// Defines values for CommentStatus.
const (
	CommentStatusHidden  CommentStatus = "hidden"
	CommentStatusVisible CommentStatus = "visible"
)

// Valid indicates whether the value is a known member of the CommentStatus enum.
func (e CommentStatus) Valid() bool {
	switch e {
	case CommentStatusHidden:
		return true
	case CommentStatusVisible:
		return true
	default:
		return false
	}
}

// Defines values for ContactCategory.
const (
	Collaboration ContactCategory = "collaboration"
	General       ContactCategory = "general"
	Internship    ContactCategory = "internship"
)

// Valid indicates whether the value is a known member of the ContactCategory enum.
func (e ContactCategory) Valid() bool {
	switch e {
	case Collaboration:
		return true
	case General:
		return true
	case Internship:
		return true
	default:
		return false
	}
}

// Defines values for ContactMessageResponseOk.
const (
	True ContactMessageResponseOk = true
)

// Valid indicates whether the value is a known member of the ContactMessageResponseOk enum.
func (e ContactMessageResponseOk) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MediaKind.
const (
	Document MediaKind = "document"
	Image    MediaKind = "image"
	Video    MediaKind = "video"
)

// Valid indicates whether the value is a known member of the MediaKind enum.
func (e MediaKind) Valid() bool {
	switch e {
	case Document:
		return true
	case Image:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for PresignedAssetUploadMethod.
const (
	PUT PresignedAssetUploadMethod = "PUT"
)

// Valid indicates whether the value is a known member of the PresignedAssetUploadMethod enum.
func (e PresignedAssetUploadMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	ReadinessStatusReady       ReadinessStatus = "ready"
	ReadinessStatusUnavailable ReadinessStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case ReadinessStatusReady:
		return true
	case ReadinessStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetContentParamsVariant.
const (
	Delivery  GetAssetContentParamsVariant = "delivery"
	Download  GetAssetContentParamsVariant = "download"
	Poster    GetAssetContentParamsVariant = "poster"
	Thumbnail GetAssetContentParamsVariant = "thumbnail"
)

// Valid indicates whether the value is a known member of the GetAssetContentParamsVariant enum.
func (e GetAssetContentParamsVariant) Valid() bool {
	switch e {
	case Delivery:
		return true
	case Download:
		return true
	case Poster:
		return true
	case Thumbnail:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	Assets         []ActivityAsset    `json:"assets"`
	Body           LocalizedText      `json:"body"`
	Caption        LocalizedText      `json:"caption"`
	Category       ActivityCategory   `json:"category"`
	CreatedAt      time.Time          `json:"created_at"`
	Date           openapi_types.Date `json:"date"`
	ID             openapi_types.UUID `json:"id"`
	Pinned         bool               `json:"pinned"`
	Progress       *ActivityProgress  `json:"progress,omitempty"`
	RelatedProject *string            `json:"related_project,omitempty"`
	Slug           *string            `json:"slug,omitempty"`
	Status         ActivityStatus     `json:"status"`
	Tags           []string           `json:"tags"`
	Title          LocalizedText      `json:"title"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Version        int64              `json:"version"`
}

// ActivityAsset defines model for ActivityAsset.
type ActivityAsset struct {
	Alt          string                  `json:"alt"`
	AssetID      openapi_types.UUID      `json:"asset_id"`
	ByteSize     int64                   `json:"byte_size"`
	Caption      LocalizedText           `json:"caption"`
	Crop         *map[string]interface{} `json:"crop,omitempty"`
	DownloadSrc  *string                 `json:"download_src,omitempty"`
	DurationMs   *int64                  `json:"duration_ms,omitempty"`
	Filename     string                  `json:"filename"`
	Height       *int                    `json:"height,omitempty"`
	Kind         MediaKind               `json:"kind"`
	Label        LocalizedText           `json:"label"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	MimeType     string                  `json:"mime_type"`
	PageCount    *int                    `json:"page_count,omitempty"`
	Position     int                     `json:"position"`
	PosterSrc    *string                 `json:"poster_src,omitempty"`
	PreviewSrc   *string                 `json:"preview_src,omitempty"`
	Role         ActivityAssetRole       `json:"role"`
	Src          *string                 `json:"src,omitempty"`
	Status       AssetStatus             `json:"status"`
	ThumbnailSrc *string                 `json:"thumbnail_src,omitempty"`
	Width        *int                    `json:"width,omitempty"`
}

// ActivityAssetRole defines model for ActivityAssetRole.
type ActivityAssetRole string

// ActivityAssetWrite defines model for ActivityAssetWrite.
type ActivityAssetWrite struct {
	Alt      string                  `json:"alt"`
	AssetID  openapi_types.UUID      `json:"asset_id"`
	Caption  LocalizedText           `json:"caption"`
	Crop     *map[string]interface{} `json:"crop,omitempty"`
	Label    LocalizedText           `json:"label"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Position int                     `json:"position"`
	Role     ActivityAssetRole       `json:"role"`
}

// ActivityCategory defines model for ActivityCategory.
type ActivityCategory string

// ActivityComment defines model for ActivityComment.
type ActivityComment struct {
	ActivityID   openapi_types.UUID `json:"activity_id"`
	ActivitySlug *string            `json:"activity_slug,omitempty"`
	Author       string             `json:"author"`
	Body         string             `json:"body"`
	CreatedAt    time.Time          `json:"created_at"`
	ID           openapi_types.UUID `json:"id"`
	Status       CommentStatus      `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// ActivityList defines model for ActivityList.
type ActivityList struct {
	Items  []Activity `json:"items"`
	Limit  int        `json:"limit"`
	Offset int        `json:"offset"`
	Total  int64      `json:"total"`
}

// ActivityProgress defines model for ActivityProgress.
type ActivityProgress string

// ActivityStatus defines model for ActivityStatus.
type ActivityStatus string

// ActivityWrite defines model for ActivityWrite.
type ActivityWrite struct {
	Assets         []ActivityAssetWrite `json:"assets"`
	Body           LocalizedText        `json:"body"`
	Caption        LocalizedText        `json:"caption"`
	Category       ActivityCategory     `json:"category"`
	Date           openapi_types.Date   `json:"date"`
	Pinned         bool                 `json:"pinned"`
	Progress       *ActivityProgress    `json:"progress,omitempty"`
	RelatedProject *string              `json:"related_project,omitempty"`
	Slug           *string              `json:"slug,omitempty"`
	Status         ActivityStatus       `json:"status"`
	Tags           []string             `json:"tags"`
	Title          LocalizedText        `json:"title"`
}

// AdminCommentList defines model for AdminCommentList.
type AdminCommentList struct {
	Items  []ActivityComment `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int64             `json:"total"`
}

// AdminLoginRequest defines model for AdminLoginRequest.
type AdminLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AdminSession defines model for AdminSession.
type AdminSession struct {
	ExpiresAt time.Time `json:"expires_at"`
	User      AdminUser `json:"user"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	ID          openapi_types.UUID  `json:"id"`
}

// AssetStatus defines model for AssetStatus.
type AssetStatus string

// CommentStatus defines model for CommentStatus.
type CommentStatus string

// ContactCategory defines model for ContactCategory.
type ContactCategory string

// ContactMessageRequest defines model for ContactMessageRequest.
type ContactMessageRequest struct {
	Category ContactCategory     `json:"category"`
	Company  string              `json:"company"`
	Email    openapi_types.Email `json:"email"`
	Message  string              `json:"message"`
	Name     string              `json:"name"`
}

// ContactMessageResponse defines model for ContactMessageResponse.
type ContactMessageResponse struct {
	Ok ContactMessageResponseOk `json:"ok"`
}

// ContactMessageResponseOk defines model for ContactMessageResponse.Ok.
type ContactMessageResponseOk bool

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest = ActivityWrite

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	Author string `json:"author"`
	Body   string `json:"body"`
}

// EngagementSnapshot defines model for EngagementSnapshot.
type EngagementSnapshot struct {
	CommentLimit  int               `json:"comment_limit"`
	CommentOffset int               `json:"comment_offset"`
	CommentTotal  int64             `json:"comment_total"`
	Comments      []ActivityComment `json:"comments"`
	Liked         bool              `json:"liked"`
	Likes         int64             `json:"likes"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
	RequestID string `json:"request_id"`
}

// Health defines model for Health.
type Health struct {
	// Service Example: portfolio-api
	Service string       `json:"service"`
	Status  HealthStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LikeState defines model for LikeState.
type LikeState struct {
	Liked bool  `json:"liked"`
	Likes int64 `json:"likes"`
}

// LocalizedText defines model for LocalizedText.
type LocalizedText struct {
	En string `json:"en"`
	ID string `json:"id"`
}

// MediaAsset defines model for MediaAsset.
type MediaAsset struct {
	ByteSize     int64              `json:"byte_size"`
	CreatedAt    time.Time          `json:"created_at"`
	DurationMs   *int64             `json:"duration_ms,omitempty"`
	ErrorCode    *string            `json:"error_code,omitempty"`
	ErrorMessage *string            `json:"error_message,omitempty"`
	Filename     string             `json:"filename"`
	Height       *int               `json:"height,omitempty"`
	ID           openapi_types.UUID `json:"id"`
	Kind         MediaKind          `json:"kind"`
	MimeType     string             `json:"mime_type"`
	PageCount    *int               `json:"page_count,omitempty"`
	ReadyAt      *time.Time         `json:"ready_at,omitempty"`
	Status       AssetStatus        `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
	Width        *int               `json:"width,omitempty"`
}

// MediaKind defines model for MediaKind.
type MediaKind string

// ModerateCommentRequest defines model for ModerateCommentRequest.
type ModerateCommentRequest struct {
	Status CommentStatus `json:"status"`
}

// PresignAssetUploadRequest defines model for PresignAssetUploadRequest.
type PresignAssetUploadRequest struct {
	ByteSize int64     `json:"byte_size"`
	Filename string    `json:"filename"`
	Kind     MediaKind `json:"kind"`
	MimeType string    `json:"mime_type"`
}

// PresignedAssetUpload defines model for PresignedAssetUpload.
type PresignedAssetUpload struct {
	Asset     MediaAsset                 `json:"asset"`
	ExpiresAt time.Time                  `json:"expires_at"`
	Method    PresignedAssetUploadMethod `json:"method"`
	UploadURL string                     `json:"upload_url"`
}

// PresignedAssetUploadMethod defines model for PresignedAssetUpload.Method.
type PresignedAssetUploadMethod string

// Readiness defines model for Readiness.
type Readiness struct {
	// Service Example: portfolio-api
	Service string          `json:"service"`
	Status  ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// ServiceInfo defines model for ServiceInfo.
type ServiceInfo struct {
	// Commit Example: unknown
	Commit string `json:"commit"`

	// Name Example: portfolio-api
	Name string `json:"name"`

	// Version Example: dev
	Version string `json:"version"`
}

// SetLikeRequest defines model for SetLikeRequest.
type SetLikeRequest struct {
	Liked bool `json:"liked"`
}

// UpdateActivityRequest defines model for UpdateActivityRequest.
type UpdateActivityRequest struct {
	Assets         []ActivityAssetWrite `json:"assets"`
	Body           LocalizedText        `json:"body"`
	Caption        LocalizedText        `json:"caption"`
	Category       ActivityCategory     `json:"category"`
	Date           openapi_types.Date   `json:"date"`
	Pinned         bool                 `json:"pinned"`
	Progress       *ActivityProgress    `json:"progress,omitempty"`
	RelatedProject *string              `json:"related_project,omitempty"`
	Slug           *string              `json:"slug,omitempty"`
	Status         ActivityStatus       `json:"status"`
	Tags           []string             `json:"tags"`
	Title          LocalizedText        `json:"title"`
	Version        int64                `json:"version"`
}

// ActivityID defines model for ActivityID.
type ActivityID = openapi_types.UUID

// ActivitySlug defines model for ActivitySlug.
type ActivitySlug = string

// AssetID defines model for AssetID.
type AssetID = openapi_types.UUID

// CommentID defines model for CommentID.
type CommentID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListPublicActivitiesParams defines parameters for ListPublicActivities.
type ListPublicActivitiesParams struct {
	Limit    *Limit            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *Offset           `form:"offset,omitempty" json:"offset,omitempty"`
	Search   *string           `form:"search,omitempty" json:"search,omitempty"`
	Category *ActivityCategory `form:"category,omitempty" json:"category,omitempty"`
}

// GetActivityEngagementParams defines parameters for GetActivityEngagement.
type GetActivityEngagementParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAdminActivitiesParams defines parameters for ListAdminActivities.
type ListAdminActivitiesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAdminCommentsParams defines parameters for ListAdminComments.
type ListAdminCommentsParams struct {
	Limit      *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
	ActivityID *openapi_types.UUID `form:"activity_id,omitempty" json:"activity_id,omitempty"`
	Status     *CommentStatus      `form:"status,omitempty" json:"status,omitempty"`
}

// GetAssetContentParams defines parameters for GetAssetContent.
type GetAssetContentParams struct {
	Variant GetAssetContentParamsVariant `form:"variant" json:"variant"`
}

// GetAssetContentParamsVariant defines parameters for GetAssetContent.
type GetAssetContentParamsVariant string

// CreateActivityCommentJSONRequestBody defines body for CreateActivityComment for application/json ContentType.
type CreateActivityCommentJSONRequestBody = CreateCommentRequest

// SetActivityLikeJSONRequestBody defines body for SetActivityLike for application/json ContentType.
type SetActivityLikeJSONRequestBody = SetLikeRequest

// CreateAdminActivityJSONRequestBody defines body for CreateAdminActivity for application/json ContentType.
type CreateAdminActivityJSONRequestBody = CreateActivityRequest

// UpdateAdminActivityJSONRequestBody defines body for UpdateAdminActivity for application/json ContentType.
type UpdateAdminActivityJSONRequestBody = UpdateActivityRequest

// PresignAdminAssetUploadJSONRequestBody defines body for PresignAdminAssetUpload for application/json ContentType.
type PresignAdminAssetUploadJSONRequestBody = PresignAssetUploadRequest

// LoginAdminJSONRequestBody defines body for LoginAdmin for application/json ContentType.
type LoginAdminJSONRequestBody = AdminLoginRequest

// ModerateAdminCommentJSONRequestBody defines body for ModerateAdminComment for application/json ContentType.
type ModerateAdminCommentJSONRequestBody = ModerateCommentRequest

// SendContactMessageJSONRequestBody defines body for SendContactMessage for application/json ContentType.
type SendContactMessageJSONRequestBody = ContactMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetServiceInfo Read API build information
	// (GET /api/v1)
	GetServiceInfo(c *gin.Context)
	// ListPublicActivities List published activities
	// (GET /api/v1/activities)
	ListPublicActivities(c *gin.Context, params ListPublicActivitiesParams)
	// GetPublicActivity Read a published activity
	// (GET /api/v1/activities/{slug})
	GetPublicActivity(c *gin.Context, slug ActivitySlug)
	// CreateActivityComment Publish a visitor comment
	// (POST /api/v1/activities/{slug}/comments)
	CreateActivityComment(c *gin.Context, slug ActivitySlug)
	// GetActivityEngagement Read likes and visible comments
	// (GET /api/v1/activities/{slug}/engagement)
	GetActivityEngagement(c *gin.Context, slug ActivitySlug, params GetActivityEngagementParams)
	// SetActivityLike Set the current visitor like state
	// (PUT /api/v1/activities/{slug}/like)
	SetActivityLike(c *gin.Context, slug ActivitySlug)
	// ListAdminActivities List all activities
	// (GET /api/v1/admin/activities)
	ListAdminActivities(c *gin.Context, params ListAdminActivitiesParams)
	// CreateAdminActivity Create an activity
	// (POST /api/v1/admin/activities)
	CreateAdminActivity(c *gin.Context)
	// DeleteAdminActivity Delete an activity
	// (DELETE /api/v1/admin/activities/{id})
	DeleteAdminActivity(c *gin.Context, id ActivityID)
	// GetAdminActivity Read an activity by ID
	// (GET /api/v1/admin/activities/{id})
	GetAdminActivity(c *gin.Context, id ActivityID)
	// UpdateAdminActivity Replace an activity
	// (PUT /api/v1/admin/activities/{id})
	UpdateAdminActivity(c *gin.Context, id ActivityID)
	// PresignAdminAssetUpload Create an asset and presign its original upload
	// (POST /api/v1/admin/assets/uploads)
	PresignAdminAssetUpload(c *gin.Context)
	// DeleteAdminAsset Delete an asset that is not attached to an activity
	// (DELETE /api/v1/admin/assets/{id})
	DeleteAdminAsset(c *gin.Context, id AssetID)
	// GetAdminAsset Read upload and processing status
	// (GET /api/v1/admin/assets/{id})
	GetAdminAsset(c *gin.Context, id AssetID)
	// CompleteAdminAssetUpload Verify a direct upload and enqueue media processing
	// (POST /api/v1/admin/assets/{id}/complete)
	CompleteAdminAssetUpload(c *gin.Context, id AssetID)
	// LoginAdmin Start an administrator session
	// (POST /api/v1/admin/auth/login)
	LoginAdmin(c *gin.Context)
	// LogoutAdmin Revoke the current administrator session
	// (POST /api/v1/admin/auth/logout)
	LogoutAdmin(c *gin.Context)
	// RefreshAdminSession Rotate an administrator session
	// (POST /api/v1/admin/auth/refresh)
	RefreshAdminSession(c *gin.Context)
	// GetAdminSession Read the current administrator session
	// (GET /api/v1/admin/auth/session)
	GetAdminSession(c *gin.Context)
	// ListAdminComments List comments for moderation
	// (GET /api/v1/admin/comments)
	ListAdminComments(c *gin.Context, params ListAdminCommentsParams)
	// DeleteAdminComment Permanently delete a comment
	// (DELETE /api/v1/admin/comments/{comment_id})
	DeleteAdminComment(c *gin.Context, commentID CommentID)
	// ModerateAdminComment Change comment visibility
	// (PATCH /api/v1/admin/comments/{comment_id})
	ModerateAdminComment(c *gin.Context, commentID CommentID)
	// GetAssetContent Redirect to an authorized short-lived asset URL
	// (GET /api/v1/assets/{id}/content)
	GetAssetContent(c *gin.Context, id AssetID, params GetAssetContentParams)
	// SendContactMessage Deliver a portfolio contact message
	// (POST /api/v1/contact)
	SendContactMessage(c *gin.Context)
	// GetHealth Check process health
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// GetReadiness Check dependency readiness
	// (GET /readyz)
	GetReadiness(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetServiceInfo operation middleware
func (siw *ServerInterfaceWrapper) GetServiceInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceInfo(c)
}

// ListPublicActivities operation middleware
func (siw *ServerInterfaceWrapper) ListPublicActivities(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicActivitiesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicActivities(c, params)
}

// GetPublicActivity operation middleware
func (siw *ServerInterfaceWrapper) GetPublicActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicActivity(c, slug)
}

// CreateActivityComment operation middleware
func (siw *ServerInterfaceWrapper) CreateActivityComment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateActivityComment(c, slug)
}

// GetActivityEngagement operation middleware
func (siw *ServerInterfaceWrapper) GetActivityEngagement(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActivityEngagementParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivityEngagement(c, slug, params)
}

// SetActivityLike operation middleware
func (siw *ServerInterfaceWrapper) SetActivityLike(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetActivityLike(c, slug)
}

// ListAdminActivities operation middleware
func (siw *ServerInterfaceWrapper) ListAdminActivities(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminActivitiesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAdminActivities(c, params)
}

// CreateAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminActivity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAdminActivity(c)
}

// DeleteAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ActivityID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminActivity(c, id)
}

// GetAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) GetAdminActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ActivityID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminActivity(c, id)
}

// UpdateAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ActivityID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAdminActivity(c, id)
}

// PresignAdminAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) PresignAdminAssetUpload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PresignAdminAssetUpload(c)
}

// DeleteAdminAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminAsset(c, id)
}

// GetAdminAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAdminAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminAsset(c, id)
}

// CompleteAdminAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteAdminAssetUpload(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteAdminAssetUpload(c, id)
}

// LoginAdmin operation middleware
func (siw *ServerInterfaceWrapper) LoginAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginAdmin(c)
}

// LogoutAdmin operation middleware
func (siw *ServerInterfaceWrapper) LogoutAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LogoutAdmin(c)
}

// RefreshAdminSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshAdminSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshAdminSession(c)
}

// GetAdminSession operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminSession(c)
}

// ListAdminComments operation middleware
func (siw *ServerInterfaceWrapper) ListAdminComments(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminCommentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "activity_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "activity_id", c.Request.URL.Query(), &params.ActivityID, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter activity_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAdminComments(c, params)
}

// DeleteAdminComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminComment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "comment_id" -------------
	var commentID CommentID

	err = runtime.BindStyledParameterWithOptions("simple", "comment_id", c.Param("comment_id"), &commentID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter comment_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminComment(c, commentID)
}

// ModerateAdminComment operation middleware
func (siw *ServerInterfaceWrapper) ModerateAdminComment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "comment_id" -------------
	var commentID CommentID

	err = runtime.BindStyledParameterWithOptions("simple", "comment_id", c.Param("comment_id"), &commentID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter comment_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ModerateAdminComment(c, commentID)
}

// GetAssetContent operation middleware
func (siw *ServerInterfaceWrapper) GetAssetContent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetContentParams

	// ------------- Required query parameter "variant" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "variant", c.Request.URL.Query(), &params.Variant, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAssetContent(c, id, params)
}

// SendContactMessage operation middleware
func (siw *ServerInterfaceWrapper) SendContactMessage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendContactMessage(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
	router.GET(options.BaseURL+"/api/v1", wrapper.GetServiceInfo)
	router.POST(options.BaseURL+"/api/v1/contact", wrapper.SendContactMessage)
	router.POST(options.BaseURL+"/api/v1/admin/auth/login", wrapper.LoginAdmin)
	router.POST(options.BaseURL+"/api/v1/admin/auth/refresh", wrapper.RefreshAdminSession)
	router.POST(options.BaseURL+"/api/v1/admin/auth/logout", wrapper.LogoutAdmin)
	router.GET(options.BaseURL+"/api/v1/admin/auth/session", wrapper.GetAdminSession)
	router.GET(options.BaseURL+"/api/v1/activities", wrapper.ListPublicActivities)
	router.GET(options.BaseURL+"/api/v1/activities/:slug", wrapper.GetPublicActivity)
	router.GET(options.BaseURL+"/api/v1/activities/:slug/engagement", wrapper.GetActivityEngagement)
	router.PUT(options.BaseURL+"/api/v1/activities/:slug/like", wrapper.SetActivityLike)
	router.POST(options.BaseURL+"/api/v1/activities/:slug/comments", wrapper.CreateActivityComment)
	router.GET(options.BaseURL+"/api/v1/admin/activities", wrapper.ListAdminActivities)
	router.POST(options.BaseURL+"/api/v1/admin/activities", wrapper.CreateAdminActivity)
	router.DELETE(options.BaseURL+"/api/v1/admin/activities/:id", wrapper.DeleteAdminActivity)
	router.GET(options.BaseURL+"/api/v1/admin/activities/:id", wrapper.GetAdminActivity)
	router.PUT(options.BaseURL+"/api/v1/admin/activities/:id", wrapper.UpdateAdminActivity)
	router.POST(options.BaseURL+"/api/v1/admin/assets/uploads", wrapper.PresignAdminAssetUpload)
	router.DELETE(options.BaseURL+"/api/v1/admin/assets/:id", wrapper.DeleteAdminAsset)
	router.GET(options.BaseURL+"/api/v1/admin/assets/:id", wrapper.GetAdminAsset)
	router.POST(options.BaseURL+"/api/v1/admin/assets/:id/complete", wrapper.CompleteAdminAssetUpload)
	router.GET(options.BaseURL+"/api/v1/assets/:id/content", wrapper.GetAssetContent)
	router.GET(options.BaseURL+"/api/v1/admin/comments", wrapper.ListAdminComments)
	router.DELETE(options.BaseURL+"/api/v1/admin/comments/:comment_id", wrapper.DeleteAdminComment)
	router.PATCH(options.BaseURL+"/api/v1/admin/comments/:comment_id", wrapper.ModerateAdminComment)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7F3rc+O4kf9XULxU3Uu2NF7vZqMvV85M9uKK5+Kyx3cfJj4XTLZExCTABUB5tFP+36/wIsE3KUsaz1W+",
	"WRYJNLp/3egHGvoahCzNGAUqRbD8GmSY4xQkcP3pIpRkQ+T28oP6RGiwDDIs42AWUJxCsAxIFMwCDr/m",
	"hEMULCXPYRaIMIYUqzdWjKdYBssgz/WTcpupt4TkhK6Dl5dZMcNtkq875hDqq75ZUvzlCuhaxsHy92ez",
	"ICXUfXw3U2NJ4GrU//2MT35bnPzh/t//5T+WJ8WHf/2337VTJgTIwy38PUtToN0ThOb7h1dPdEVSIotJ",
	"fs2Bb8tZEv2lP2AEK5wnMlieLWaKsyTN02D540Lz1Xx4V0xDqIQ1cD3PX1crAZ0TMfNt60z+2IuWsV8U",
	"A0TGqACNyj/i6AZ+zUHo2UJGJVD9J86yhIRYEkbnfxeMqv+V8/2OwypYBv80LxE/N9+K+Z84Z3aqCETI",
	"SaYGCZbBpxgQN5OhDG8ThiNEBCJ0gxMSnQZaknSVkPBoxAiW8xBQaKcV6JnIGIU550AlEsA3wJGQWIIm",
	"7xfGH0kUAT0usxgna0IVryiTCCcJewbDr0uqFBInZpijEhWyPIk0QY+KgWmWgIQIRTkgyRB2zAM1lqb1",
	"v5j8heU0OiqZEJVSfsaGgStFhSbpFviGhHBH8QaTBD8mcHjiLpCzQJpFJAQlWAlpxjjmJNmivCRHU/mJ",
	"sY+Ybq2eiiPwjzGUYrp1TBSnwSyIAUd2K7sBybcnFysJvDpbr1lT89xRnMuYcfIbHAEHF7mMgUo7Klph",
	"kkCEGEcyBiRACPVfrVUoYXQNHDlL9OKMa2Xr1mRGEVGj4eSaswy4JMqQrnAiYBZk3r++BljtevovIiEV",
	"Q8tws+jNUsndchBzjrfq8yOLtkODXLEQJ4q7n+CLHiTElhuT35OwZnw7lur37nn1LgcsIXrAsrKtRljC",
	"iSQpNPfWmf6y8XTbgyQasVfPgoxQajBmv3pkLAFM9XecrTkII6Qk+esqWH4et8pr9+bL/SygeWJthvIk",
	"9M6a6HVnnP0dzCZWfaaFTmGdtZrjNfyexDIfjalb87QCFV5XIdkYuQ47SaSxi5Pwk2fRZAxsgAuL1eIF",
	"QuVP58Ggx1R6dZ+Nnsyc+pUq4IG6gtGZw5pGkgVOwWHLMseHyspKku8Lqtijlr3njxuFnmg7EtkqHL2o",
	"h5E68LiV8CDIbzCZo6+wG5xl3Ws1YO4Ad8m5iD1T5R4+CB6O0qIo59rGPxhMd6910Tm7t/YVScD42i0S",
	"iIGsY1nf7YYHfSLG9enj5keICP6LevBlFiT4EZLJ/E9B4ghLPCSDBs9TksKD+W/LqjO8hoeQ5XSHlWdM",
	"EIelvuBEPymBj5Z6xmFD4Hn085wNG7KK0t6oF5SxHTnBSKOshvYscpynjxSTZPQ6nkmk9olpcqgZSWVg",
	"PHPiGwvfYhaqYAHsYOnjxZOw5XHBiUGzeGNFAlQt43MQsg3wYBascZKYoBdLicNYxe/eaCUvKqP9DyfG",
	"i5huab3998fFYvZKy/tNreeRDcd49d5R/4aQW6LVYbOOxz4YvvccXYdC58DNggQwp0qoykkgiQZkGBPY",
	"wCAibVZqKhzt22ORVjzvHMlB62EisFYr7yKMJp538OhHLmCczbTMLK3mdP+yDiOP0QVTZs55rLiHpOIO",
	"ejP34eqKiKmyL3zySfFim8+euERlUwlZkVtsfieZxEmrAzWwmxiCZ0UOtEhRmhH7+HTtBWNO/zytEzHJ",
	"Mu2Pw5csYVqUfVp3W8CpUOb8MSEi1mNEHK8UWbHJ4vUNtNNe8oqI38z3PYf9o0P4NxKbe1v+u7PF7DuI",
	"1b2JfzqvV2ca06b4y6V5853n0bwqrt8l0rYoGIirW01ElBJqLf/RzKnbtr9Tq6pYdsXWhHplnQk8gxST",
	"Kq3mPzMfe2c/nrdpNRbimfGorlqLsyGo1pbtZiwG7FzorcnhTl3jl4xwEJOcmVyYXHcvghRJd6JFkN6M",
	"dqjOJd3ZiSasJyIiS/D2oTNl0S3U3Zy22uoq88+KsUmH4Lzo19ulf80h1+YhzxKGI7P5Z5yFSsTUFK2x",
	"tjYmjd+6d1e9RG/0DRHkUQemPTv/e0YlDmVbQLAGChzrVemKm/JKlJVjyvIzk3vqG/MjCIHXsJtOjt2T",
	"6/Sr7ZylGabbmkqetQa4r1D91CyvGUcvBjcpB9r6ZjzFYPhpXbvgEoaONjtVGyTrQjL18YlSYk8eYJQj",
	"UM5UuDc1utlTOzk69nD7kY+ZSf6QdSjvixGtduwGwjJq9CT187B8nfdahd9EAVejszae/Ymu8VrH5LcU",
	"ZyJmk5XMnhHp2ePdI317vXume8/vT5HY9/fstjx1edvqKzGZzLr6VVjX4FOdKd4iHW2OkFbJuqMNU3b4",
	"Hd4JWdS+e3rGbcAMqRHK59sWYwvqNrkz4AbpRVTeaRvyz4ATkw2esFh78sB4QzjNVCAQZIzLFUsIO8EZ",
	"6U/VuH2xYsFaC3nl8BFsBl0JR5cXJfRV2K7IE6jNfqqtPrRGDKO6GldNRDdtxekoTNFux0wXn3apVb6q",
	"zLjLUYG9Fvu0mj047R+M5c3jnk0YfOMg1cSRydXJRcfDVQG1+94n58NU13Y5h7CP+lqlnOYnk72KmpaZ",
	"Lav55bSxqeZScp5JJqnxdjckAhbMgoiFeWet4iOLgL/WNdwpg183/N31wmsOgqypluudDg53I3PATLnj",
	"uWc/nb07P3cuao/p8vW6EiH9OOgUv04tJ03WA8tmbbecpkcQEHmi2CVBPmrlxSm4XbI1KciYVbTi+u5T",
	"qwKYbMNDzqvOes7JcAFJGO+2ktyxM1cGbuPlDeCIUJfnPr7j5pIp3lnTFv4MeWdtK7Nnai/piu0QgpnY",
	"q1xaTp8oe6ZBT+ZgAh929kstaXbSfqf0FqTyS3czUp2eaauH2Tb9nd4z9pU9mH2tEbinM3rdDLzXh28h",
	"zDmR21tFlSuMhyDEe8aeCBSdEaH5WLRGFAh4wFFK6IN5qRQvzshfYGvckRUHEU8cz77VHFARTSzkQ5NO",
	"0s6hGeZjHuM0xRG6IBFJ0C9EchwHjfPKf/706RpdXF+iFeOo9Z1/FqggCbkKNsoSLJUwTv9GP8W6m0Fy",
	"HEpEBIIvGaYRRIjQkOv8CE6SrWlzABzG6BGHT0AjtAIscw6nf6NFSWYZXBdzOVgo8jz8L4PF6bvTha6A",
	"ZECV2i2DH04Xpz/o/L2MtejmOCPzzTv159qYf4Uo7cNfRsEy+E+QvtWotaicLRZ7OyruT9N2YPz6EimR",
	"IUwj9JiTRPHNwJwwas+F52mK+TZYahuuxdV40hW3lp+D262QkAYa1ZYPcys4q1GtLLkiQl7njwkJL8qH",
	"Z5WWsg5FLh+Zm3YlpcMDD9p+I/VkW8ORAMzDOOjoE9Pp2ob5bB/Jy9SOE1izzvxyf0B8VA5vtADkGq8J",
	"VS45Kk4VoFKaulvj3JDTNktB9txru3qZBT+OeaXa6lNFoiK3lSIPiB6OOsA4/yqSfP3Sp6YVSG4nA7LS",
	"oXgUQbYKsc6oLYpAYpJY+Z0PC6PoZdqH9LQdwU35bXeR3tzPIGdMtMixWl9wieM9yFID+o824b8XMbYW",
	"Ll6qzkRxwKMCpXd7h1KRYW8iyn6FbKC/qx04X/ww/ErZg7gLWM/P/jD8Qr3hbB8gt0qHMNoQQSTjKCyA",
	"50BeFnGGQA7lkz3WyknOG/d1KJ/tf8s9pBFsKYq1gdd2uzq5qNDC9LxqNygrtjxnWb6lmdQZdU2XLekj",
	"r5g0HUdqOG0o8xYE3ZYIUgHd27SQtWhzlG3cH8LKAkwLsEwkGtUBhddrDmv1SWeS/2Esm1C/Bal7VMNO",
	"1RyDdhWxjo019NmjY4Yab8OLL7mDCEWwAb5FJrdlYfluWJCVnuZXSN+mPDS3q8mOz/eKXTV3HydJh6Ov",
	"RIkqDuOs3xP0ZL8NDunI1bNS38iTaw39XSjwah9uB8icL0YYmuJujKNgzAgMYdoajTQh1mN45l9J9GJu",
	"KUnA1OqrMPyg/1+H4W6b7eWHNttybqZvFbihKjp9hfSm7itvT9xGBOPFPet2ug8oxsVxTUElK3AMYBxe",
	"zibXUEoZPW7R5YfB3aPNPbaFhv2Ke/87T3s95Mh+8ii42Wr/kXee79923UCW4PBVe5VuYJmbmm1P5swd",
	"RdCY94rgh0Fu98GHI/tNrYX/NiSrrxGHkPFIh3oiZlyeJGQDEYoIh1Aiw2N0d3N1ZJxPjRaP6mJpxuls",
	"i2E1IlLYa79wYnnWxLRpu+rG8xS/yx5mmGi+7b1+Iz0ub5Vko5ZerPAZOCAOKdsc3f4dPovwpr09LRMZ",
	"Y1lcL6fvW4BI3+LWZ1Ed+oZcwX0ja3+7sn/QqDsvalhUyQq80b35SO6jNeFGkV2DFqq2dU4zUnN3f2BP",
	"0co+0bL3fnfIMpSjDXCyItDgpGmF+4cZPDia/1sJYItwzTdR4gCqpYBSJUhU6UMcje9cxvOErQntRrXu",
	"1NUDHciHbPYDHzvy8ft0W3RB04ZEHoYAkdUFLcLyhkZzKEsYJ0GArN1GeQvypDzGVVJVP5Ly8rb1ydQa",
	"jnSxp4al2uohzfZ4vecuKqveGsGslqtaazUTibnUHotCHBGSY8m4A1FTb3MZ92ktMymPTrVluSz1dsjz",
	"tfhHHDbsyYLcoTpMAPPXpR/fXmhzoxdaqWHtQSzu9GWnXG7MAxWb8w1tmyWnZt24SVeYAyP7NG1vFjuv",
	"VHEfdrVjuw3cMelC6tfDTZS3S/RGOG8AaUWsUt54rNDm8+AtFzR1WLE/Y+EfgeuveL8vD498m6O11VvI",
	"JvwWQcdJXReEjazK1nqy7g8NYf8yn97CvBNhWZZPTaua2kbLC/mP5c8dqaZfrHrFuLfgBvAL2PaAf/61",
	"/NmLsVnAXc+Clj/AMS4T6M5L7qH0evC49fCivwaeYjVi4orRCLecjmyIXndYhHFToq6rc68y3X9s2tF8",
	"+o1Kcz3He91BNiuT/2+ZmSNUOmJM18VRTXN0kyRtWeUOy1ZJFRZC7/TK1OPv7XM75wc7ttgN5gTrcbt/",
	"Sch1WUaQkI1521xtHXjXPQflPedtrZd1Q/rD4vdNQ3oDNnVlfnLFK7eZdroTIRnHazD1tkpsccWMuqi/",
	"x/wmUmtH7Mubz217PqbHKopKcipsM8n+u5srH5ktKT6vx689FL0FGlXvlTrUybrWG8aObEQ7btBqsaX2",
	"EaQMRiZtSGz15KidEzuf7T07zg8Y6fvLUMbZhkTAEQelz+bna8qfXrKM07GTvZPkdH8ptQ92dOw1nVrg",
	"o/JaNacmFgNWT2J9LdFvfWba3lx0QFjaGTo4fHF96TL7iAhkKN7WuzzfxxA+Fc/FjubW/k7dVd+75rLv",
	"/4DLLifpWbnSOyIFiiADGgENCQiEdRkeR1sfRYenyftNrIKcrZJJ9aewWuTiPc491jalox0WvnFOQL0I",
	"EeIERbCBhGXWW9ZXQgSxlNlyPk/UAzETcvnz4ueF9ojtFM1Ur/lNLwMUzWV3s/5p6URYupSPUdvQmcSS",
	"0LXNDJ48YlFP5Lh0iPDG8/IhzTFN02Zb47hiWWWY8pRUc5iLam7JjZFiatsPmvT0DfdB78Ynkp3UXBVT",
	"crO1uISsINyGSvz1wc2u3E6n3dmd/4XYymmwa90NyxUY79KfoGvoa+CCCKUMbpCyH6nsjirG8Tozhtjp",
	"XOMy6G8suHCNR0jYWWnHAG8wZ6Zf7l/+LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
