// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	Ready       ReadinessStatus = "ready"
	Unavailable ReadinessStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case Ready:
		return true
	case Unavailable:
		return true
	default:
		return false
	}
}

// AdminLoginRequest defines model for AdminLoginRequest.
type AdminLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AdminSession defines model for AdminSession.
type AdminSession struct {
	ExpiresAt time.Time `json:"expires_at"`
	User      AdminUser `json:"user"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	ID          openapi_types.UUID  `json:"id"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
	RequestID string `json:"request_id"`
}

// Health defines model for Health.
type Health struct {
	// Service Example: portfolio-api
	Service string       `json:"service"`
	Status  HealthStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Readiness defines model for Readiness.
type Readiness struct {
	// Service Example: portfolio-api
	Service string          `json:"service"`
	Status  ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// ServiceInfo defines model for ServiceInfo.
type ServiceInfo struct {
	// Commit Example: unknown
	Commit string `json:"commit"`

	// Name Example: portfolio-api
	Name string `json:"name"`

	// Version Example: dev
	Version string `json:"version"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// LoginAdminJSONRequestBody defines body for LoginAdmin for application/json ContentType.
type LoginAdminJSONRequestBody = AdminLoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetServiceInfo Read API build information
	// (GET /api/v1)
	GetServiceInfo(c *gin.Context)
	// LoginAdmin Start an administrator session
	// (POST /api/v1/admin/auth/login)
	LoginAdmin(c *gin.Context)
	// LogoutAdmin Revoke the current administrator session
	// (POST /api/v1/admin/auth/logout)
	LogoutAdmin(c *gin.Context)
	// RefreshAdminSession Rotate an administrator session
	// (POST /api/v1/admin/auth/refresh)
	RefreshAdminSession(c *gin.Context)
	// GetAdminSession Read the current administrator session
	// (GET /api/v1/admin/auth/session)
	GetAdminSession(c *gin.Context)
	// GetHealth Check process health
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// GetReadiness Check dependency readiness
	// (GET /readyz)
	GetReadiness(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetServiceInfo operation middleware
func (siw *ServerInterfaceWrapper) GetServiceInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceInfo(c)
}

// LoginAdmin operation middleware
func (siw *ServerInterfaceWrapper) LoginAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginAdmin(c)
}

// LogoutAdmin operation middleware
func (siw *ServerInterfaceWrapper) LogoutAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LogoutAdmin(c)
}

// RefreshAdminSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshAdminSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshAdminSession(c)
}

// GetAdminSession operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminSession(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
	router.GET(options.BaseURL+"/api/v1", wrapper.GetServiceInfo)
	router.POST(options.BaseURL+"/api/v1/admin/auth/login", wrapper.LoginAdmin)
	router.POST(options.BaseURL+"/api/v1/admin/auth/refresh", wrapper.RefreshAdminSession)
	router.POST(options.BaseURL+"/api/v1/admin/auth/logout", wrapper.LogoutAdmin)
	router.GET(options.BaseURL+"/api/v1/admin/auth/session", wrapper.GetAdminSession)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFjfT9tOEv9XVnsn3UtIAqVSz2+0ul7R9SQE5YkiNHgn8Zb1rr+741AX5X//atZObCcGGgq0b46zO/OZ",
	"+cxP38nU5YWzaCnI5E56DIWzAeOP96BO8a8SA/Gv1FlCGx+hKIxOgbSzk2/BWX4X0gxz4Kd/epzJRP5j",
	"0oqe1P+GyX+8d14ul8uRVBhSrwsWIhP5JUPha2WigMo4UEIHoe0CjFZjuRzJj85fa6XQvi4a5/VcWwZj",
	"HQkwxt1iDejYEnoLphbzqqBSVxoVAV2jYCEGCZVQJQpyAkRAv0AvkGVFrGfoFzrFcwsL0AauDb484KMI",
	"V3tUEY9Okb1ImBfOg9emEmULJ6I8t1BS5rz+geoV8JWUoaVGqpiBNqiE84IyFAFD4LeRd2GcnaMXq2Bc",
	"jhrdMU+OVK7tZzfXtpMuoJRmsWBOvCvQk+akmoEJOJJF59WdxBy04YeZ8zmQTJo3I5nD989o55TJ5ODt",
	"4UhSVaBMZCCv7ZwdVkAIt85HZ3UO708PDkeSUa1ebN1djuSKHZlcrDWuBV6ub7jrb5gSa4uGntWO2dXG",
	"74X2GK6AeoYqINwjnaMcMK4M6B8jN0I654NbFrUaG1H3mnTeKNrBHqVDYaC6spDHTNoCfz+pW0e16p0r",
	"S63kY3z19I/WsvUwcesKtQtjT7iTOjXsjRxDgPnQfxt2RQnt+SFjmhp4VbvtkbCORvTuDIn8hGA4TXYy",
	"tqlpdXQDl2CZyMJ5mjmj3R4UeojsQEBl7WBb5ozR3XQwtQcX6Fd51opXuHg0NFa41rpaWUO2nyIobTGE",
	"32S+R1AVp2inNV3ubOOQZU3PO7Yzt3Mc57mmvmmlvbHu1g4ZtSoCO/jhyew20BqlD1HL3sa09JqqM66W",
	"tWmQphjCB+dudMSsuROm9c+VJS38K+D6eFVfarFBof+HVZ2MM48h21Fec2tbIIPWDV/c/CGNLDRi/l9m",
	"kOegxJFW2oiPmjxkcquvf/ry5UQcnRyLmfNi8M6/glhDEpCSXmiqRGGAuAqPv1qetVi/h5R4BMDvBViF",
	"SmibeszREhhTiVtNmUBIM3EN6Q1aJWYIVHocf42BoinyerLWdbTSdXRy3CEvkdPx/njKprgCLcdMIt+M",
	"p+M3sSVTFqmbQKEni31+nGP0C8dsHF6OlUzkf5G6IT/qT/MH0+mzjVRdNUOD1cmxYMoEWCWuS23Yb3V/",
	"084281OZ5+ArmcQCFOnaOskuhHngsD+rAmEuL/lq44dJjKUJT4wTw9MXoy5cGPBMHM5iq297wXunqmdz",
	"yPYIuOwnLvkSly/ISG80G6AkYhOhTFNEjmNmJlaHdtKtkzaIW4wvaSxHMkNQ6CPaM6S9Ns1bVJvlinUf",
	"1pYNAV57YNJZL+OV/cev9PaDeOnN45favZFvHPz7FTY150QOthIxLAUQ7zwUNhx6iuSrvaMZ1cNnqzPX",
	"VufcHNupXVvCeRxyWdvbn3FvfzuNt37CWQN7Yj9bzwg8CbAiZp8O5IGcXwVRJ2NjRAresR7KWlfSg2nr",
	"Smrztpc7h3EM7/m9iX/hceFumiBfRXVqEHyzuL9SrD2Fpk7TlsnFZru+uFxe9ksnGxr31bT0Hi09By2r",
	"7nwvL6f1gV7N+Y21rYGzUd08FgbS2Kuft7T9sbHziyneDbuNsW4r7hwB4TNVgdB+ULhvrPlTIu3DKsna",
	"L0ccbV0fPL3AvEa5APVrxSKLi/KPh7hqdukXZKnRcM8nUp4kC+/YDzy514irzaHzQ4bpzfpctsI8OG7G",
	"DfVBm9sd+gXNbpU8YDlXPk1BKCzQKrQplz3wKKIR406ReHlMne+/azgVc9L/7DvAS+e477h2m50Y/34R",
	"6/jF3dbMm4IRChdoXMF9QI5k6Y1MZEZUJJOJ4QOZC5S8m76bSk6WRsX2ZFF/v64DJXo5RwIFBON2zW1w",
	"LUeb12O91HbeNKK9awibdWOVfaEjr5N+y8vl3wEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
