// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivityAssetRole.
const (
	Attachment ActivityAssetRole = "attachment"
	Cover      ActivityAssetRole = "cover"
	Gallery    ActivityAssetRole = "gallery"
)

// Valid indicates whether the value is a known member of the ActivityAssetRole enum.
func (e ActivityAssetRole) Valid() bool {
	switch e {
	case Attachment:
		return true
	case Cover:
		return true
	case Gallery:
		return true
	default:
		return false
	}
}

// Defines values for ActivityCategory.
const (
	ActivityCategoryAchievement ActivityCategory = "achievement"
	ActivityCategoryDaily       ActivityCategory = "daily"
	ActivityCategoryLearning    ActivityCategory = "learning"
	ActivityCategoryProject     ActivityCategory = "project"
)

// Valid indicates whether the value is a known member of the ActivityCategory enum.
func (e ActivityCategory) Valid() bool {
	switch e {
	case ActivityCategoryAchievement:
		return true
	case ActivityCategoryDaily:
		return true
	case ActivityCategoryLearning:
		return true
	case ActivityCategoryProject:
		return true
	default:
		return false
	}
}

// Defines values for ActivityProgress.
const (
	ActivityProgressExploring ActivityProgress = "exploring"
	ActivityProgressLearning  ActivityProgress = "learning"
	ActivityProgressShipped   ActivityProgress = "shipped"
)

// Valid indicates whether the value is a known member of the ActivityProgress enum.
func (e ActivityProgress) Valid() bool {
	switch e {
	case ActivityProgressExploring:
		return true
	case ActivityProgressLearning:
		return true
	case ActivityProgressShipped:
		return true
	default:
		return false
	}
}

// Defines values for ActivityStatus.
const (
	ActivityStatusDraft     ActivityStatus = "draft"
	ActivityStatusHidden    ActivityStatus = "hidden"
	ActivityStatusPublished ActivityStatus = "published"
)

// Valid indicates whether the value is a known member of the ActivityStatus enum.
func (e ActivityStatus) Valid() bool {
	switch e {
	case ActivityStatusDraft:
		return true
	case ActivityStatusHidden:
		return true
	case ActivityStatusPublished:
		return true
	default:
		return false
	}
}

// Defines values for AssetStatus.
const (
	AssetStatusFailed     AssetStatus = "failed"
	AssetStatusProcessing AssetStatus = "processing"
	AssetStatusQueued     AssetStatus = "queued"
	AssetStatusReady      AssetStatus = "ready"
	AssetStatusUploading  AssetStatus = "uploading"
)

// Valid indicates whether the value is a known member of the AssetStatus enum.
func (e AssetStatus) Valid() bool {
	switch e {
	case AssetStatusFailed:
		return true
	case AssetStatusProcessing:
		return true
	case AssetStatusQueued:
		return true
	case AssetStatusReady:
		return true
	case AssetStatusUploading:
		return true
	default:
		return false
	}
}

// Defines values for CommentStatus.
const (
	CommentStatusHidden  CommentStatus = "hidden"
	CommentStatusVisible CommentStatus = "visible"
)

// Valid indicates whether the value is a known member of the CommentStatus enum.
func (e CommentStatus) Valid() bool {
	switch e {
	case CommentStatusHidden:
		return true
	case CommentStatusVisible:
		return true
	default:
		return false
	}
}

// Defines values for ContactCategory.
const (
	Collaboration ContactCategory = "collaboration"
	General       ContactCategory = "general"
	Internship    ContactCategory = "internship"
)

// Valid indicates whether the value is a known member of the ContactCategory enum.
func (e ContactCategory) Valid() bool {
	switch e {
	case Collaboration:
		return true
	case General:
		return true
	case Internship:
		return true
	default:
		return false
	}
}

// Defines values for ContactMessageResponseOk.
const (
	True ContactMessageResponseOk = true
)

// Valid indicates whether the value is a known member of the ContactMessageResponseOk enum.
func (e ContactMessageResponseOk) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MediaKind.
const (
	Document MediaKind = "document"
	Image    MediaKind = "image"
	Video    MediaKind = "video"
)

// Valid indicates whether the value is a known member of the MediaKind enum.
func (e MediaKind) Valid() bool {
	switch e {
	case Document:
		return true
	case Image:
		return true
	case Video:
		return true
	default:
		return false
	}
}

// Defines values for PresignedAssetUploadMethod.
const (
	PUT PresignedAssetUploadMethod = "PUT"
)

// Valid indicates whether the value is a known member of the PresignedAssetUploadMethod enum.
func (e PresignedAssetUploadMethod) Valid() bool {
	switch e {
	case PUT:
		return true
	default:
		return false
	}
}

// Defines values for ReadinessStatus.
const (
	ReadinessStatusReady       ReadinessStatus = "ready"
	ReadinessStatusUnavailable ReadinessStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ReadinessStatus enum.
func (e ReadinessStatus) Valid() bool {
	switch e {
	case ReadinessStatusReady:
		return true
	case ReadinessStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for GetAdminAssetContentParamsVariant.
const (
	GetAdminAssetContentParamsVariantDelivery  GetAdminAssetContentParamsVariant = "delivery"
	GetAdminAssetContentParamsVariantDownload  GetAdminAssetContentParamsVariant = "download"
	GetAdminAssetContentParamsVariantPoster    GetAdminAssetContentParamsVariant = "poster"
	GetAdminAssetContentParamsVariantThumbnail GetAdminAssetContentParamsVariant = "thumbnail"
)

// Valid indicates whether the value is a known member of the GetAdminAssetContentParamsVariant enum.
func (e GetAdminAssetContentParamsVariant) Valid() bool {
	switch e {
	case GetAdminAssetContentParamsVariantDelivery:
		return true
	case GetAdminAssetContentParamsVariantDownload:
		return true
	case GetAdminAssetContentParamsVariantPoster:
		return true
	case GetAdminAssetContentParamsVariantThumbnail:
		return true
	default:
		return false
	}
}

// Defines values for GetAssetContentParamsVariant.
const (
	GetAssetContentParamsVariantDelivery  GetAssetContentParamsVariant = "delivery"
	GetAssetContentParamsVariantDownload  GetAssetContentParamsVariant = "download"
	GetAssetContentParamsVariantPoster    GetAssetContentParamsVariant = "poster"
	GetAssetContentParamsVariantThumbnail GetAssetContentParamsVariant = "thumbnail"
)

// Valid indicates whether the value is a known member of the GetAssetContentParamsVariant enum.
func (e GetAssetContentParamsVariant) Valid() bool {
	switch e {
	case GetAssetContentParamsVariantDelivery:
		return true
	case GetAssetContentParamsVariantDownload:
		return true
	case GetAssetContentParamsVariantPoster:
		return true
	case GetAssetContentParamsVariantThumbnail:
		return true
	default:
		return false
	}
}

// Activity defines model for Activity.
type Activity struct {
	Assets         []ActivityAsset    `json:"assets"`
	Body           LocalizedText      `json:"body"`
	Caption        LocalizedText      `json:"caption"`
	Category       ActivityCategory   `json:"category"`
	CreatedAt      time.Time          `json:"created_at"`
	Date           openapi_types.Date `json:"date"`
	ID             openapi_types.UUID `json:"id"`
	Pinned         bool               `json:"pinned"`
	Progress       *ActivityProgress  `json:"progress,omitempty"`
	RelatedProject *string            `json:"related_project,omitempty"`
	Slug           *string            `json:"slug,omitempty"`
	Status         ActivityStatus     `json:"status"`
	Tags           []string           `json:"tags"`
	Title          LocalizedText      `json:"title"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Version        int64              `json:"version"`
}

// ActivityAsset defines model for ActivityAsset.
type ActivityAsset struct {
	Alt          string                  `json:"alt"`
	AssetID      openapi_types.UUID      `json:"asset_id"`
	ByteSize     int64                   `json:"byte_size"`
	Caption      LocalizedText           `json:"caption"`
	Crop         *map[string]interface{} `json:"crop,omitempty"`
	DownloadSrc  *string                 `json:"download_src,omitempty"`
	DurationMs   *int64                  `json:"duration_ms,omitempty"`
	Filename     string                  `json:"filename"`
	Height       *int                    `json:"height,omitempty"`
	Kind         MediaKind               `json:"kind"`
	Label        LocalizedText           `json:"label"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	MimeType     string                  `json:"mime_type"`
	PageCount    *int                    `json:"page_count,omitempty"`
	Position     int                     `json:"position"`
	PosterSrc    *string                 `json:"poster_src,omitempty"`
	PreviewSrc   *string                 `json:"preview_src,omitempty"`
	Role         ActivityAssetRole       `json:"role"`
	Src          *string                 `json:"src,omitempty"`
	Status       AssetStatus             `json:"status"`
	ThumbnailSrc *string                 `json:"thumbnail_src,omitempty"`
	Width        *int                    `json:"width,omitempty"`
}

// ActivityAssetRole defines model for ActivityAssetRole.
type ActivityAssetRole string

// ActivityAssetWrite defines model for ActivityAssetWrite.
type ActivityAssetWrite struct {
	Alt      string                  `json:"alt"`
	AssetID  openapi_types.UUID      `json:"asset_id"`
	Caption  LocalizedText           `json:"caption"`
	Crop     *map[string]interface{} `json:"crop,omitempty"`
	Label    LocalizedText           `json:"label"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Position int                     `json:"position"`
	Role     ActivityAssetRole       `json:"role"`
}

// ActivityCategory defines model for ActivityCategory.
type ActivityCategory string

// ActivityComment defines model for ActivityComment.
type ActivityComment struct {
	ActivityID   openapi_types.UUID `json:"activity_id"`
	ActivitySlug *string            `json:"activity_slug,omitempty"`
	Author       string             `json:"author"`
	Body         string             `json:"body"`
	CreatedAt    time.Time          `json:"created_at"`
	ID           openapi_types.UUID `json:"id"`
	Status       CommentStatus      `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// ActivityList defines model for ActivityList.
type ActivityList struct {
	Items  []Activity `json:"items"`
	Limit  int        `json:"limit"`
	Offset int        `json:"offset"`
	Total  int64      `json:"total"`
}

// ActivityProgress defines model for ActivityProgress.
type ActivityProgress string

// ActivityStatus defines model for ActivityStatus.
type ActivityStatus string

// ActivityWrite defines model for ActivityWrite.
type ActivityWrite struct {
	Assets         []ActivityAssetWrite `json:"assets"`
	Body           LocalizedText        `json:"body"`
	Caption        LocalizedText        `json:"caption"`
	Category       ActivityCategory     `json:"category"`
	Date           openapi_types.Date   `json:"date"`
	Pinned         bool                 `json:"pinned"`
	Progress       *ActivityProgress    `json:"progress,omitempty"`
	RelatedProject *string              `json:"related_project,omitempty"`
	Slug           *string              `json:"slug,omitempty"`
	Status         ActivityStatus       `json:"status"`
	Tags           []string             `json:"tags"`
	Title          LocalizedText        `json:"title"`
}

// AdminCommentList defines model for AdminCommentList.
type AdminCommentList struct {
	Items  []ActivityComment `json:"items"`
	Limit  int               `json:"limit"`
	Offset int               `json:"offset"`
	Total  int64             `json:"total"`
}

// AdminLoginRequest defines model for AdminLoginRequest.
type AdminLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// AdminSession defines model for AdminSession.
type AdminSession struct {
	ExpiresAt time.Time `json:"expires_at"`
	User      AdminUser `json:"user"`
}

// AdminUser defines model for AdminUser.
type AdminUser struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	ID          openapi_types.UUID  `json:"id"`
}

// AssetStatus defines model for AssetStatus.
type AssetStatus string

// CommentStatus defines model for CommentStatus.
type CommentStatus string

// ContactCategory defines model for ContactCategory.
type ContactCategory string

// ContactMessageRequest defines model for ContactMessageRequest.
type ContactMessageRequest struct {
	Category ContactCategory     `json:"category"`
	Company  string              `json:"company"`
	Email    openapi_types.Email `json:"email"`
	Message  string              `json:"message"`
	Name     string              `json:"name"`
}

// ContactMessageResponse defines model for ContactMessageResponse.
type ContactMessageResponse struct {
	Ok ContactMessageResponseOk `json:"ok"`
}

// ContactMessageResponseOk defines model for ContactMessageResponse.Ok.
type ContactMessageResponseOk bool

// CreateActivityRequest defines model for CreateActivityRequest.
type CreateActivityRequest = ActivityWrite

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	Author string `json:"author"`
	Body   string `json:"body"`
}

// EngagementSnapshot defines model for EngagementSnapshot.
type EngagementSnapshot struct {
	CommentLimit  int               `json:"comment_limit"`
	CommentOffset int               `json:"comment_offset"`
	CommentTotal  int64             `json:"comment_total"`
	Comments      []ActivityComment `json:"comments"`
	Liked         bool              `json:"liked"`
	Likes         int64             `json:"likes"`
}

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
	RequestID string `json:"request_id"`
}

// Health defines model for Health.
type Health struct {
	// Service Example: portfolio-api
	Service string       `json:"service"`
	Status  HealthStatus `json:"status"`

	// Version Example: dev
	Version string `json:"version"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LikeState defines model for LikeState.
type LikeState struct {
	Liked bool  `json:"liked"`
	Likes int64 `json:"likes"`
}

// LocalizedText defines model for LocalizedText.
type LocalizedText struct {
	En string `json:"en"`
	ID string `json:"id"`
}

// MediaAsset defines model for MediaAsset.
type MediaAsset struct {
	ByteSize     int64              `json:"byte_size"`
	CreatedAt    time.Time          `json:"created_at"`
	DurationMs   *int64             `json:"duration_ms,omitempty"`
	ErrorCode    *string            `json:"error_code,omitempty"`
	ErrorMessage *string            `json:"error_message,omitempty"`
	Filename     string             `json:"filename"`
	Height       *int               `json:"height,omitempty"`
	ID           openapi_types.UUID `json:"id"`
	Kind         MediaKind          `json:"kind"`
	MimeType     string             `json:"mime_type"`
	PageCount    *int               `json:"page_count,omitempty"`
	ReadyAt      *time.Time         `json:"ready_at,omitempty"`
	Status       AssetStatus        `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
	Width        *int               `json:"width,omitempty"`
}

// MediaKind defines model for MediaKind.
type MediaKind string

// ModerateCommentRequest defines model for ModerateCommentRequest.
type ModerateCommentRequest struct {
	Status CommentStatus `json:"status"`
}

// PresignAssetUploadRequest defines model for PresignAssetUploadRequest.
type PresignAssetUploadRequest struct {
	ByteSize int64     `json:"byte_size"`
	Filename string    `json:"filename"`
	Kind     MediaKind `json:"kind"`
	MimeType string    `json:"mime_type"`
}

// PresignedAssetUpload defines model for PresignedAssetUpload.
type PresignedAssetUpload struct {
	Asset     MediaAsset                 `json:"asset"`
	ExpiresAt time.Time                  `json:"expires_at"`
	Method    PresignedAssetUploadMethod `json:"method"`
	UploadURL string                     `json:"upload_url"`
}

// PresignedAssetUploadMethod defines model for PresignedAssetUpload.Method.
type PresignedAssetUploadMethod string

// Readiness defines model for Readiness.
type Readiness struct {
	// Service Example: portfolio-api
	Service string          `json:"service"`
	Status  ReadinessStatus `json:"status"`
}

// ReadinessStatus defines model for Readiness.Status.
type ReadinessStatus string

// ServiceInfo defines model for ServiceInfo.
type ServiceInfo struct {
	// Commit Example: unknown
	Commit string `json:"commit"`

	// Name Example: portfolio-api
	Name string `json:"name"`

	// Version Example: dev
	Version string `json:"version"`
}

// SetLikeRequest defines model for SetLikeRequest.
type SetLikeRequest struct {
	Liked bool `json:"liked"`
}

// UpdateActivityRequest defines model for UpdateActivityRequest.
type UpdateActivityRequest struct {
	Assets         []ActivityAssetWrite `json:"assets"`
	Body           LocalizedText        `json:"body"`
	Caption        LocalizedText        `json:"caption"`
	Category       ActivityCategory     `json:"category"`
	Date           openapi_types.Date   `json:"date"`
	Pinned         bool                 `json:"pinned"`
	Progress       *ActivityProgress    `json:"progress,omitempty"`
	RelatedProject *string              `json:"related_project,omitempty"`
	Slug           *string              `json:"slug,omitempty"`
	Status         ActivityStatus       `json:"status"`
	Tags           []string             `json:"tags"`
	Title          LocalizedText        `json:"title"`
	Version        int64                `json:"version"`
}

// ActivityID defines model for ActivityID.
type ActivityID = openapi_types.UUID

// ActivitySlug defines model for ActivitySlug.
type ActivitySlug = string

// AssetID defines model for AssetID.
type AssetID = openapi_types.UUID

// CommentID defines model for CommentID.
type CommentID = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = Error

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// ListPublicActivitiesParams defines parameters for ListPublicActivities.
type ListPublicActivitiesParams struct {
	Limit    *Limit            `form:"limit,omitempty" json:"limit,omitempty"`
	Offset   *Offset           `form:"offset,omitempty" json:"offset,omitempty"`
	Search   *string           `form:"search,omitempty" json:"search,omitempty"`
	Category *ActivityCategory `form:"category,omitempty" json:"category,omitempty"`
}

// GetActivityEngagementParams defines parameters for GetActivityEngagement.
type GetActivityEngagementParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAdminActivitiesParams defines parameters for ListAdminActivities.
type ListAdminActivitiesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetAdminAssetContentParams defines parameters for GetAdminAssetContent.
type GetAdminAssetContentParams struct {
	Variant GetAdminAssetContentParamsVariant `form:"variant" json:"variant"`
}

// GetAdminAssetContentParamsVariant defines parameters for GetAdminAssetContent.
type GetAdminAssetContentParamsVariant string

// ListAdminCommentsParams defines parameters for ListAdminComments.
type ListAdminCommentsParams struct {
	Limit      *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
	ActivityID *openapi_types.UUID `form:"activity_id,omitempty" json:"activity_id,omitempty"`
	Status     *CommentStatus      `form:"status,omitempty" json:"status,omitempty"`
}

// GetAssetContentParams defines parameters for GetAssetContent.
type GetAssetContentParams struct {
	Variant GetAssetContentParamsVariant `form:"variant" json:"variant"`
}

// GetAssetContentParamsVariant defines parameters for GetAssetContent.
type GetAssetContentParamsVariant string

// CreateActivityCommentJSONRequestBody defines body for CreateActivityComment for application/json ContentType.
type CreateActivityCommentJSONRequestBody = CreateCommentRequest

// SetActivityLikeJSONRequestBody defines body for SetActivityLike for application/json ContentType.
type SetActivityLikeJSONRequestBody = SetLikeRequest

// CreateAdminActivityJSONRequestBody defines body for CreateAdminActivity for application/json ContentType.
type CreateAdminActivityJSONRequestBody = CreateActivityRequest

// UpdateAdminActivityJSONRequestBody defines body for UpdateAdminActivity for application/json ContentType.
type UpdateAdminActivityJSONRequestBody = UpdateActivityRequest

// PresignAdminAssetUploadJSONRequestBody defines body for PresignAdminAssetUpload for application/json ContentType.
type PresignAdminAssetUploadJSONRequestBody = PresignAssetUploadRequest

// LoginAdminJSONRequestBody defines body for LoginAdmin for application/json ContentType.
type LoginAdminJSONRequestBody = AdminLoginRequest

// ModerateAdminCommentJSONRequestBody defines body for ModerateAdminComment for application/json ContentType.
type ModerateAdminCommentJSONRequestBody = ModerateCommentRequest

// SendContactMessageJSONRequestBody defines body for SendContactMessage for application/json ContentType.
type SendContactMessageJSONRequestBody = ContactMessageRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetServiceInfo Read API build information
	// (GET /api/v1)
	GetServiceInfo(c *gin.Context)
	// ListPublicActivities List published activities
	// (GET /api/v1/activities)
	ListPublicActivities(c *gin.Context, params ListPublicActivitiesParams)
	// GetPublicActivity Read a published activity
	// (GET /api/v1/activities/{slug})
	GetPublicActivity(c *gin.Context, slug ActivitySlug)
	// CreateActivityComment Publish a visitor comment
	// (POST /api/v1/activities/{slug}/comments)
	CreateActivityComment(c *gin.Context, slug ActivitySlug)
	// GetActivityEngagement Read likes and visible comments
	// (GET /api/v1/activities/{slug}/engagement)
	GetActivityEngagement(c *gin.Context, slug ActivitySlug, params GetActivityEngagementParams)
	// SetActivityLike Set the current visitor like state
	// (PUT /api/v1/activities/{slug}/like)
	SetActivityLike(c *gin.Context, slug ActivitySlug)
	// ListAdminActivities List all activities
	// (GET /api/v1/admin/activities)
	ListAdminActivities(c *gin.Context, params ListAdminActivitiesParams)
	// CreateAdminActivity Create an activity
	// (POST /api/v1/admin/activities)
	CreateAdminActivity(c *gin.Context)
	// DeleteAdminActivity Delete an activity
	// (DELETE /api/v1/admin/activities/{id})
	DeleteAdminActivity(c *gin.Context, id ActivityID)
	// GetAdminActivity Read an activity by ID
	// (GET /api/v1/admin/activities/{id})
	GetAdminActivity(c *gin.Context, id ActivityID)
	// UpdateAdminActivity Replace an activity
	// (PUT /api/v1/admin/activities/{id})
	UpdateAdminActivity(c *gin.Context, id ActivityID)
	// PresignAdminAssetUpload Create an asset and presign its original upload
	// (POST /api/v1/admin/assets/uploads)
	PresignAdminAssetUpload(c *gin.Context)
	// DeleteAdminAsset Delete an asset that is not attached to an activity
	// (DELETE /api/v1/admin/assets/{id})
	DeleteAdminAsset(c *gin.Context, id AssetID)
	// GetAdminAsset Read upload and processing status
	// (GET /api/v1/admin/assets/{id})
	GetAdminAsset(c *gin.Context, id AssetID)
	// CompleteAdminAssetUpload Verify a direct upload and enqueue media processing
	// (POST /api/v1/admin/assets/{id}/complete)
	CompleteAdminAssetUpload(c *gin.Context, id AssetID)
	// GetAdminAssetContent Stream asset bytes for an authenticated administrator
	// (GET /api/v1/admin/assets/{id}/content)
	GetAdminAssetContent(c *gin.Context, id AssetID, params GetAdminAssetContentParams)
	// LoginAdmin Start an administrator session
	// (POST /api/v1/admin/auth/login)
	LoginAdmin(c *gin.Context)
	// LogoutAdmin Revoke the current administrator session
	// (POST /api/v1/admin/auth/logout)
	LogoutAdmin(c *gin.Context)
	// RefreshAdminSession Rotate an administrator session
	// (POST /api/v1/admin/auth/refresh)
	RefreshAdminSession(c *gin.Context)
	// GetAdminSession Read the current administrator session
	// (GET /api/v1/admin/auth/session)
	GetAdminSession(c *gin.Context)
	// ListAdminComments List comments for moderation
	// (GET /api/v1/admin/comments)
	ListAdminComments(c *gin.Context, params ListAdminCommentsParams)
	// DeleteAdminComment Permanently delete a comment
	// (DELETE /api/v1/admin/comments/{comment_id})
	DeleteAdminComment(c *gin.Context, commentID CommentID)
	// ModerateAdminComment Change comment visibility
	// (PATCH /api/v1/admin/comments/{comment_id})
	ModerateAdminComment(c *gin.Context, commentID CommentID)
	// GetAssetContent Redirect to a short-lived URL for a publicly linked asset
	// (GET /api/v1/assets/{id}/content)
	GetAssetContent(c *gin.Context, id AssetID, params GetAssetContentParams)
	// SendContactMessage Deliver a portfolio contact message
	// (POST /api/v1/contact)
	SendContactMessage(c *gin.Context)
	// GetHealth Check process health
	// (GET /healthz)
	GetHealth(c *gin.Context)
	// GetReadiness Check dependency readiness
	// (GET /readyz)
	GetReadiness(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetServiceInfo operation middleware
func (siw *ServerInterfaceWrapper) GetServiceInfo(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetServiceInfo(c)
}

// ListPublicActivities operation middleware
func (siw *ServerInterfaceWrapper) ListPublicActivities(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPublicActivitiesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "search", c.Request.URL.Query(), &params.Search, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", c.Request.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter category: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPublicActivities(c, params)
}

// GetPublicActivity operation middleware
func (siw *ServerInterfaceWrapper) GetPublicActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPublicActivity(c, slug)
}

// CreateActivityComment operation middleware
func (siw *ServerInterfaceWrapper) CreateActivityComment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateActivityComment(c, slug)
}

// GetActivityEngagement operation middleware
func (siw *ServerInterfaceWrapper) GetActivityEngagement(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActivityEngagementParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetActivityEngagement(c, slug, params)
}

// SetActivityLike operation middleware
func (siw *ServerInterfaceWrapper) SetActivityLike(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug ActivitySlug

	err = runtime.BindStyledParameterWithOptions("simple", "slug", c.Param("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter slug: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SetActivityLike(c, slug)
}

// ListAdminActivities operation middleware
func (siw *ServerInterfaceWrapper) ListAdminActivities(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminActivitiesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAdminActivities(c, params)
}

// CreateAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) CreateAdminActivity(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAdminActivity(c)
}

// DeleteAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ActivityID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminActivity(c, id)
}

// GetAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) GetAdminActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ActivityID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminActivity(c, id)
}

// UpdateAdminActivity operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdminActivity(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id ActivityID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAdminActivity(c, id)
}

// PresignAdminAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) PresignAdminAssetUpload(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PresignAdminAssetUpload(c)
}

// DeleteAdminAsset operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminAsset(c, id)
}

// GetAdminAsset operation middleware
func (siw *ServerInterfaceWrapper) GetAdminAsset(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminAsset(c, id)
}

// CompleteAdminAssetUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteAdminAssetUpload(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CompleteAdminAssetUpload(c, id)
}

// GetAdminAssetContent operation middleware
func (siw *ServerInterfaceWrapper) GetAdminAssetContent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAdminAssetContentParams

	// ------------- Required query parameter "variant" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "variant", c.Request.URL.Query(), &params.Variant, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminAssetContent(c, id, params)
}

// LoginAdmin operation middleware
func (siw *ServerInterfaceWrapper) LoginAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LoginAdmin(c)
}

// LogoutAdmin operation middleware
func (siw *ServerInterfaceWrapper) LogoutAdmin(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LogoutAdmin(c)
}

// RefreshAdminSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshAdminSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshAdminSession(c)
}

// GetAdminSession operation middleware
func (siw *ServerInterfaceWrapper) GetAdminSession(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAdminSession(c)
}

// ListAdminComments operation middleware
func (siw *ServerInterfaceWrapper) ListAdminComments(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminCommentsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "activity_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "activity_id", c.Request.URL.Query(), &params.ActivityID, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter activity_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", c.Request.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListAdminComments(c, params)
}

// DeleteAdminComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdminComment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "comment_id" -------------
	var commentID CommentID

	err = runtime.BindStyledParameterWithOptions("simple", "comment_id", c.Param("comment_id"), &commentID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter comment_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAdminComment(c, commentID)
}

// ModerateAdminComment operation middleware
func (siw *ServerInterfaceWrapper) ModerateAdminComment(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "comment_id" -------------
	var commentID CommentID

	err = runtime.BindStyledParameterWithOptions("simple", "comment_id", c.Param("comment_id"), &commentID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter comment_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ModerateAdminComment(c, commentID)
}

// GetAssetContent operation middleware
func (siw *ServerInterfaceWrapper) GetAssetContent(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id AssetID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAssetContentParams

	// ------------- Required query parameter "variant" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "variant", c.Request.URL.Query(), &params.Variant, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter variant: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAssetContent(c, id, params)
}

// SendContactMessage operation middleware
func (siw *ServerInterfaceWrapper) SendContactMessage(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SendContactMessage(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetHealth(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
	router.GET(options.BaseURL+"/api/v1", wrapper.GetServiceInfo)
	router.POST(options.BaseURL+"/api/v1/contact", wrapper.SendContactMessage)
	router.POST(options.BaseURL+"/api/v1/admin/auth/login", wrapper.LoginAdmin)
	router.POST(options.BaseURL+"/api/v1/admin/auth/refresh", wrapper.RefreshAdminSession)
	router.POST(options.BaseURL+"/api/v1/admin/auth/logout", wrapper.LogoutAdmin)
	router.GET(options.BaseURL+"/api/v1/admin/auth/session", wrapper.GetAdminSession)
	router.GET(options.BaseURL+"/api/v1/activities", wrapper.ListPublicActivities)
	router.GET(options.BaseURL+"/api/v1/activities/:slug", wrapper.GetPublicActivity)
	router.GET(options.BaseURL+"/api/v1/activities/:slug/engagement", wrapper.GetActivityEngagement)
	router.PUT(options.BaseURL+"/api/v1/activities/:slug/like", wrapper.SetActivityLike)
	router.POST(options.BaseURL+"/api/v1/activities/:slug/comments", wrapper.CreateActivityComment)
	router.GET(options.BaseURL+"/api/v1/admin/activities", wrapper.ListAdminActivities)
	router.POST(options.BaseURL+"/api/v1/admin/activities", wrapper.CreateAdminActivity)
	router.DELETE(options.BaseURL+"/api/v1/admin/activities/:id", wrapper.DeleteAdminActivity)
	router.GET(options.BaseURL+"/api/v1/admin/activities/:id", wrapper.GetAdminActivity)
	router.PUT(options.BaseURL+"/api/v1/admin/activities/:id", wrapper.UpdateAdminActivity)
	router.POST(options.BaseURL+"/api/v1/admin/assets/uploads", wrapper.PresignAdminAssetUpload)
	router.DELETE(options.BaseURL+"/api/v1/admin/assets/:id", wrapper.DeleteAdminAsset)
	router.GET(options.BaseURL+"/api/v1/admin/assets/:id", wrapper.GetAdminAsset)
	router.POST(options.BaseURL+"/api/v1/admin/assets/:id/complete", wrapper.CompleteAdminAssetUpload)
	router.GET(options.BaseURL+"/api/v1/assets/:id/content", wrapper.GetAssetContent)
	router.GET(options.BaseURL+"/api/v1/admin/assets/:id/content", wrapper.GetAdminAssetContent)
	router.GET(options.BaseURL+"/api/v1/admin/comments", wrapper.ListAdminComments)
	router.DELETE(options.BaseURL+"/api/v1/admin/comments/:comment_id", wrapper.DeleteAdminComment)
	router.PATCH(options.BaseURL+"/api/v1/admin/comments/:comment_id", wrapper.ModerateAdminComment)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1tc9s4kv9XQfG/Vf97kG3F48zO6s2VN9m5da1z67LjuxfZnAsiWyLWJMABQDmalL/7FZ5I8JmUJcWZ",
	"mneWRQKN7l83+gnQ1yBkacYoUCmCxdcgwxynIIHrT5ehJBsit1fv1SdCg0WQYRkHs4DiFIJFQKJgFnD4",
	"JSccomAheQ6zQIQxpFi9sWI8xTJYBHmun5TbTL0lJCd0HTw/z4oZ7pJ83TGHUF/1zZLiL9dA1zIOFn88",
	"nwUpoe7jm5kaSwJXo/7vJ3zy6/zkT5///V/+Y3FSfPjXf/tDO2VCgDzcwt+xNAXaPUFovn948UTXJCWy",
	"mOSXHPi2nCXRX/oDRrDCeSKDxfl8pjhL0jwNFm/nmq/mw5tiGkIlrIHref6+WgnonIiZb1tn8seet4z9",
	"rBggMkYFaFT+GUe38EsOQs8WMiqB6j9xliUkxJIwevZPwaj6XznfHzisgkXw/85KxJ+Zb8XZXzhndqoI",
	"RMhJpgYJFsHHGBA3k6EMbxOGI0QEInSDExKdBlqSdJWQ8GjECJbzEFBopxXoicgYhTnnQCUSwDfAkZBY",
	"gibvZ8aXJIqAHpdZjJM1oYpXlEmEk4Q9geHXFVUKiRMzzFGJClmeRJqgpWJgmiUgIUJRDkgyhB3zQI2l",
	"af0vJn9mOY2OSiZEpZSfsGHgSlGhSboDviEh3FO8wSTBywQOT9wlchZIs4iEoAQrIc0Yx5wkW5SX5Ggq",
	"PzL2AdOt1VNxBP4xhlJMt46J4jSYBTHgyG5ltyD59uRyJYFXZ+s1a2qee4pzGTNOfoUj4OAylzFQaUdF",
	"K0wSiBDjSMaABAih/qu1CiWMroEjZ4menXGtbN2azCgiajSc3HCWAZdEGdIVTgTMgsz719cAq11P/0Uk",
	"pGJoGW4WvVkquVsOYs7xVn1esmg7NMg1C3GiuPsRvuhBQmy5Mfk9CWvGt2OpfueeV+9ywBKiBywr22qE",
	"JZxIkkJzb53pLxtPtz1IohF79SzICKUGY/arJWMJYKq/42zNQRghJcnfV8Hi07hV3rg3nz/PApon1mYo",
	"T0LvrIled8bZP8FsYtVnWugU1lmrOV7D70ks89GYujNPK1DhdRWSjZHrsJNEGrs4CT95Fk3GwAa4sFgt",
	"XiBU/ngRDHpMpVf3yejJzKlfqQIeqCsYnTmsaSRZ4BQctixzfKisrCT5c0EVW2rZe/64UeiJtiORrcLR",
	"i3oYqQPLrYQHQX6FyRx9gd3gLOteqwFzB7hLzkXsiSr38EHwcJQWRTnXNv7BYLp7rfPO2b21r0gCxtdu",
	"kUAMZB3L+m43POgjMa5PHzc/QETw39SDz7MgwUtIJvM/BYkjLPGQDBo8T0kKD+a/LavO8BoeQpbTHVae",
	"MUEclvqCE/2kBD5a6hmHDYGn0c9zNmzIKkp7q15QxnbkBCONshras8hxni4pJsnodTyRSO0T0+RQM5LK",
	"wHjmxDcWvsUsVMEC2MHSx4snYcvjghODZvHWigSoWsanIGQb4MEsWOMkMUEvlhKHsYrfvdFKXlRG+x9O",
	"jBcx3dJ6++/b+Xz2Qsv7Ta3nkQ3HePXeUf+GkFui1WGzjsc+GL7zHF2HQufAzYIEMKdKqMpJIIkGZBgT",
	"2MAgIm1Waioc7dtjkVY87xzJQethIrBWK+8ijCaed/DoRy5gnM20zCyt5nT/sg4jj9EFU2bOeay4h6Ti",
	"Dnoz9+Hqmoipsi988knxYpvPnrhEZVMJWZFbbH4nmcRJqwM1sJsYgmdFDrRIUZoR+/h04wVjTv88rRMx",
	"yTLtj8OXLGFalH1ad1fAqVDmfJkQEesxIo5XiqzYZPH6BtppL3lBxG/m+57D/tEh/CuJzb0t/835fPYd",
	"xOrexD9e1KszjWlT/OXKvPnG82heFNfvEmlbFAzE1a0mIkoJtZb/aObUbdvfqVVVLLtma0K9ss4EnkGK",
	"SZVW85+Zj73ztxdtWo2FeGI8qqvW/HwIqrVluxmLATsXemdyuFPX+CUjHMQkZyYXJtfdiyBF0r1oEaQ3",
	"ox2qc0n3dqIJ64mIyBK8fehMWXQLdTenrba6yvyzYmzSITgv+vV26V9yyLV5yLOE4chs/hlnoRIxNUVr",
	"rK2NSeO37t1VL9EbfUMEWerAtGfnf8eoxKFsCwjWQIFjvSpdcVNeibJyTFl+ZnJPfWN+ACHwGnbTybF7",
	"cp1+tZ2zNMN0W1PJ89YA9wWqn5rlNePo+eAm5UBb34ynGAw/rWsXXMLQ0WanaoNkXUimPj5RSuzRA4xy",
	"BMqZCvemRjd7bCdHxx5uP/IxM8kfsg7l52JEqx27gbCMGj1J/TQsX+e9VuE3UcDV6KyNZ3+ha7zWMfkd",
	"xZmI2WQlsz0iPXu8e6Rvr3fPdO/5/SkS+/6e3ZbHLm9bfSUmk1lXvwrrGnyqM8VbpKPNEdIqWdfaMGWH",
	"3+GdkEXtu6dn3AbMkBqhfL5tMbagbpM7A26QXkTlnbYh/wo4MdngCYu1nQfGG8JppgKBIGNcrlhC2AnO",
	"SH+qxu2LFQvWWsgrh49gM+hKOLq8KKGvwnZNHkFt9lNt9aE1YhjV1bhqIrppK05HYYp2O2a6+LRLrfJF",
	"ZcZdWgX2WuzTavbgtH8wljePezZh8I2DVBNHJlcnFx0PVwXU7nufnA9TXdulD2Ef9bVKOc1PJnsVNS0z",
	"W1bzy2ljU82l5DyTTFLj7W5IBCyYBREL885axQcWAX+pa7hTBr9u+LvrhTccBFlTLdd7HRzuRuaAmXLt",
	"uec/nr+5uHAuao/p8vW6EiG9HXSKX6aWkybrgWWztltO0yMIiDxR7JIgH7Xyogtul2xNCjJmFa24uf/Y",
	"qgAm2/CQ86qznnMyXEASxrutJHfszJWB23h5Czgi1OW5j++4uWSK12vawp8h76xtZban9oqu2A4hmIm9",
	"yqXl9JGyJxr0ZA4m8GFnv9SSZiftd0rvQCq/dDcj1emZtnqYbdPf6z1jX9mD2dcagXvq0etm4GfdfAth",
	"zonc3imqXGE8BCHeMfZIoDgZEZqPxdGIAgEPOEoJfTAvleLFGfkbbI07suIg4onj2beaAyqiiYV8aNJJ",
	"2jk0w3zIY5ymOEKXJCIJ+plIjuOg0a/8148fb9DlzRVaMY5a3/n/AhUkIVfBRlmCpRLG6T/ox1ifZpAc",
	"hxIRgeBLhmkEESI05Do/gpNka445AA5jtMThI9AIrQDLnMPpP2hRklkEN8VcDhaKPA//i2B++uZ0risg",
	"GVCldovgh9P56Q86fy9jLboznJGzzRv159qYf4Uo7cNfRcEi+E+QvtWoHVE5n8/31iruT9PWMH5zhZTI",
	"EKYRWuYkUXwzMCeM2r7wPE0x3wYLbcO1uBpPuuLW4lNwtxUS0kCj2vLhzArOalQrS66JkDf5MiHhZfnw",
	"rHKkrEORy0fOzHElpcMDD9rzRurJtgNHAjAP46DjnJhO1zbMZ/tIXqZ2nMCadebnzwfER6V5owUgN3hN",
	"qHLJUdFVgEpp6tMaF4actlkKss+8Y1fPs+DtmFeqR32qSFTktlLkAdHDUQcYz76KJF8/96lpBZLbyYCs",
	"nFA8iiBbhVhn1BZFIDFJrPwuhoVRnGXah/S0HcFN+W13kd6Zn0HOmGiRY7W+4BLHe5ClBvSfbcJ/L2Js",
	"LVw8V52JosGjAqU3e4dSkWFvIsp+hWygv6sduJj/MPxKeQZxF7BenP9p+IX6gbN9gNwqHcJoQwSRjKOw",
	"AJ4DeVnEGQI5lE/2WCsnOW/cl6F8tv8t95BGsKUo1gZee9rVyUWFFubMq3aDsmLLc5blW5pJnVHXdNmS",
	"PvKKSdNxpIbThjJvQdBdiSAV0L1OC1mLNkfZxv0hrCzAtADLRKJRHVB4veawVp90Jvl3Y9mE+h1IfUY1",
	"7FTNMWhXEevYWEP3Hh0z1HgdXnzJHUQogg3wLTK5LQvLN8OCrJxpfoH0bcpDc7ua7Pj0WbGr5u7jJOlw",
	"9JUoUcVhnPV7gp7st8EhHbl6VuobeXKtob8LBV7sw+0AmYv5CENT3I1xFIwZgSFMW6ORJsR6DM/ZVxI9",
	"m1tKEjC1+ioM3+v/12G422Z79b7NtlyY6VsFbqiKTl8gvan7yusTtxHBeHHPup3uA4pxflxTUMkKHAMY",
	"h5ezyTWUUkbLLbp6P7h7tLnHttCwX3Hvf+dpr4cc2U8eBTdb7T/yzvP9265byBIcvmiv0gdYzkzNtidz",
	"5loRNOa9IvhhkNvd+HBkv6m18N+GZPU14hAyHulQT8SMy5OEbCBCEeEQSmR4jO5vr4+M86nR4lFdLM04",
	"nW0xrEZECnvtF04sz5qYNseuuvE8xe+yzQwTzbe912+kx+WtkmzU0osVPgEHxCFlm6Pbv8NnEV61t6dl",
	"ImMsi+vl9H0LEOlb3PosqkPfkCu4b2Ttb1f2G42686KGRZWswCvdm4/kPloTbhTZHdBC1WOd04zUmbs/",
	"sKdoZZ9o2Xu/O2QZytEGOFkRaHDSHIX73QweHM3/rQSwRbjmmyhxANVSQKkSJKqcQ9wN3wWorLGsIuJO",
	"csCp0Enf5VaC+ouzfB3r/1zeXCGOZQxcWWqKOBiCCV3PkGCV6wxNBxMSOd+QjS2VSHPXqWaZ0tOtQAKn",
	"cGLvFV0xjkJMN9g8ffP+Z8TNZY+n6C7PMsalQBzTNZQXQuo2oR6D/84ueGft7Ggg2WBOsB63+x5f1+MY",
	"gfI89dvmYqnAu2wpKG8Za2t8nGYcWChBnggtxKqRKHrkloRiTUp9pg4vWqNA24Dz+Y/HmvoGc0lwYrc8",
	"A0SFDlwV/2/NNB3e0hj9bvKVIlzeUap2AqVAREiOpT77NdrW5DI+S9ia0O4dVN8KoAc6ULzavHvg2FkW",
	"/06AFnhr2pDIwxAgsvuuFmLdfAoTkAiQtZtv70CelC2jJVUNzXrdCmLqmke6RFjDUoUVkGZ7vEp4F6VV",
	"b41gVsu10LX6rMRcau319dWBqKm3uYz7tJaZ9Gqn2rJclno7FGVb/CMOG/ZoQe5QHSaA+ctKHa8vjXKr",
	"F1qpl+9BLK7Tu1Mut+aBis35hrbNklOzbtykRk1z2j5N26vFzgtV3Idd7YhAA3dMuvTdy+EmyptserMp",
	"rwBpRV6k23N5zc0TOoWxP2Pht9v2d9e8KxvVvk0bf/XGwwm/e9JxKsAlfEZ2gNTOf34+NIT9i8N6m4Cc",
	"CMsWoNQci1XbaPnjH8fy547UP1SsWgUi5YIbwC9g2wP+s6/lT+yMrTjs2nde/tjPuKqD683eQ5vHbyAQ",
	"vQGeYjVi4hpfEG7pxG6IXp/mCuOmRN0J8r3KdP+xacdB92/UBtBzlMA1zVqZ/J5qmVxVjXWqyvLPtImT",
	"pK2C1WHZJqRtzXEok9YRCHPQOrXWApQMmSOtSEjG8RqQYDb1Q9UugzIsGmneU/ROX3wuUJoLqetxAlQA",
	"xyFSvhZOxAItOXsS6hkOq1zon1tasSRhT0qViwcVhjgTwmV5XdL4FN0LEy1pG45sRhWxFZIxEYizXILJ",
	"Tpll6eKgWpuiJiH00dYGWw4sdaWFf4sZ4R/mf2wC4tYy2f4Eltf+YLBw4rCg+x8q8dc1MyZF/T3mN+pa",
	"byh4fvW1Rs8P72LV/e21zTprhIXJ1sHOXblQ6HFLQtQ7fd0euN8Bjao3/h2q57n17scjbzkddxu27Dz2",
	"EaTMayZtAsFqzFHPtO186uL8OD8tp2+WRBlnGxIBRxyUZpsfFit/FM8yThtae1vU6f4SkO/t6Ni7DsAC",
	"H5UXXjo1sRiwehLrC+N+7Us12DvlDghLO0MHhy9vrlzNFRGBDMXb+vn7dzGEj8VzsaO59eS9vu+kd83l",
	"jSwHXHY5Sc/Kld4RKVAEGdAIaEjAOBd6ET6KDk+T92uFBTlbJZPqjxS2yMV7nHusbUpHu3d849yBeskm",
	"xAmKYAMJy2xsoS/rCWIps8XZWaIeiJmQi5/mP811/GCnaCbGza8tGqBoLrvfPDkt3QlLl/I2als7k1gS",
	"urZ51JMlFvW0l0seCW88L3vUHNP6jy1XeiiWVYYp+1ebw1xWM3FujBRTezCsSU/fcO/1vnwi2UnNaTHN",
	"ELZLIiErCLehEn99cLMrt9NpXA5nHrfK7bQa7C5VCMsVGA/Un6Br6BvgggilDG6Q8qRoeW61GMc7MzfE",
	"ThdIlCmSxoKLQGKEhJ2VdgzwBnNm+vnz8/8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
